### ISSUE TITLE
win_unzip Does not appear to set defaults

### ISSUE THREAD

**Issue by blakfeld** [ansible/ansible-modules-extras#1072]
When using win_unzip it, it fails on every unset parameters, claiming that the win_unzip object does not contain that attribute.

Example, if I run:

```
- name: Unzipping Thing
  win_unzip:
    src: C:\some\source.zip
    dest: C:\some\dest
```

I'll get an error at:

```
If ($params.creates) {
```

If I do something like:

```
- name: Unzipping thing
  win_unzip:
    src: C:\some\source.zip
    dest: C:\some\dest
    creates: $false
```

It will then fail at:

```
If ($params.recurse) {
```

and so on and so forth

If I set all those parameters to false, it fails with a message that says it succeeded. The directory appears to be created, but it does not unzip the file.
