### ISSUE TITLE
gluster_volume: no replicas not possible

### ISSUE THREAD

**Issue by tobias-nawa** [ansible/ansible-modules-extras#1074]
It's not possible to set up gluster without clusters. I always get the following error.
My ansible version is 1.9.2 on Mac os

failed: [fileserver] => {"failed": true, "parsed": false}
BECOME-SUCCESS-gzczujddrapqbuwwbbcknuyjaqorlryu
Traceback (most recent call last):
  File "/root/.ansible/tmp/ansible-tmp-1444394830.43-46504764465318/gluster_volume", line 2045, in <module>
    main()
  File "/root/.ansible/tmp/ansible-tmp-1444394830.43-46504764465318/gluster_volume", line 365, in main
    probe_all_peers(cluster, peers, myhostname)
  File "/root/.ansible/tmp/ansible-tmp-1444394830.43-46504764465318/gluster_volume", line 253, in probe_all_peers
    for host in hosts:
TypeError: 'NoneType' object is not iterable

Here is the code I use - but I can also just use state and name => Same error:
- name: Setup gluster volume
  gluster_volume:
    state: "present"
    name: "{{ gluster_brick_name }}"
    brick: "{{ gluster_brick_dir }}"
    force: yes
  run_once: true

**Comment by robynbergeron** [comment]
[module: system/gluster_volume.py]

**Comment by robynbergeron** [comment]
Hi @Bullettoothtobi -- thanks for submitting this bug report. 

@rosmo -- thanks in advance for taking a look at this bug report and for your ongoing work in maintaining this module.

**Comment by rosmo** [comment]
@Bullettoothtobi, have you tried just passing one host to clusters?

**Comment by tobias-nawa** [comment]
Yes. But it didn’t work.

**Comment by rosmo** [comment]
@Bullettoothtobi, can you give me the module parameters you used?

**Comment by jgeusebroek** [comment]
@rosmo I'm having the same issue.

``` yaml
  - name: Gluster Test
    gluster_volume:
      name: "test_volume"
      brick: '/brick_test'
      force: True
      state: present
```

```
failed: [www-app-1.localhost] => {"failed": true, "parsed": false}
BECOME-SUCCESS-ygcjwqrafinyuzexahiuxlqvmwwnjkxt
Traceback (most recent call last):
  File "/home/vagrant/.ansible/tmp/ansible-tmp-1451768104.05-202266410922301/gluster_volume", line 2052, in <module>
    main()
  File "/home/vagrant/.ansible/tmp/ansible-tmp-1451768104.05-202266410922301/gluster_volume", line 365, in main
    probe_all_peers(cluster, peers, myhostname)
  File "/home/vagrant/.ansible/tmp/ansible-tmp-1451768104.05-202266410922301/gluster_volume", line 253, in probe_all_peers
    for host in hosts:
TypeError: 'NoneType' object is not iterable
```

``` yaml
  - name: Gluster Test
    gluster_volume:
      name: "test_volume"
      cluster: "{{ansible_fqdn}}"
      brick: '/brick_test'
      force: True
      state: present
```

```
failed: [www-app-1.localhost] => {"failed": true}
msg: failed to probe peer www-app-1.localhost
```
