### ISSUE TITLE
Consul: configuration must be `service_name` not `name`

### ISSUE THREAD

**Issue by micahlmartin** [ansible/ansible-modules-extras#1086]
The documentation shows a service definition likes this:

```
- name: register nginx service with the local consul agent
  consul:
    name: nginx
    service_port: 80
```

This actually causes the error:

```
fatal: [devbox]: FAILED! => {"changed": false, "failed": true, "msg": "unsupported parameter for module: name"}
```

The proper definition should be:

```
- name: register nginx service with the local consul agent
  consul:
    service_name: nginx
    service_port: 80
```
