### ISSUE TITLE
win_iis_webapppool: The property 'Value' cannot be found on this object

### ISSUE THREAD

**Issue by rriggs** [ansible/ansible-modules-extras#1093]
Please see https://github.com/ansible/ansible/issues/12494

``` text
TASK [foo : Create fooservice app pool] **************************************
fatal: [foohost]: FAILED! => {"changed": false, "failed": true, "msg": "The property 'Value' cannot be found on this object. Verify that the property exists."}
```

``` yml
- name: Create fooservice app pool
  win_iis_webapppool:
    name: "fooservice"
    state: started
    attributes: "enable32BitAppOnWin64:true|managedRuntimeVersion:v4.0|managedPipelineMode:0"
```

> it sounds like a result of #12384, which turned on strict mode by default for modules.
> Updating the module to include Set-StrictMode -Off just below the # POWERSHELL_COMMON line
> would be a quick workaround to get it working again.
