### ISSUE TITLE
win_iis_webapppool: The property 'attributes' cannot be found on this object.

### ISSUE THREAD

**Issue by rriggs** [ansible/ansible-modules-extras#1097]
My handler that restarts an app pool is now failing.

``` yml
# Restart the Foo app pool
- name: restart Foo
  win_iis_webapppool:
    name: "Foo"
    state: restarted
```

```
FAILED! => {"changed": false, "failed": true, "msg": "The property 'attributes' cannot be found on this object. Verify that the property exists."}
```

Putting in a dummy attributes line seems to fix the problem.
