### ISSUE TITLE
npm module ignores PATH set with Ansible environment keyword

### ISSUE THREAD

**Issue by brunokindt** [ansible/ansible-modules-extras#1154]
The npm and node are executables are located in ~/.local/bin. Using npm.executable the npm executable is found. Using the ansible environment keyword to update the PATH environment to include the npm executable results in `msg: Failed to find required executable npm`.
## ok

```
- name: Install npm packages 2
  npm:
    name: "{{ item }}"
    global: yes
    state: latest
    executable: "~/.local/bin/npm"
  with_items: node.packages
  become: yes
  become_user: "{{user}}"
```
## fails

```
- name: Install npm packages
  npm:
    name: "{{ item }}"
    global: yes
    state: latest
  with_items: node.packages
  environment:
    PATH: "{{ ansible_env.PATH }}:~/.local/bin"
  become: yes
  become_user: "{{user}}"
```
