### ISSUE TITLE
Stopping ec2 instances by tags is not working

### ISSUE THREAD

**Issue by agrgic** [ansible/ansible-modules-extras#1179]
As stated in the docs:

instance_tags
a hash/dictionary of tags to add to the new instance or for starting/stopping instance by tag; '{"key":"value"}' and '{"key":"value","key":"value"}'

You can't stop instances by just providing (a) tag(s), using: 

``` yaml

---
- name: start instances that don't need to be on the whole day (eu-west-1)
  hosts: localhost
  connection: local
  gather_facts: no
  vars:
    instance_tags:
      sandbox: 'yes'
  tasks:
    - name: start instances that don't need to be on the whole day (eu-west-1)
      local_action:
        module: ec2
        region: eu-west-1
        instance_tags: '{{ instance_tags }}'
        state: running
        wait: True
```

As my yml gives the following error: 

failed: [localhost -> 127.0.0.1] => {"failed": true}
msg: running list needs to be a list of instances to run: None

FATAL: all hosts have already failed -- aborting

**Comment by robynbergeron** [comment]
Hi @agrgic -- is this for the ec2_tag module? If so, that is a core module and the issue needs to be filed here: https://github.com/ansible/ansible-modules-core/issues

When you do that -- or if this is for a different module that is in extras -- you might want to consider giving us the following additional information to help the module maintainer identify the issue: https://github.com/ansible/ansible/blob/devel/ISSUE_TEMPLATE.md

Thanks!

**Comment by agrgic** [comment]
hi @robynbergeron I have already filed it at the core-modules and they said to me that I need to file it here so I did. 

If you look at the documentation: http://docs.ansible.com/ansible/ec2_module.html, it says that if you want to stop by tag you have to do the following:

 Start stopped instances specified by tag

``` yaml
- local_action:
    module: ec2
    instance_tags:
        Name: ExtraPower
    state: running
```

If you look at my snippet I did it like that but it still does not work (it gives the error as supplied), I don't know what I could give you more in regards to information.
