### ISSUE TITLE
win_unzip exception on windows 2012 R2 core

### ISSUE THREAD

**Issue by xpicio** [ansible/ansible-modules-extras#1233]
##### ISSUE TYPE

Bug Report
##### COMPONENT NAME

win_unzip module
##### ANSIBLE VERSION

N/A
##### SUMMARY

Hello, on windows 2012 R2 core using the module win_unzip i have the following exception to decompress a zip file:

`NameSpace" with "1" argument(s): "Unspecified error (Exception from HRESULT: 0x80004005 (E_FAIL))`

here my playbook snippet:

```
- name: Unzip TeamCity Artifact
    win_unzip:
      src: 'C:\Windows\Temp\{{ artifact_name }}'
      dest: 'C:\Program Files\{{ build_name }}'
     rm: yes
```

At the moment i patched the script with the following solution, but it work only with .NET 4.5 or 4.6:

```
Add-Type -assembly  System.IO.Compression.FileSystem
[System.IO.Compression.ZipFile]::ExtractToDirectory($src, $dest);
```
