### ISSUE TITLE
dnf module doesn't install packages when 'state' is set to 'latest'

### ISSUE THREAD

**Issue by avtar** [ansible/ansible-modules-extras#1239]
##### Issue Type:
- Bug Report
##### Ansible Version:

ansible 1.9.4
  configured module search path = None
##### Ansible Configuration:

I'm using the default config.
##### Environment:

Fedora 22
##### Summary:

The `dnf` module doesn't install packages when `state` is set to `latest`. It only works when `state` is set to `present`.
##### Steps To Reproduce:

I'm using nginx as an example but any package will do. Ensure the package is not installed:

```
rpm -qa | grep nginx
```

Use the following playbook:

```

---
- hosts: localhost
  user: root

  tasks:
    - name: Install nginx
      dnf:
        name: nginx
        state: latest
```

Run the playbook:

```
sudo ansible-playbook install_nginx.yml 
```
##### Expected Results:

The `nginx` package should have been installed.
##### Actual Results:

The package is not installed:

```
[vagrant@ansible-test ~]$ rpm -qa | grep nginx
[vagrant@ansible-test ~]$
```

As mentioned above, when the `state` parameter is set to `present` then the package gets installed.
