### ISSUE TITLE
yum_repository module does not support additional settings provided by yum plugins

### ISSUE THREAD

**Issue by detiber** [ansible/ansible-modules-extras#1305]
One example off the top of my head is the yum-plugin-priorities module which allows for setting priorities on repos. The yumrepos module should support a way to provide arbitrary additional settings on a repo.

@jtyr I failed to notice your PR before it was merged to bring this up, but on https://github.com/ansible/ansible-modules-extras/pull/411 I proposed the following for supporting this:

> personally, I would add an new param called additional_attributes that takes a dict to allow for setting repo attributes for plugins.
> 
> I'd avoid disabling param checking just because it seems like it could create a confusing user experience.
> 
> An example showing what I'm thinking:
> 
> ```
> yum_repository: 
>   id: example
>   baseurl='http://example.com/repo/'
>   additional_attributes:
>     priority: 1
> ```

**Comment by robynbergeron** [comment]
[module: packaging/os/yum_repository.py]

**Comment by robynbergeron** [comment]
@detiber -- Thanks for submitting this feature idea.

@jtyr -- Pinging you to bring this feature request to your attention. Please note that you are under no particular obligation to add this feature.

We encourage all Ansible community members to submit pull requests to satisfy feature requests. Consult the module guidelines (http://docs.ansible.com/ansible/developing_modules.html) for more information.

**Comment by jtyr** [comment]
@detiber I'm very happy that you brought this feature up as I was thinking about it recently as well. The biggest advantage of this new feature would be that it would allow to override already defined params and also add new params without the need to modify the role where the module is used. For example, some people might need to use a proxy server when fetching packages and if the author of the role did not parametrize it, the user would need to modify the role.

I'm just not sure whether `additional_parameters` is right name for it as it's quite long. What about to name it just `params`?

Here is an example of how people could use it:

```
---

# This is the defaults/main.yaml file of the my_role

# Default set of custom params would be empty hash
my_role_epel_yumrepo_params: {}
```

```
---

# This is the tasks/main.yaml file of the my_role

- name: Add EPEL repo
  yumrepo:
    name: epel
    description: EPEL YUM repo
    baseurl: http://download.fedoraproject.org/pub/epel/$releasever/$basearch/
    # Here we prepare the task to accept the custom params
    params: "{{ my_role_epel_yumrepo_params }}"
```

The user could add the custom params to the module by defining the `my_role_epel_yumrepo_params` variable in the playbook or in an other role:

```
---

# This is the playbook using the my_role

- name: My play
  hosts: all
  vars:
    # Here we add the custom params
    my_role_epel_yumrepo_params:
      proxy: http://myproxy.com:8080
  roles:
    - my_role
```

I would like to implement this feature in the near future so please provide feedback on the above.
