### ISSUE TITLE
s3_lifecycle.py - overwrites previous rules

### ISSUE THREAD

**Issue by Constantin07** [ansible/ansible-modules-extras#1323]
##### Issue Type:

Bug
##### Ansible Version:

ansible-1.9.4-1.el7.noarch
##### Ansible Configuration:

Variable definition:

```
# Lifecycle rules for S3 bucket
backup_lifecycle_rules:
  - prefix: daily
    expiration_days: 7
    rule_name: "Delete older than 1 week"
  - prefix: weekly
    expiration_days: 31
    rule_name: "Delete older than 1 month"
  - prefix: monthly
    expiration_days: 365
    rule_name: "Delete older than 1 year"

```

Task:

```
- name: Create S3 Lifecicle polices
  s3_lifecycle:
    name: "{{ s3_bucket_name }}"
    prefix: "{{ s3_tower_bakups_dir }}/{{ item.prefix }}/"
    expiration_days: "{{ item.expiration_days }}"
    rule_id: "{{ item.rule_name}}"
    state: present
    status: enabled
  with_items: backup_lifecycle_rules
  tags: s3

```
##### Environment:

CentOS Linux release 7.1.1503 (Core)
##### Summary:

The last lifecycle rule overwrites the previous ones so cannot create multiple rules. 
##### Steps To Reproduce:

Try to create multiple rules in loop.

```
TASK: [s3 | Create S3 Lifecicle polices] **************************************
<127.0.0.1> REMOTE_MODULE s3_lifecycle rule_id='Delete older than 1 week' expiration_days=7 prefix=tower_backups/daily/ state=present name=sample-bucket status=enabled
changed: [127.0.0.1] => (item={'expiration_days': 7, 'rule_name': 'Delete older than 1 week', 'prefix': 'daily'}) => {"changed": true, "item": {"expiration_days": 7, "prefix": "daily", "rule_name": "Delete older than 1 week"}}
<127.0.0.1> REMOTE_MODULE s3_lifecycle rule_id='Delete older than 1 month' expiration_days=31 prefix=tower_backups/weekly/ state=present name=sample-bucket status=enabled
changed: [127.0.0.1] => (item={'expiration_days': 31, 'rule_name': 'Delete older than 1 month', 'prefix': 'weekly'}) => {"changed": true, "item": {"expiration_days": 31, "prefix": "weekly", "rule_name": "Delete older than 1 month"}}
<127.0.0.1> REMOTE_MODULE s3_lifecycle rule_id='Delete older than 1 year' expiration_days=365 prefix=tower_backups/monthly/ state=present name=sample-bucket status=enabled
changed: [127.0.0.1] => (item={'expiration_days': 365, 'rule_name': 'Delete older than 1 year', 'prefix': 'monthly'}) => {"changed": true, "item": {"expiration_days": 365, "prefix": "monthly", "rule_name": "Delete older than 1 year"}}

```
##### Expected Results:

Be able to create multiple rules in loop.
##### Actual Results:

Only one rule is created which appears to be the last one in the list.
