### ISSUE TITLE
gluster_volume parameter 'replicas' is being ignored

### ISSUE THREAD

**Issue by roryirvine** [ansible/ansible-modules-extras#1357]
Using Ansible 1.9.4, I'm having problems with the following task:

```
- name: Configure gluster volume
  gluster_volume:
    state: present
    name: "{{ gluster_volume_name }}"
    brick: "{{ gluster_brick_dir }}"
    replicas: 2
    cluster: "{{ web_servers }}"
    host: "{{ ansible_default_ipv4.address }}"
  run_once: true
```

Ansible logs this as:

```
ansible-<stdin>: Invoked with force=False name=sr16 replicas=2 quota=None stripes=None cluster=['10.6.3.106', '10.6.5.69'] state=present start_on_create=False directory=None host=10.6.3.106 brick=/srv/brick/brick0 rebalance=False options={} transport=tcp 
```

...but the gluster-cli log shows that the 'replica' parameter isn't being supplied correctly:

```
[2015-12-10 13:07:25.882366]  : volume add-brick sr16 10.6.5.69:/srv/brick/brick0 force : FAILED : Incorrect number of bricks supplied 1 with count 2
```

I can replicate that on the command line:

```
# gluster volume add-brick sr16 10.6.5.69:/srv/brick/brick0
volume add-brick: failed: Incorrect number of bricks supplied 1 with count 2
```

but if I add the 'replica 2' parameter on the command line, it works as expected:

```
# gluster volume add-brick sr16 replica 2 10.6.5.69:/srv/brick/brick0
volume add-brick: success
```

Could this be due to confusion between 'replicas' (the parameter name used in the gluster_volume docs) and 'replica' (which is what gluster actually requires)?
