### ISSUE TITLE
win_regedit: can't handle "(Default)" key value 

### ISSUE THREAD

**Issue by dreamcat4** [ansible/ansible-modules-extras#1404]
Hi, This error report is from Ansible v1.9.4.

I'm getting error returned on specific keys. The keys all seem to get created but the task fails. I suspect this may be because the key name is `(Default)` in all of them. All my other registry keys in same loop exit fine. So perhaps it's falling over unquoted brackets parens `()` when it encounters them.

Here is the error message repeated several times:

https://gist.github.com/dreamcat4/4903f3526f4e91286cab

Here is the input data that causes the error:

``` yaml

  - name: Settings>Devices>AutoPlay - Default Action - Removable drive
    descr: Switches off / Disables this feature
    subkey: SOFTWARE\Microsoft\Windows\CurrentVersion\Explorer\AutoplayHandlers\EventHandlersDefaultSelection\StorageOnArrival
    value: "(Default)"
    state: present
    datatype: string
    data: MSTakeNoAction

  - name: Settings>Devices>AutoPlay - Default Action - Removable drive
    descr: Switches off / Disables this feature
    subkey: SOFTWARE\Microsoft\Windows\CurrentVersion\Explorer\AutoplayHandlers\UserChosenExecuteHandlers\StorageOnArrival
    value: "(Default)"
    state: present
    datatype: string
    data: MSTakeNoAction

  - name: Settings>Devices>AutoPlay - Default Action - Memory card
    descr: Switches off / Disables this feature
    subkey: SOFTWARE\Microsoft\Windows\CurrentVersion\Explorer\AutoplayHandlers\EventHandlersDefaultSelection\CameraAlternate\ShowPicturesOnArrival
    value: "(Default)"
    state: present
    datatype: string
    data: MSTakeNoAction

  - name: Settings>Devices>AutoPlay - Default Action - Memory card
    descr: Switches off / Disables this feature
    subkey: SOFTWARE\Microsoft\Windows\CurrentVersion\Explorer\AutoplayHandlers\UserChosenExecuteHandlers\CameraAlternate\ShowPicturesOnArrival
    value: "(Default)"
    state: present
    datatype: string
    data: MSTakeNoAction

- name: hkey_users - set registry values for users
  win_regedit:
    key: Registry::\HKEY_USERS\{{ item[0].sid }}\{{ item[1].subkey }}
    state: "{{ item[1].state }}"
    value: "{{ item[1].value }}"
    data: "{{ item[1].data }}"
    datatype: "{{ item[1].datatype }}"
  with_nested:
    - win_users
    - "{{ hkey_users }}"
```
