### ISSUE TITLE
win_iis_webbinding: remove default binding

### ISSUE THREAD

**Issue by aensidhe** [ansible/ansible-modules-extras#1432]
##### ISSUE TYPE

Bug Report
##### COMPONENT NAME

win_iis_webbinding module
##### ANSIBLE VERSION

N/A
##### SUMMARY

When you create a website for the first time, it will receive default binding: `http:*:80`

I add some non-default bindings:

```
- name: add bindings
  win_iis_webbinding:
    name: "{{ http.name }}"
    state: present
    protocol: http
    port: 80
    host_header: "{{ item.name }}"
  with_items: "{{ evote_site_domains }}"
```

And after that I try to remove default binding:

```
- name: remove *:80 bindings
  win_iis_webbinding:
    name: "{{ http.name }}"
    state: absent
    protocol: http
    port: 80
    host_header: ""
```

But this code removes all bindings from website.
I do not know this is a bug or I do something wrong.
