### ISSUE TITLE
win_acl: set permissions to apppool identities don't work

### ISSUE THREAD

**Issue by aensidhe** [ansible/ansible-modules-extras#1433]
##### ISSUE TYPE

Bug Report
##### COMPONENT NAME

win_acl module
##### ANSIBLE VERSION

N/A
##### SUMMARY

I have this playbook:

```
- name: create app domain
  win_iis_webapppool:
    name: "{{ http.appdomain }}"
    state: started

- name: create data directory
  win_file:
    path: "{{ http.path }}"
    state: directory

- name: iis should have read access to path
  win_acl:
    path: "{{ http.path }}"
    user: "IIS APPPOOL\\{{ http.appdomain }}"
    rights: 'Read'
    type: 'allow'
    state: 'present'
    inherit: 'ContainerInherit, ObjectInherit'
    propagation: 'None'
```

When I run it against Windows Server 2012 R2 I'm getting error:

```
TASK [windows/evote-site : iis should have read access to path] ****************
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: +         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
fatal: [hostname]: FAILED! => {"changed": false, "failed": true, "msg": "Exception calling \"FindOne\" with \"0\" argument(s): \"The specified domain either does not exist or could not be contacted.\r\n\""}

PLAY RECAP *********************************************************************
hostname   : ok=8    changed=0    unreachable=0    failed=1
```

But if I call `icacls` all works perfect:

```
- name: grant read access to iis to application
  raw: 'icacls --% "{{ http.path }}" /grant "IIS APPPOOL\{{ http.appdomain }}":(OI)(CI)(RX)'
```
