### ISSUE TITLE
Bug report: ufw: interface option causes an error (1.9.4)

### ISSUE THREAD

**Issue by malakai97** [ansible/ansible-modules-extras#1491]
Specifying the interface option seems to get translated into an "on" field, which leads to this error:

```
failed: [myserver] => {"failed": true}
msg: ERROR: Invalid token 'on'


FATAL: all hosts have already failed -- aborting
```

The task in question is simply:

```
- name: allow some interface
  ufw:
    interface: lo
    rule: allow
```

Ansible version: 1.9.4
Config: stock
OS: Ubuntu 14.04 LTS Desktop to Ubuntu 14.04 LTS Server, fresh installs.

**Comment by bearrito** [comment]
Try 

```
- name: allow some interface
  ufw:
    interface: lo
    rule: allow
    direction: in
```
