### ISSUE TITLE
win_firewall_rule exception when adding rule

### ISSUE THREAD

**Issue by tcr-ableton** [ansible/ansible-modules-extras#1512]
##### Issue Type:

Bug Report
##### Ansible Version:

Ansible 2.0.0.2
##### Ansible Configuration:

Vanilla
##### Environment:

Running ansible from OSX, managing a Windows 10 host. 
##### Summary:

The `win_firewall_rule` module does not work in my case. Using example step from documentation as well custom usage led to the same error: `The property 'failed' cannot be found on this object. Verify that the property exists.`
##### Steps To Reproduce:

Here is an example of `win_firewall_rule` usage that fails

``` yaml
- name: Open jenkins slave ports in firewall
  action: win_firewall_rule
    args:
      name: jenkinsslave135
      enabled: yes
      localport: 135
      action: allow
      protocol: TCP
      direction: In
```
##### Expected Results:

It is expected that the windows firewall opens port 135 for incoming TCP connexions. But the step fails. 
##### Actual Results:

The step fails with the following error, letting the firewall unconfigured:

```
An exception occurred during task execution. The full traceback is:
At C:\Users\cibot\AppData\Local\Temp\ansible-tmp-1453124307.49-253776948010647\win_firewall_rule.ps1:503 char:5
+ if ($capture.failed -eq $true) {
+     ~~~~~~~~~~~~~~~~~~~~~~~~~
fatal: [X.X.X.X]: FAILED! => {"changed": false, "failed": true, "msg": "The property 'failed' cannot be found on this object. Verify that the property exists."}
```

And here is the `win_firewall_rule.ps1` file generated on the host machine mentioned in the error: https://gist.github.com/tcr-ableton/63509ca3b27423b6f9fe

Cheers,
Theo
