### ISSUE TITLE
Slack webhook notification does not work with ansible 1.8

### ISSUE THREAD

**Issue by leevs** [ansible/ansible-modules-extras#157]
##### Issue Type:

Bug Report
##### Ansible Version:

Broken : ansible 1.8.1              ansible-1.8.1-1.el6.noarch
Working : ansible 1.7.2            ansible-1.7.2-2.el6.noarch
##### Environment:

CentOS release 6.6 (Final)
##### Summary:

Slack webhook notification does not work anymore with the update of ansible 1.8.1.
Tasks says there is no problem but nothing is getting shown in slack.
##### Steps To Reproduce:

```
- name: Send notification message via Slack all options
  local_action:
    module: slack
    domain: xxx.slack.com
    token: xxx
    msg: "Branch {{ build }}, is now getting build on jenkins with these options: {{params}} optimize:{{optimize}} bootstrap:{{bootstrap}} and will stay up for {{timetolive}} days. The process can be followed here : xxx"
    channel: "#ci"
    link_names: 1
```
##### Expected Results:

A post to the slack channel: 
"Branch test, is now getting build on jenkins with these options: test optimize:test bootstrap:test and will stay up for test days. The process can be followed here : xxx"
##### Actual Results:

Nothing is shown.

1.7.2 -vvv result (working)

TASK: [Send notification message via Slack all options] ***********************
<127.0.0.1> REMOTE_MODULE slack channel='#ci' token= domain=xxx.slack.com msg='Branch test, is now getting build on jenkins with these options: test optimize:test bootstrap:test and will stay up for test days. The process can be followed here : xxxx'
<127.0.0.1> EXEC ['/bin/sh', '-c', 'mkdir -p $HOME/.ansible/tmp/ansible-tmp-1418310211.18-188493459373960 && chmod a+rx $HOME/.ansible/tmp/ansible-tmp-1418310211.18-188493459373960 && echo $HOME/.ansible/tmp/ansible-tmp-1418310211.18-188493459373960']
<127.0.0.1> PUT /tmp/tmplhxI3I TO /home/ansible/.ansible/tmp/ansible-tmp-1418310211.18-188493459373960/slack
<127.0.0.1> EXEC /bin/sh -c 'sudo -k && sudo -H -S -p "[sudo via ansible, key=uhkhypxfjylljezednmskwqgaokaogyq] password: " -u root /bin/sh -c '"'"'echo SUDO-SUCCESS-uhkhypxfjylljezednmskwqgaokaogyq; LANG=C LC_CTYPE=C /usr/bin/python /home/ansible/.ansible/tmp/ansible-tmp-1418310211.18-188493459373960/slack; rm -rf /home/ansible/.ansible/tmp/ansible-tmp-1418310211.18-188493459373960/ >/dev/null 2>&1'"'"''
ok: [localhost -> 127.0.0.1] => {"changed": false, "msg": "OK"}

1.8.1 -vvv result (broken)

TASK: [Send notification message via Slack all options] ***********************
<127.0.0.1> REMOTE_MODULE slack channel='#ci' token= domain=xxx.slack.com msg='Branch test, is now getting build on jenkins with these options: test optimize:test bootstrap:test and will stay up for test days. The process can be followed here : xxx'
<127.0.0.1> EXEC ['/bin/sh', '-c', 'mkdir -p $HOME/.ansible/tmp/ansible-tmp-1418310038.98-146454958098479 && chmod a+rx $HOME/.ansible/tmp/ansible-tmp-1418310038.98-146454958098479 && echo $HOME/.ansible/tmp/ansible-tmp-1418310038.98-146454958098479']
<127.0.0.1> PUT /tmp/tmpRiLiit TO /home/ansible/.ansible/tmp/ansible-tmp-1418310038.98-146454958098479/slack
<127.0.0.1> EXEC /bin/sh -c 'sudo -k && sudo -H -S -p "[sudo via ansible, key=ciahqceudvthumdpkvppcfzugjjtmefp] password: " -u root /bin/sh -c '"'"'echo SUDO-SUCCESS-ciahqceudvthumdpkvppcfzugjjtmefp; LANG=C LC_CTYPE=C /usr/bin/python /home/ansible/.ansible/tmp/ansible-tmp-1418310038.98-146454958098479/slack; rm -rf /home/ansible/.ansible/tmp/ansible-tmp-1418310038.98-146454958098479/ >/dev/null 2>&1'"'"''
ok: [localhost -> 127.0.0.1] => {"changed": false, "msg": "OK"}

**Comment by avelis** [comment]
I might be out of my league here, but have you considered upgrading Ansible to `v1.8.2`? I don't seem to be having any Slack notifications issues with that version of Ansible.

**Comment by AndreBremer** [comment]
There is a workaround.

The slack module recently changed the slack service endpoint. As a result, the token itself is no longer enough to post messages. It also requires two preceding - presumably secret - path components. The final URL is of the form https://hooks.slack.com/services/XXXX/YYYY/TOKEN

You can look up the required path components in your existing configured webhook slack integration and then pass it as the 'token' value to the slack module. The slack module will simply concatenate it and create the correct URL again:

```
- name: Send notification message via Slack all options
  local_action:
    module: slack
    domain: xxx.slack.com
    token: XXXX/YYYY/TOKEN 
    msg: "Branch {{ build }}, is now getting build on jenkins with these options: {{params}} optimize:{{optimize}} bootstrap:{{bootstrap}} and will stay up for {{timetolive}} days. The process can be followed here : xxx"
    channel: "#ci"
    link_names: 1
```

The old domain-style URLs are still working but appear to be deprecated. 

To maintain backwards compatibility the module should make use of the 'domain' endpoint if it's supplied.
