### ISSUE TITLE
sns_topics tasks fails with "TypeError: 'NoneType' object is not iterable"

### ISSUE THREAD

**Issue by gb-klein** [ansible/ansible-modules-extras#1573]
##### Issue Type:

Bug Report
##### Ansible Version:

ansible 2.0.0.2
##### Ansible Configuration:

only changed 'host_key_checking = False' in /etc/ansible/ansible.cfg
##### Environment:

DISTRIB_ID=LinuxMint
DISTRIB_RELEASE=17.1
DISTRIB_CODENAME=rebecca
DISTRIB_DESCRIPTION="Linux Mint 17.1 Rebecca"
NAME="Ubuntu"
VERSION="14.04.3 LTS, Trusty Tahr"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 14.04.3 LTS"
VERSION_ID="14.04"
##### Summary:

Simple playbook with sns_topic task fails with message: "TypeError: 'NoneType' object is not iterable"
##### Steps To Reproduce:

define playbook setup-sns.yml with content:

```
- name: Setup required SNS topics and subscriptions for our lambda functions
  hosts: localhost
  connection: local
  tasks:  
    - name: setup simpleSnsTopic
      sns_topic:
        name: "simpleSnsTopic"
        state: present
        region: eu-central-1
```

execute with _ansible-playbook -vvv setup-sns.yml_

if i however append a subscriptions defintion

```
subscriptions:
          - endpoint: "my_email_address@example.com"
            protocol: "email"
```

the playbook succeeds. But that is not a workaround for us as we have sns topics without subscriptions
##### Expected Results:

simpleSnsTopic should be created without any error and tasks should not fail
##### Actual Results:

simpleSnsTopic is created and task fails with error message:

> An exception occurred during task execution. The full traceback is:
> Traceback (most recent call last):
>   File "/home/user/.ansible/tmp/ansible-tmp-1454082395.19-227895112884618/sns_topic", line 2421, in <module>
>     main()
>   File "/home/user/.ansible/tmp/ansible-tmp-1454082395.19-227895112884618/sns_topic", line 234, in main
>     subscriptions]
> TypeError: 'NoneType' object is not iterable
> fatal: [localhost]: FAILED! => {"changed": false, "failed": true, "invocation": {"module_name": "sns_topic"}, "parsed": false}

**Comment by wimnat** [comment]
@f24-gklein I've submitted a PR above to address this issue. Let me know if it solves your problem.

**Comment by joelthompson** [comment]
Hey @f24-gklein -- sorry about this bug! :(

Until @wimnat's PR gets merged and then released, you should be able to work around it by explicitly setting subscriptions to an empty list, e.g.:

``` yaml
- name: Setup required SNS topics and subscriptions for our lambda functions
  hosts: localhost
  connection: local
  tasks:  
    - name: setup simpleSnsTopic
      sns_topic:
        name: "simpleSnsTopic"
        state: present
        region: eu-central-1
        subscriptions: []
```
