### ISSUE TITLE
Using blockinfile with with_items loop

### ISSUE THREAD

**Issue by augustoribeiro** [ansible/ansible-modules-extras#1592]
Hi,

I am trying to use the **blockinfile** module with a **with_items** loop but it seems like the last item always overwrite the ones before.

Take for example:

```
- hosts: webserver
  tasks:
  - name: touch /tmp/text.txt
    file: path=/tmp/text.txt state=touch
  - name: block in file with items
    blockinfile:
        dest: /tmp/text.txt
        insertafter: BOF
        state: present
        block: |
          {{item}}
    with_items:
      - 1
      - 2
      - 3
```

Examining the content of /tmp/text.txt shows:

```
# BEGIN ANSIBLE MANAGED BLOCK
3
# END ANSIBLE MANAGED BLOCK
```

Is this the expected behaviour?

Best regards,
Augusto

edit: added @yaegashi for visibility

**Comment by yaegashi** [comment]
Yes, that's expected - blockinfile is just repeatedly called with each item.

You can specify alternative markers using `{{item}}` like this:

```
  - name: block in file with items
    blockinfile:
      dest: /tmp/text.txt
      insertafter: BOF
      state: present
      block: |
        {{item}}
      marker: "# {mark} ANSIBLE MANAGED BLOCK {{item}}"
    with_items:
      - 1
      - 2
      - 3
```

Output in /tmp/text.txt:

```
# BEGIN ANSIBLE MANAGED BLOCK 1
1
# END ANSIBLE MANAGED BLOCK 1
# BEGIN ANSIBLE MANAGED BLOCK 2
2
# END ANSIBLE MANAGED BLOCK 2
# BEGIN ANSIBLE MANAGED BLOCK 3
3
# END ANSIBLE MANAGED BLOCK 3
```
