### ISSUE TITLE
ec2_asg module issue when trying to add new elb name to the load_balancers list

### ISSUE THREAD

**Issue by ProgressiveAstronaut** [ansible/ansible-modules-extras#1594]
I'm trying to add a new ELB to the load_balancers list. The playbook ran successfully  but the new list isn't applied to the AS group.

```
- hosts: localhost
  connection: local
  gather_facts: no
  tasks:
  - name: Update Auto-Scaling Group Settings
    ec2_asg:
       name: as_group_name
       load_balancers: [ 'elb-1', 'elb-2', 'elb-3', 'elb-4', 'new-elb-to-add']
       region: {{ region }}
```
