### ISSUE TITLE
vca_vapp ignores service_type option

### ISSUE THREAD

**Issue by dan-petty** [ansible/ansible-modules-extras#1602]
The 'service_type' option ( https://github.com/ansible/ansible-modules-extras/blob/devel/cloud/vmware/vca_vapp.py#L122 ):

```
    service_type:
      description:
        - The type of service we are authenticating against
      required: false
      default: vca
      choices: [ "vca", "vchs", "vcd" ]

```

Seems to be completely ignored by the code.
