### ISSUE TITLE
Maven module should be able to resolve and fetch dependencies as well

### ISSUE THREAD

**Issue by lygaret** [ansible/ansible-modules-extras#1615]
##### Summary:

It would be incredibly useful if the `maven_artifact` module could fetch the POM, and resolve listed dependencies, as well as simply download the given artifact. I imagine it working by passing something like `dependencies=true` on the module line.

Thanks for taking the time :smiley_cat: 
##### Steps To Reproduce:

[Stanford CoreNLP](http://stanfordnlp.github.io/CoreNLP/corenlp-server.html)'s new server is a good example of the issue I'm having. This is my step for downloading the CoreNLP server:

```
- name: Download CoreNLP & Dependencies
  maven_artifact: group_id={{ item.value.group_id }} artifact_id={{ item.value.artifact_id }} classifier={{ item.value.classifier|default(omit) }} dest=/home/scout/corenlp/{{ item.key }}-latest.jar
  with_dict:
    corenlp:
      group_id: edu.stanford.nlp
      artifact_id: stanford-corenlp
    corenlp_models:
      group_id: edu.stanford.nlp
      artifact_id: stanford-corenlp
      classifier: models
    xom:
      group_id: com.io7m.xom
      artifact_id: xom
    joda_time:
      group_id: joda-time
      artifact_id: joda-time
    jollyday:
      group_id: de.jollyday
      artifact_id: jollyday
    javax_json_api:
      group_id: javax.json
      artifact_id: javax.json-api
    ejml:
      group_id: com.googlecode.efficient-java-matrix-library
      artifact_id: ejml
    slf4j_api:
      group_id: org.slf4j
      artifact_id: slf4j-api
```

If I could ask the `maven_artifact` module to please include dependencies, it would look something more akin to this:

```
- name: Download CoreNLP & Dependencies
  maven_artifact: group_id=edu.stanford.nlp artifact_id=stanford-corenlp classifier={{item.classifier|default(omit)}} dependencies=true dest=/home/scout/corenlp
  with_items:
    - { }
    - { classifier: models }
```

Pros:
- Much simpler and more obvious role.
- I'm not responsible for keeping my playbook up to date with the dependencies of whatever the `-latest` version is upstream.
- I'm no longer overriding versions with `-latest` for the dependencies, but rather getting the actually versioned dependencies defined by whatever `-latest` of my main artifact asks for.

Cons
- Lost the ability to name output files explicitly
- Transitive dependencies? Etc. etc.
