### ISSUE TITLE
blockinfile module overwrites previous changes

### ISSUE THREAD

**Issue by vikas027** [ansible/ansible-modules-extras#1635]
##### Environment

OS X : 10.11.2
Ansible : 2.0.0.2
##### Problem

[blockinfile](http://docs.ansible.com/ansible/blockinfile_module.html) module does not updates the file but overwrites previous task changes on the second run

Example

``` yaml

---
- hosts: 127.0.0.1
  tasks:
    - name: first block
      blockinfile:
        dest: /Users/vikas027/test_file
        insertafter: EOF
        block: |
          line1
          line2
          line3

    - name: second block
      blockinfile:
        dest: /Users/vikas027/test_file
        insertafter: EOF
        block: |
          line4
          line5
```

``` bash
$ cat /Users/vikas027/test_file
# BEGIN ANSIBLE MANAGED BLOCK
line4
line5
# END ANSIBLE MANAGED BLOCK
```
##### Expected Results (something similar)

``` bash
$ cat /Users/vikas027/test_file
# BEGIN ANSIBLE MANAGED BLOCK
line1
line2
line3
line4
line5
# END ANSIBLE MANAGED BLOCK
```
##### Used Case

I don't want to have this is one block as I have two roles which may or may not add a block in the same file depending on certain conditions.
