### ISSUE TITLE
Unsupported parameter for module

### ISSUE THREAD

**Issue by alexbowers** [ansible/ansible-modules-extras#1652]
##### ISSUE TYPE

Bug Report
##### COMPONENT NAME

blockinfile module
##### ANSIBLE VERSION
2.0

##### SUMMARY

On Ansible 2.0 I receive an error with the blockinfile module, where it says

``` bash
fatal: [web]: FAILED! => {"changed": false, "failed": true, "msg": "unsupported parameter for module: state"}
```

My code example is as follows: 

``` yaml

---
- name: Enable CPU monitoring
  become: yes
  blockinfile:
    state: "{{ collectd.monitors.cpu | ternary('present', 'absent') }}"
    marker: "# {mark} COLLECTD CPU MANAGED BLOCK"
    dest: /etc/collectd/collectd.conf
    block: |
      <Plugin cpu>
        ReportByCpu true
        ReportByState true
        ValuesPercentage true
      </Plugin>
```

On ansible 1.9, using the standard module, this worked perfectly fine as expected (https://github.com/yaegashi/ansible-role-blockinfile)

**Comment by alexbowers** [comment]
When i debug the ternary, I do get 'present' returned, so the value is correct.

**Comment by insanity54** [comment]
I'm getting something similar. Not sure if it's related but I'll post just in case. Problem exists with ansible 2.0.0.2, but was fine with 1.9. 

`fatal: [foxxy]: FAILED! => {"changed": false, "failed": true, "msg": "unsupported parameter for module: 'state"}`

Code example from [this](https://github.com/dochang/ansible-role-docker) playbook:

```
- name: install docker-py
  pip: >-
    'name=docker-py'
    'state=present'
    'executable=pip2'
    {% if docker_dockerpy_version is defined and docker_dockerpy_version %}
    'version={{ docker_dockerpy_version }}'
    {% endif %}
```

**Comment by bcoca** [comment]
@insanity54 that is an invalid entry (1.9 ignored many of these errors), you want:

```
pip: >
  name=docker-py
  state=present
  executable=pip2
  version={{docker_dockerpy_version|default(omit, boolean=True)}}
```

**Comment by shopblocks** [comment]
@bcoca Is there anything wrong with my entry? (alexbowers)

**Comment by bcoca** [comment]
nothing obvious

**Comment by jhawk28** [comment]
blockinfile also does not support "register" or "notify"
for example:

```
- blockinfile:
  dest: /etc/grub.d/10_linux
  block: |
    cat << EOF
    set superusers="root"
    password_pbkdf2 root grub.pbkdf2.sha512.10000.biglongstring
    EOF
  register: grubpwd
- command: grub2-mkconfig --output=/boot/grub2/grub.cfg
  when grubpwd.changed
```

**Comment by thomseddon** [comment]
For anyone else that ends up here, in my case this error was caused by having versions of ansible installed via both apt and pip, resolution was to remove one!

Credit: https://groups.google.com/d/msg/ansible-project/hMkpsV2pp9s/h3Fz6qt-JAAJ

**Comment by ansibot** [comment]
@yaegashi, ping. This issue is still waiting on your response.
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibot** [comment]
@yaegashi, ping. This issue is still waiting on your response.
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by trishnaguha** [comment]
I got the similar issue.

**Comment by ansibot** [comment]
@yaegashi, ping. This issue is still waiting on your response.
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibot** [comment]
@yaegashi, ping. This issue is still waiting on your response.
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by alexbowers** [comment]
Is it time to mark this as abandoned?

**Comment by yaegashi** [comment]
@alexbowers, I cannot reproduce your problem with Ansible 2.0.0.2-2 nor 2.1.2.0-1ppa~xenial on Ubuntu 16.04.  Could you provide a test case as a single playbook if the problem persists?  My own test was like the following:

``` yaml
---
- hosts: localhost
  gather_facts: no
  vars:
    v1: true
    v2: false
  tasks:
    - blockinfile:
        state: "{{ v1 | ternary('present', 'absent') }}"
        marker: "# {mark} v1"
        dest: output.txt
        block:
          v1
    - blockinfile:
        state: "{{ v2 | ternary('present', 'absent') }}"
        marker: "# {mark} v2"
        dest: output.txt
        block:
          v2
```

Sample session:

```
$ touch output.txt
$ ansible-playbook playbook.yml
```

Result in output.txt (Ansible 2.0.0.2-2 on Ubuntu 16.04)

```
# BEGIN v1
v1
# END v1
```
