### ISSUE TITLE
homebrew_cask should accept an appdir parameter

### ISSUE THREAD

**Issue by siancu** [ansible/ansible-modules-extras#167]
##### Issue Type:

Feature Idea.
##### Ansible Version:

ansible --version
ansible 1.8.2
  configured module search path = None
##### Environment:

I'm running Ansible on OSX 10.10.1 and I'm managing the same computer (local connection).
##### Summary:

By default, cask symlinks the apps to ~/Applications instead of /Applications.

The brew cask command accepts a "--appdir" parameter but with homebrew_cask it is impossible to set it. So I would like to request an improvement to the module to add this parameter.

At the moment I've patched locally the source of the module by hardcoding it to /Applications like this:

```
    cmd = [opt
           for opt in (self.brew_path, 'cask', 'install', '--appdir=/Applications', self.current_cask)
           if opt]
```

(lines 398-400 in homebrew_cask.py). It seems to work so far. But this is not the right solution, obviously.
##### Steps To Reproduce:

For example, the homebrew_cask task could look like this:

```
- name: Install Homebrew cask apps
  homebrew_cask: "name=spotify state=present appdir=/Applications"
```

**Comment by elnappo** [comment]
I use the environment variable `HOMEBREW_CASK_OPTS`. Hope this is good enough for you, I'm fine with this ;)

``` yaml
- name: Install Homebrew cask apps
  homebrew_cask: name=spotify state=present
  environment:
    HOMEBREW_CASK_OPTS: --appdir=/Applications
```
