### ISSUE TITLE
Fetch module for windows client does not fetch a file

### ISSUE THREAD

**Issue by sparkvilla** [ansible/ansible-modules-extras#1696]
##### Issue Type:
- Bug Report
##### Plugin Name:

Fetch module for windows
##### Ansible Version:

```
ansible 2.0.0.2
```
##### Ansible Configuration:

I am using ansible.cfg in my folder where I run the playbook.
[defaults]
hostfile=./hosts
log_path = ./ansible.log
##### Environment:

I am running Ansible 2.0.0.2 on a Ubuntu desktop 15.10 OS, managing a virtual machine 
with Windows 10 OS 
##### Summary:

I am using the fetch module as part of the playbook to fetch a file from a windows client. The playbook runs without errors but the file is not fetched.
##### Steps To Reproduce:

For bugs, please show exactly how to reproduce the problem. For new
features, show how the feature would be used.

```
- name: Test win_copy module on windows client
  hosts: win1
  tasks:
    - name: Write PS output command to a file
      raw: Get-Service > C:/info.txt
    - name: Fetch the file          #here is the problem
       fetch: src=C:/info.txt dest=/home/diego/work/ansible_win/ex1 flat=yes

```
##### Expected Results:

To have info.txt file on my localmachine, i.e. in /home/diego/work/ansible_win/ex1 
##### Actual Results:

There is no the info.txt file on my local machine

```
If (Test-Path -PathType Leaf "C:\info.txt")
{
$sp = new-object -TypeName   System.Security.Cryptography.SHA1CryptoServiceProvider;
$fp = [System.IO.File]::Open("C:\info.txt[System.IO.Filemode]::Open, [System.IO.FileAccess]::Read);
[System.BitConverter]::ToString($sp.ComputeHash($fp)).Replace("-", "").ToLower();
$fp.Dispose();
}
ElseIf (Test-Path -PathType Container "C:\info.txt")
{
Write-Host "3";
}
Else 
{
Write-Host "1";
} 
<192.168.122.123> FETCH "C:\info.txt" TO "/home/diego/work/ansible_win/ex1"
```

**Comment by jhawkesworth** [comment]
Using Ansible 2.0.1 rc 2 on Lubuntu 14.04 targetting 1 x Windows Server 2012 R2 host, this worked for me using the following playbook. 

Not sure why this isn't working for you.

I think perhaps your yaml is not correctly formed - I suggest using yamllint.com or a yaml-aware editor (I use notepad++ on windows) or possibly ex1 is not a directory in your playbook?  
Are you targeting more than 1 windows host with this playbook?  If so then the file could be being overwritten as you are attempting to store results from all hosts in the same file name.

``` yaml
---

- hosts: windows
  tasks:
    - name: get service
      raw: Get-Service > C:/info.txt

    - name: Fetch the file
      fetch: src=C:/info.txt dest=/tmp/ flat=yes
```

**Comment by sparkvilla** [comment]
It is funny, I tried to run the playbook including an end slash for ex1 directory, i.e. `/home/diego/work/ansible_win/ex1/` and the first time It actually worked, i.e. I could read the info.txt file on my local machine. Then I run the playbook a second time and I was able to retrieve the info.txt file but when I tried to open it on my local machine it was a binary file. I tried several times (also changing the name of the file) and I always get a binary file. I don't know what is wrong now..

To answer your questions. I am targeting a single windows host and I am using either vim or gedit as text editor. Thanks for your help.

**Comment by jhawkesworth** [comment]
dest is going to need to be a directory every time, that's what fetch requires.

When you say 'get a binary file' I am not sure what you mean exactly.

Files created on later windows versions often start with a Byte Order Mark, and that is what is happening here.  You can see this if you examine the first line of the file with od, like this (its the feff bit):

``` bash
$ head -1 /tmp/info.txt  | od -cx
0000000 377 376  \r  \0  \n
           feff    000d    000a
```

If you need to, you can remove the Byte Order Mark so you can continue processing as text.

However, depending on what you are trying to achieve, you might be able to avoid this by using 
register in your playbook to capture the result from Get-Service and then process the output within ansible.  Playbook would look something like this:

``` yaml
- hosts: windows
  tasks:
    - name: get service
      raw: Get-Service
      register: services_result

    - name: examine services result
      debug:
         var: services_result
```

Hope this helps,

Jon
