### ISSUE TITLE
win_get_url module appears to require parameter listed as optional in docs ('creates')

### ISSUE THREAD

**Issue by danielcarl** [ansible/ansible-modules-extras#1718]
##### Issue Type:
- Bug Report
##### Plugin Name:

win_unzip
##### Ansible Version:

```
ansible 2.0.0
```
##### Ansible Configuration:

n/a
##### Environment:

Running from OSX El Capitan (10.11.3 (15D21)), managing a Windows 7 Ultimate SP1 VM (probably n/a to issue at hand)
##### Summary:

'creates' parameter is listed as optional in documentation, but script is throwing error when the parameter is excluded.
##### Steps To Reproduce:

Created a playbook with the following play which extracts a zip file which had previously been successfully fetched using win_get_url:

```
- name: Extract root contents on endpoint
  win_unzip:
    src: 'C:\temp\root.zip'
    dest: 'C:\stuff'
    recurse: no
    rm: true
```
##### Expected Results:

Expected the contents of the zip file to be extracted to C:\stuff directory (C:\stuff directory exists on the target system).
##### Actual Results:

The following error is displayed (when running with the -vvv param).

```
An exception occurred during task execution. The full traceback is:
At C:\Users\Administrator\AppData\Local\Temp\ansible-tmp-1456264089.65-21881646871196\win_unzip.ps1:255 char:5
+ If ($params.creates) {
+     ~~~~~~~~~~~~~~~
fatal: [172.17.12.37]: FAILED! => {"changed": false, "failed": true, "invocation": {"module_args": {"dest": "C:\\stuff", "recurse": false, "rm": true, "src": "C:\\temp\\root.zip"}, "module_name": "win_unzip"}, "msg": "Property 'creates' cannot be found on this object. Make sure that it exists."}
```

Modifying the play as below fixes the issue:

```
- name: Extract root contents on endpoint
  win_unzip:
    src: 'C:\temp\root.zip'
    dest: 'C:\stuff'
    recurse: no
    rm: true
    creates: 'C:\stuff'
```
