### ISSUE TITLE
lvg: undocumented support of physical volume creation

### ISSUE THREAD

**Issue by elouanKeryell-Even** [ansible/ansible-modules-extras#1720]
##### Issue Type:

Documentation Report
##### Plugin Name:

lvg
##### Ansible Version:

```
# ansible --version
ansible 1.9.4
  configured module search path = None
```
##### Summary:

lvg module seems to take care of physical volume creation, on top of volume group creation. However, it doesn't appear to be documented.

I noticed I could just use

```
- name: Create LVM volume group
  lvg:
    pvs: /dev/vdc
    state: present
    vg: direct-lvm
```

instead of:

```
- name: Create LVM physical volume
  command: pvcreate -y /dev/vdc

- name: Create LVM volume group
  lvg:
    pvs: /dev/vdc
    state: present
    vg: direct-lvm
```

which isn't idempotent since executing pvcreate a second time will fail.
