### ISSUE TITLE
'vapp has no vm named ...' while trying to create VM and few smaller bugs.

### ISSUE THREAD

**Issue by warej** [ansible/ansible-modules-extras#1741]
##### Issue Type:
- Bug Report
- Needs Info
  ##### Component Name:
  vca_vapp module
##### Environment:
- XUbuntu 14.04 LTS
- Python 2.7.9
- $ pip list
  - ndg-httpsclient (0.4.0)
  - pyOpenSSL (0.15.1)
  - pyvcloud (15rc2)
  - vca-cli (15)
  - ...
##### Summary:

Overall picture is that I'd like to use **Ansible** for creating and configuring VMs in **vCloud Director** (standalone) environment. Unfortunately I've encountered several problems with ansible's vmware module. Some of them were easy to do a quickfix but final result wasn't.
Now I'm confused if my configuration is wrong (despite hours with docs & code samples) or something is broken in ansible's vmware module.
##### Steps To Reproduce:

**Small bugs fixed:**

_ansible/module_utils/vca.py_:103: Probably syntax error:

```
    vms = [vm for vm in vapp._get_vms() if vm.name == vm_name]  ### edited
    vms = [vm for vm in children.get_Vm() if vm.name == vm_name]  ## ORIG
```

_ansible/module_utils/vca.py_:122: 'verify_certs' parameter isn't accepted by ansible and 'org' wasn't passed to VCA (not sure if it was blocking issue)

```
    verify = self.params.get('verify_certs') ### can't use this parameter in playbook

    ### edited by warear ###
    vca = VCA(host=host, username=username,
               service_type=SERVICE_MAP[service_type],
               version=version, verify=False)
    vca.org = self.params['org'] ### I'm not sure if this is neccessary but it's working and logically correct.
    return vca
    # ORIG:
    #return VCA(host=host, username=username,
    #           service_type=SERVICE_MAP[service_type],
    #           version=version, verify=verify)
```

_ansible/module_utils/vca.py_:139: 'org' wasn't passed to login function which caused str + None error in _pyvcloud/vcloudsession.py_:65

```
    if not self.vca.login(password=password, org=self.params['org']): ### edited
    if not self.vca.login(password=password): ### ORIG
```

_pyvcloud/vcloudair.py_:132: I've copied service type detection from _pyvcloud==14_, cause in _pyvcloud==15rc2_ it doesn't work well with VCD (issue already submitted):

```
    if response.status_code == requests.codes.unauthorized:  ### edited
    if response.status_code != 404:  ### ORIG
```

**My playbook** (based on [vca code sample](https://github.com/vmware/vca-codesamples/blob/master/ansibleworkshopVMworld2015/lessons/lesson2/library/vca_vapp.py#L214)):

```
    - hosts: localhost
      connection: local
      tasks:
       - vca_vapp:
          operation: poweron
          org: "my-org"
          username: "warear"
          password: "XXX"
          host: "https://my-vcloud.example.com"
          api_version: "5.5"
          service_type: vcd
          vdc_name: "myvdc"
          vm_name: testAutoDeploy
          vm_cpus: 1
          vapp_name: "my_vapp"
          state: present
          instance_id: "00000000-0000-0000-0000-000000000000"
          catalog_name: "MyCatalog"
          template_name: "centos_6.7_x64_template"
          network_mode: pool
          network_name: "direct-connections-allowed"
```
##### Expected Results:

Machine _testAutoDeploy_ from template _centos_6.7_x64_template_ created and started inside vapp _my_vapp_ (with given vapp _instance_id_).
##### Actual Results:

```
fatal: [localhost]: FAILED! => {"changed": false, "failed": true, "invocation": {"module_name": "vca_vapp"}, "module_stderr": "/home/warear/praca/vcdenv/lib/python2.7/site-packages/requests/packages/urllib3/connectionpool.py:791: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.org/en/latest/security.html\n  InsecureRequestWarning)\n/home/warear/praca/vcdenv/lib/python2.7/site-packages/requests/packages/urllib3/connectionpool.py:791: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.org/en/latest/security.html\n  InsecureRequestWarning)\n/home/warear/praca/vcdenv/lib/python2.7/site-packages/requests/packages/urllib3/connectionpool.py:791: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.org/en/latest/security.html\n  InsecureRequestWarning)\n/home/warear/praca/vcdenv/lib/python2.7/site-packages/requests/packages/urllib3/connectionpool.py:791: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.org/en/latest/security.html\n  InsecureRequestWarning)\n/home/warear/praca/vcdenv/lib/python2.7/site-packages/requests/packages/urllib3/connectionpool.py:791: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.org/en/latest/security.html\n  InsecureRequestWarning)\nTraceback (most recent call last):\n  File \"/home/warear/.ansible/tmp/ansible-tmp-1455547055.46-178559918444595/vca_vapp\", line 2545, in <module>\n    main()\n  File \"/home/warear/.ansible/tmp/ansible-tmp-1455547055.46-178559918444595/vca_vapp\", line 278, in main\n    do_operation(module)\n  File \"/home/warear/.ansible/tmp/ansible-tmp-1455547055.46-178559918444595/vca_vapp\", line 207, in do_operation\n    vm = module.get_vm(vapp_name, vm_name)\n  File \"/home/warear/.ansible/tmp/ansible-tmp-1455547055.46-178559918444595/vca_vapp\", line 2326, in get_vm\n    raise VcaError('vapp has no vm named %s' % vm_name)\n__main__.VcaError: vapp has no vm named testAutoDeploy\n", "module_stdout": "", "msg": "MODULE FAILURE", "
```

Could you please tell me what's wrong?

BR,
Artur
