### ISSUE TITLE
osx_defaults fails with type set to string: "TypeError: isinstance() arg 2 must be a class, type, or tuple of classes and types"

### ISSUE THREAD

**Issue by dixhuit** [ansible/ansible-modules-extras#1742]
##### Issue Type:
- Bug
##### Plugin Name:

osx_defaults
##### Ansible Version:

```
ansible 2.0.1.0
  config file = /Users/danbohea/mac-playbook/ansible.cfg
  configured module search path = Default w/o overrides
```
##### Ansible Configuration:

```
[defaults]
gathering = smart
hostfile = ./hosts
log_path = ./ansible.log
roles_path = ext_roles
```
##### Environment:

Reproduced in:
- Mac OS 10.9
- Mac OS 10.11

(10.10 wasn't available to test in)
##### Summary:

Ansible fails when using `type` property `string` with the osx_defaults module.
##### Steps To Reproduce:

```
# This equivalent `defaults` command would work:
# defaults write NSGlobalDomain AppleShowScrollBars -string "Always"
- name: Always show scrollbars
  osx_defaults:
    domain: NSGlobalDomain
    key: AppleShowScrollBars
    type: string
    value: "Always"
```
##### Expected Results:

I'd expect the task to report with "OK" or "Changed" depending on the system state at the time.
##### Actual Results:

```
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: TypeError: isinstance() arg 2 must be a class, type, or tuple of classes and types
fatal: [mba]: FAILED! => {"changed": false, "failed": true, "parsed": false}
```
