### ISSUE TITLE
win_iis_webapppool: can't delete application pool

### ISSUE THREAD

**Issue by aensidhe** [ansible/ansible-modules-extras#1743]
##### Issue Type:

Please pick one and delete the rest:
- Bug Report
##### Plugin Name:

win_iis_webapppool:
##### Ansible Version:

```
ansible 2.0.0.2
  config file =
  configured module search path = Default w/o overrides
```
##### Ansible Configuration:

None
##### Environment:

OS X El Captain: 10.11.3
##### Summary:

Error is emitted during deletion of application pool
##### Steps To Reproduce:

Just run playbook below. AppPool will be deleted, but an error will be emitted.

Also, error emitted if there is no AppPool.

```
- name: test playbook for ansible issue tracking
  hosts: windows
  vars:
    - app: 'test-ansible-domain'

  tasks:
    - name: delete old app domain
      win_iis_webapppool:
        name: test
        state: absent

```
##### Expected Results:

AppPool deleted, no error messages
##### Actual Results:

Error message is emitted even if not 

```
Vault password:

PLAY [test playbook for ansible issue tracking] ********************************

TASK [setup] *******************************************************************
ok: [04.host]
ok: [05.host]

TASK [delete old app domain] ***************************************************
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: + ~~~~~~~~~~~~~~~~~
fatal: [04.host]: FAILED! => {"changed": false, "failed": true, "msg": "The property 'Name' cannot be found on this object. Verify that the property exists."}
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: + ~~~~~~~~~~~~~~~~~
fatal: [05.host]: FAILED! => {"changed": false, "failed": true, "msg": "The property 'Name' cannot be found on this object. Verify that the property exists."}

PLAY RECAP *********************************************************************
04.host   : ok=1    changed=0    unreachable=0    failed=1
05.host   : ok=1    changed=0    unreachable=0    failed=1
```
