### ISSUE TITLE
rabbitmq_user multiple permissions fails

### ISSUE THREAD

**Issue by johnjelinek** [ansible/ansible-modules-extras#1794]
##### Ansible Version: 2.0.1.0

```
ansible 2.0.1.0
  config file = ansible.cfg
  configured module search path = Default w/o overrides
```
##### Ansible Configuration:

`ansible.cfg`

```
[defaults]
host_key_checking = no

[ssh_connection]
ssh_args = -o ControlMaster=auto -o ControlPersist=60s -o UserKnownHostsFile=/dev/null -o IdentitiesOnly=yes

```
##### Summary:

@chrishoffman, I'm getting an error when using multiple permissions.
##### Steps To Reproduce:

```

---
- name: Create Admin
# ==================
  hosts: rmq[0]
  become: yes
  gather_facts: yes
  become_method: sudo

  tasks:
  - name: Set the admin password
    rabbitmq_user:
      user: "{{ rabbitmq_admin_user }}"
      password: "{{ rabbitmq_admin_pass }}"
      force: true
      permissions:
      - vhost: /
        configure_priv: .*
        write_priv: .*
        read_priv: .*
```
##### Expected Results:

I expected success
##### Actual Results:

```
fatal: [rabbitmq1]: FAILED! => {"changed": false, "failed": true, "invocation": {"module_args": {"force": true, "password": "password", "privileges": [{"configure_priv": ".*", "read_priv": ".*", "vhost": "/", "write_priv": ".*"}], "user": "admin"}, "module_name": "rabbitmq_user"}, "msg": "unsupported parameter for module: privileges"}
```
