### ISSUE TITLE
zabbix_host cannot delete host entry due to the SQL statement error.

### ISSUE THREAD

**Issue by tomgoto** [ansible/ansible-modules-extras#1800]
##### Issue Type:
- Bug Report
##### Plugin Name:

zabbix_host
##### Ansible Version:

```
ansible 2.0.1.0
```
##### Ansible Configuration:

Please mention any settings you've changed/added/removed in ansible.cfg
(or using the ANSIBLE_\* environment variables).
##### Environment:
- Ansible : CentOS7 with zabbix-api 0.4
- Zabbix:  Zabbix Server 2.4.7-1.el7 on CentOS7
##### Summary:

Adding host entry to zabbix server with `zabbix_host` module succeeded. 
However, deleting it failed with `Application error., SQL statement execution has failed`
##### Steps To Reproduce:

Add a host entry to zabbix server, then remove it.
Adding succeeds, but not the removing.

```
- name: initialize zabbix server entry
  hosts: localhost
  gather_facts: no
  become: no
  tasks:
      - name: Register merge request hosts to zabbix server
        zabbix_host:
          server_url: http://192.168.0.7/zabbix
          login_user: admin
          login_password: zabbix
          host_name: "{{item}}"
          state: present
          status: disabled
          host_groups:
            - "Linux Servers"
            - "Discovered hosts"
          interfaces:
            - type: 1
              main: 1
              useip: 1
              ip: 192.168.0.222
              dns: ""
              port: 10050
        with_items:
          - mytest

      - name: UnRegister merge request hosts from zabbix server
        zabbix_host:
          server_url: http://192.168.0.7/zabbix
          login_user: admin
          login_password: zabbix
          host_name: "{{item}}"
          state: absent
          status: disabled
          host_groups:
            - "Linux Servers"
            - "Discovered hosts"
          interfaces:
            - type: 1
              main: 1
              useip: 1
              ip: 192.168.0.222
              dns: ""
              port: 10050
        with_items:
          - mytest
```
##### Expected Results:

Add a host entry to zabbix, then delete the same entry from zabbix.
##### Actual Results:

First adding code succeeded, but removing failed with SQL statement execution. Ultimately `mytest` host exists in zabbix entry.

I also noticed `server_url` somewhat masked, but it may be irrelevant because adding task's `server_url` is also masked.

```
TASK [Register merge request hosts from zabbix server] *************************
changed: [localhost] => (item=mytest) => {"changed": true, "invocation": {"module_args": {"force": true, "host_groups": ["Linux Servers", "Discovered hosts"], "host_name": "mytest", "interfaces": [{"dns": "", "interfaceid": "24", "ip": "192.168.0.222", "main": 1, "port": 10050, "type": 1, "useip": 1}], "link_templates": null, "login_password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER", "login_user": "admin", "proxy": null, "server_url": "http://192.168.0.7/********", "state": "present", "status": "disabled", "timeout": 10}, "module_name": "zabbix_host"}, "item": "mytest", "result": "Successfully update host mytest (192.168.0.222) and linked with template 'None'"}

TASK [UnRegister merge request hosts from zabbix server] ***********************
failed: [localhost] => (item=mytest) => 
{
  "msg": "Failed to delete host myTesthost: (u'Error -32500: Application error., SQL statement execution has failed \"DELETE FROM scre
ens_items WHERE resourceid=Array AND resourcetype=\\'16\\'\" while sending {\"params\": {\"hostid\": \"10128\"}, \"jsonrpc\": \"2.0\", \"method\": \"host.delete\", \"auth\": \"ac129a6263de70928c8859ecd017c773\", \"id\": 6}', -32500)",
  "invocation": {
    "module_name": "zabbix_host",
    "module_args": {
      "timeout": 10,
      "status": "disabled",
      "state": "absent",
      "server_url": "http://192.168.0.7/********",
      "force": true,
      "host_groups": [
        "Linux Servers",
        "Discovered hosts"
      ],
      "host_name": "myTesthost",
      "interfaces": [
        {
          "useip": 1,
          "type": 1,
          "port": 10050,
          "main": 1,
          "ip": "192.168.0.222",
          "dns": ""
        }
      ],
      "link_templates": null,
      "login_password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
      "login_user": "admin",
      "proxy": null
    }
  },
  "failed": true,
  "changed": false
}
```

Thank you!
