### ISSUE TITLE
cs_staticnat: Creating a static nat fails

### ISSUE THREAD

**Issue by profhase** [ansible/ansible-modules-extras#1811]
##### Issue Type:

Bug Report
##### Plugin Name:

module:cloud/cloudstack/cs_staticnat.py
module:cloud/cloudstack/cs_staticnat2.py
##### Ansible Version:

2.0.0.2
##### Environment:

Ubuntu 14.04
##### Summary:

When trying to assign static ip which was obtained for a vpc with `cs_staticnat` module an error occurs: 
##### Steps To Reproduce:
- Create a cloudstack instance
- Assign this instance to a network in a `vpc`
- Obtain a static ip address for this vpc

Run the following Playbook

```
    - cs_staticnat:
        ip_address: {{ obtained_address }}
        state: present
        vm: "{{ my_vm }}"
        zone: "{{ my_zone }}"
```
##### Expected Results:

SUCCESS
##### Actual Results:

> fatal: [localhost]: FAILED! => {"changed": false, "failed": true, "msg": "CloudStackException: ('HTTP 431 response from CloudStack', <Response [431]>, {u'errorcode': 431, u'uuidList': [], u'cserrorcode': 4350, u'errortext': u'Unable to enable static nat for the ipAddress id=834 as ip is not associated with any network and no networkId is passed in'})"}

**Comment by resmo** [comment]
Thanks @profhase  for reporting

I am afraid, VPC is hardly tested in the cloudstack modules yet. I see in http://cloudstack.apache.org/api/apidocs-4.8/user/enableStaticNat.html that  the networkid must be given when using VPC, but this is not yet implemented. 

Since I am not a  VPC user, I am not sure how to implement it in a way that makes sense from a user perspective. May I ask you as a VPC user, would it makes sense to you if we have a `vpc` (vpc name) argument for `cs_staticnat` and we use the id of it to pass to `listNetworks` for get the `networkid`

``` yaml
 - cs_staticnat:
    ip_address: "{{ obtained_address }}"
    vm: "{{ my_vm }}"
    zone: "{{ my_zone }}"
    vpc: my_vpc
```

or would it make more sense to just pass the network name to find its id?

``` yaml
 - cs_staticnat:
    ip_address: "{{ obtained_address }}"
    vm: "{{ my_vm }}"
    zone: "{{ my_zone }}"
    network: my_vpc_network
```

What do you think?
