### ISSUE TITLE
mongodb_user ValueError: The value of ssl must be 'true' or 'false'\r\n", "msg": "MODULE FAILURE

### ISSUE THREAD

**Issue by shepyard** [ansible/ansible-modules-extras#1869]
##### Issue Type:

- Bug Report
##### Plugin Name:

mongodb_user
##### Ansible Version:

```
ansible 2.1.0
```
##### Environment:

centos 7.2.1511
mongodb 3.0.6
##### Summary:

New install of mongodb no auth, connecting on localhost, cannot create mongodb users 
##### Steps To Reproduce:

```
- name: Mongodb | create Mongo users
  mongodb_user:
    database: admin
    name: "{{ item.name }}"
    roles: "{{ item.roles }}"
    password: "{{ MONGODB_PASSWD }}"
    state: present
  with_items:
  - { name: "siteUserAdmin", roles: "userAdminAnyDatabase" }
  - { name: "siteRootAdmin", roles: "root" }
  tags: mongo

```
##### Expected Results:

mongodb users created 
##### Actual Results:

```
failed: [10.163.49.67] (item={u'name': u'siteRootAdmin', u'roles': u'root'}) => {"failed": true, "invocation": {"module_name": "mongodb_user"}, "item": {"name": "siteRootAdmin", "roles": "root"}, "module_stderr": "", "module_stdout": "\r\nTraceback (most recent call last):\r\n  File \"/home/admin/.ansible/tmp/ansible-tmp-1458297213.91-72274712879110/mongodb_user\", line 2358, in <module>\r\n    main()\r\n  File \"/home/admin/.ansible/tmp/ansible-tmp-1458297213.91-72274712879110/mongodb_user\", line 258, in main\r\n    client = MongoClient(login_host, int(login_port), ssl=ssl)\r\n  File \"/usr/lib64/python2.7/site-packages/pymongo/mongo_client.py\", line 342, in __init__\r\n    for k, v in keyword_opts.items())\r\n  File \"/usr/lib64/python2.7/site-packages/pymongo/mongo_client.py\", line 342, in <genexpr>\r\n    for k, v in keyword_opts.items())\r\n  File \"/usr/lib64/python2.7/site-packages/pymongo/common.py\", line 471, in validate\r\n    value = validator(option, value)\r\n  File \"/usr/lib64/python2.7/site-packages/pymongo/common.py\", line 131, in validate_boolean_or_string\r\n    \"'true' or 'false'\" % (option,))\r\nValueError: The value of ssl must be 'true' or 'false'\r\n", "msg": "MODULE FAILURE", "parsed": false}

```
