### ISSUE TITLE
Marker in blockinfile is a line prefix, not a whole line

### ISSUE THREAD

**Issue by mavit** [ansible/ansible-modules-extras#1926]
##### ISSUE TYPE
- Bug Report
##### COMPONENT NAME

`blockinfile`
##### ANSIBLE VERSION

```
ansible 2.1.0 (devel 2e529d7a51) last updated 2016/03/29 20:29:18 (GMT +100)
  lib/ansible/modules/core: (detached HEAD 0268864211) last updated 2016/03/29 20:30:38 (GMT +100)
  lib/ansible/modules/extras: (detached HEAD 6978984244) last updated 2016/03/29 20:30:38 (GMT +100)
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
```
##### CONFIGURATION

N/A.
##### OS / ENVIRONMENT

N/A.
##### SUMMARY

The `blockinfile` documentation talks about `marker` being a "line template", but actually it doesn't match against a whole line, it looks for this marker at the start of the line.  This causes trouble when one marker happens to be a leading substring of another marker.
##### STEPS TO REPRODUCE

Run the following play twice:

``` yaml
- hosts: localhost
  tasks:
    - blockinfile:
        dest: /tmp/example
        block: this is an example block to insert
        create: true
    - blockinfile:
        dest: /tmp/example
        block: this is a different block
        marker: '# {mark} ANSIBLE MANAGED BLOCK: non-default marker'
```
##### EXPECTED RESULTS

File `/tmp/example` has the following contents:

```
# BEGIN ANSIBLE MANAGED BLOCK
this is an example block to insert
# END ANSIBLE MANAGED BLOCK
# BEGIN ANSIBLE MANAGED BLOCK: non-default marker
this is a different block
# END ANSIBLE MANAGED BLOCK: non-default marker
```
##### ACTUAL RESULTS

File `/tmp/example` has the following contents:

```
# BEGIN ANSIBLE MANAGED BLOCK
this is an example block to insert
# END ANSIBLE MANAGED BLOCK
# BEGIN ANSIBLE MANAGED BLOCK
this is an example block to insert
# END ANSIBLE MANAGED BLOCK
# BEGIN ANSIBLE MANAGED BLOCK: non-default marker
this is a different block
# END ANSIBLE MANAGED BLOCK: non-default marker
```

Here, on the second run, the first task has overwritten the second block, and the second task has reinserted the second block.
