### ISSUE TITLE
docker_login username regex

### ISSUE THREAD

**Issue by joshrendek** [ansible/ansible-modules-extras#1947]
##### ISSUE TYPE
- Bug Report
##### COMPONENT NAME

docker_login module
##### ANSIBLE VERSION

2.0.0.2
##### CONFIGURATION

N/A
##### OS / ENVIRONMENT

Not platform specific
##### SUMMARY

When setting up a registry login using the docker_login module a username can't have a + or _ in it which prevents using robot accounts from places like quay.io
##### STEPS TO REPRODUCE

Enter a username like: foobar+some_tag

```
    - name: registry | Login
      docker_login:
        username: foobar+some_tag
        password: password123
        email: foo@bar.com
```
##### EXPECTED RESULTS

Login to succeed - command line `docker login` works fine.
##### ACTUAL RESULTS

```
fatal: [localhost]: FAILED! => {"changed": false, "failed": true, "msg": "Docker API Error: Registration: \"Wrong username format (it has to match \\\"^[a-z0-9]{4,30}$\\\")\""}
```
