### ISSUE TITLE
Can't set volume options via gluster_volume module

### ISSUE THREAD

**Issue by cu** [ansible/ansible-modules-extras#1965]
##### ISSUE TYPE

- Bug Report
##### COMPONENT NAME

gluster_volume
##### ANSIBLE VERSION

```
ansible 2.0.1.0
  config file = 
  configured module search path = Default w/o overrides
```
##### SUMMARY

I am unable to set options on a volume gluster using the `gluster_volume`'s `options` parameter.
##### STEPS TO REPRODUCE

This example from the documentation...

```
- name: tune
  gluster_volume: state=present name=test1 options='{performance.cache-size: 256MB}'
```

...throws a YAML syntax error.

My modified version of this...

```
- name: authorize specific docker hosts to mount the volume
  gluster_volume:
    name: test1
    state: present
    options:
      auth.allow: "127.0.0.1"
```

...parses correctly but returns this error when the task is run:

```
fatal: [gfs-02.eng.example.net]: FAILED! => {"changed": false, "failed": true, "module_stderr": "", "module_stdout": "Traceback (most recent call last):\r\n  File \"/home/example/.ansible/tmp/ansible-tmp-1459822578.91-3810522444797/gluster_volume\", line 2416, in <module>\r\n    main()\r\n  File \"/home/example/.ansible/tmp/ansible-tmp-1459822578.91-3810522444797/gluster_volume\", line 382, in main\r\n    probe_all_peers(cluster, peers, myhostname)\r\n  File \"/home/example/.ansible/tmp/ansible-tmp-1459822578.91-3810522444797/gluster_volume\", line 259, in probe_all_peers\r\n    for host in hosts:\r\nTypeError: 'NoneType' object is not iterable\r\n", "msg": "MODULE FAILURE", "parsed": false}
```
