### ISSUE TITLE
blockinfile: marker doesn't compare entire line

### ISSUE THREAD

**Issue by moralloki** [ansible/ansible-modules-extras#1968]
##### ISSUE TYPE
- Bug Report
##### COMPONENT NAME

blockinfile
##### ANSIBLE VERSION

```
ansible 2.0.1.0
  config file = /etc/ansible.cfg
  configured module search path = Default w/o overrides
```
##### OS / ENVIRONMENT

N/A
##### SUMMARY

The marker directive doesn't compare the entire line when checking for blocks.  Similar blocks will be unintentionally overwritten breaking idempotency.
##### STEPS TO REPRODUCE

Can be reproduced from a tweak to one of the examples run 2+ times:

```
- name: insert/update hosts in /tmp/hosts
  blockinfile:
    dest: /tmp/hosts
    block: |
      {{item.name}} {{item.ip}}
    marker: "# {mark} ANSIBLE MANAGED BLOCK {{item.name}}"
  with_items:
      - { name: host, ip: 10.10.1.10 }
      - { name: host2, ip: 10.10.1.11 }
```

##### EXPECTED RESULTS

```
# BEGIN ANSIBLE MANAGED BLOCK host
host 10.10.1.10
# END ANSIBLE MANAGED BLOCK host
# BEGIN ANSIBLE MANAGED BLOCK host1
host1 10.10.1.11
# END ANSIBLE MANAGED BLOCK host1
```
##### ACTUAL RESULTS

```
# BEGIN ANSIBLE MANAGED BLOCK host
host 10.10.1.10
# END ANSIBLE MANAGED BLOCK host
# BEGIN ANSIBLE MANAGED BLOCK host
host 10.10.1.10
# END ANSIBLE MANAGED BLOCK host
# BEGIN ANSIBLE MANAGED BLOCK host1
host1 10.10.1.11
# END ANSIBLE MANAGED BLOCK host1
```
