### ISSUE TITLE
lxc_container container_config update is broken

### ISSUE THREAD

**Issue by slash3g** [ansible/ansible-modules-extras#1998]
##### ISSUE TYPE
- Bug Report
##### COMPONENT NAME

lxc_container
##### ANSIBLE VERSION

```
ansible 2.0.1.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
```

(bug still present in devel branch)
##### CONFIGURATION

Default Ansible configuration.
##### OS / ENVIRONMENT

N/A
##### SUMMARY

lxc_container handles container configuration via the container_configuration parameter. Unfortunately, the logic behind the configuration update is broken, as it duplicates the key and never replaces old values. Morever, when the configuration file contains duplicated keys, the script can fail to make any changes.
##### STEPS TO REPRODUCE

Exec the following playbook

```

---
- hosts: myhost
  tasks:
      - name: fist config update
        lxc_container:
            name: mycontainer
            container_config:
                - "lxc.start.auto = 0"
      - name: second config update
        lxc_container:
            name: mycontainer
            container_config:
                - "lxc.start.auto = 1"
```
##### EXPECTED RESULTS

```
$ grep start mycontainer/config
lxc.start.auto  =  1
```
##### ACTUAL RESULTS

```
$ grep start mycontainer/config
lxc.start.auto  =  0
lxc.start.auto  =  1
```
