### ISSUE TITLE
os_server - Trying to allocate floating IP when not asked to

### ISSUE THREAD

**Issue by sboulkour** [ansible/ansible-modules-extras#2032]
##### ISSUE TYPE
- Bug Report
##### COMPONENT NAME

os_server
##### ANSIBLE VERSION

`ansible 2.0.1.0`
##### CONFIGURATION

none
##### OS / ENVIRONMENT

"N/A"
##### SUMMARY

When trying to create a VM through os_server module, I get an error from the API stating it can't allocate an floating IP, which I didn't ask it to create.
##### STEPS TO REPRODUCE

Sample playbook :

```

---

- hosts: localhost
  tasks:
  - name: launch an instance
    os_server:
      name: test_ansible
      state: present
      image: c06fe6f2-3567-4ec3-8562-4cecf4044c30 #Centos 7
      flavor: 603e9687-1b6f-4e51-bf6e-8cdc4369e7e7 #eg-7
      key_name: xXxXx
      security_groups:
        - 3c8ee201-892b-436e-90b3-6655b10b63f1 #ANY_10_77
      nics:
        - net-id: 0b842919-85d6-4e8f-90b1-32faa04e4ae9 #vlan1 (private network)
        - net-id: 9029f0c9-ad37-4f4f-80cf-e21852937201 #vlan2 (private network)
```
##### EXPECTED RESULTS

A VM created with no such errors, especially about a network that ansible shouldn't request for.
##### ACTUAL RESULTS

```
fatal: [localhost]: FAILED! => {"changed": false, "extra_data": null, "failed": true, "invocation": {"module_args": {"api_timeout": null, "auth": null, "auth_type": null, "auto_ip": true, "availability_zone": null, "boot_from_volume": false, "boot_volume": null, "cacert": null, "cert": null, "cloud": null, "config_drive": false, "endpoint_type": "public", "flavor": "603e9687-1b6f-4e51-bf6e-8cdc4369e7e7", "flavor_include": null, "flavor_ram": null, "floating_ip_pools": null, "floating_ips": null, "image": "c06fe6f2-3567-4ec3-8562-4cecf4044c30", "image_exclude": "(deprecated)", "key": null, "key_name": "SBO-ovh", "meta": null, "name": "test_ansible-SBO", "network": null, "nics": [{"net-name": "pn-15896_vlan1"}, {"net-name": "pn-15896_vlan2"}], "region_name": null, "security_groups": ["3c8ee201-892b-436e-90b3-6655b10b63f1"], "state": "present", "terminate_volume": false, "timeout": 180, "userdata": null, "verify": true, "volume_size": false, "volumes": [], "wait": true}, "module_name": "os_server"}, "msg": "unable to get available floating IPs: unable to create floating IP for net **3f4e3b19-4a46-4672-aade-5654d1fc0704**: Policy doesn't allow create_floatingip to be performed."}
```

Note that the pointed _net id_ exists and is the actual public net. But as stated earlier, playbook doesn't refer to it or to floating ips.

Also, when using openstack cli with the same parameters, I get no errors and VM is created flawlessly :

```
$ openstack server create test_ansible --security-group 3c8ee201-892b-436e-90b3-6655b10b63f1 --image c06fe6f2-3567-4ec3-8562-4cecf4044c30 --flavor 603e9687-1b6f-4e51-bf6e-8cdc4369e7e7 --nic net-id=0b842919-85d6-4e8f-90b1-32faa04e4ae9 --key-name xXxXx
+--------------------------------------+------------------------------------------------------+
| Field                                | Value                                                |
+--------------------------------------+------------------------------------------------------+
| OS-EXT-STS:vm_state                  | building                                             |
 [...]
| status                               | BUILD                                                |
| updated                              | 2016-04-14T16:46:14Z                                 |
+--------------------------------------+------------------------------------------------------+
```
