### ISSUE TITLE
win_firewall_rule: default profile 'current' not valid 

### ISSUE THREAD

**Issue by one1zero1one** [ansible/ansible-modules-extras#2036]
##### ISSUE TYPE

- Bug Report
##### COMPONENT NAME

win_firewall_rule
##### ANSIBLE VERSION

```
ansible 2.1.0 (devel cb7b3b489d) last updated 2016/03/30 15:14:21 (GMT +200)
  lib/ansible/modules/core: (detached HEAD 0268864211) last updated 2016/03/30 15:14:39 (GMT +200)
  lib/ansible/modules/extras: (detached HEAD 6978984244) last updated 2016/03/30 15:14:39 (GMT +200)
```
##### OS / ENVIRONMENT

Ubuntu 14.4 -> Windows 2012 R2 (Microsoft Windows [Version 6.3.9600])
##### SUMMARY

[Example](http://docs.ansible.com/ansible/win_firewall_rule_module.html#examples) doesn't work. Returns "changed": true, but rule is not created. 
##### STEPS TO REPRODUCE

```
- name: Firewall rule to allow smtp on TCP port 25
  action: win_firewall_rule
  args:
      name: smtp
      enable: yes
      state: present
      localport: 25
      action: allow
      direction: In
      protocol: TCP
```

##### EXPECTED RESULTS

Firewall Rule to be added.
##### ACTUAL RESULTS

`changed: [xxxxxxx] => {"changed": true, "difference": [], "failed": false, "fwsettings": {"Action": "allow", "Direction": "In", "Enabled": "yes", "LocalPort": 25, "Profiles": "current", "Protocol": "TCP", "Rule Name": "smtp"}, "invocation": {"module_name": "win_firewall_rule"}, "msg": ["No rule could be found", "netsh advfirewall firewall add rule action=\"allow\" enable=\"yes\" dir=\"In\" name=\"smtp\" profile=\"current\" protocol=\"TCP\" localport=\"25\"", "Created firewall rule smtp"]}`

However, on the windows box the rule is **not** added - and when running the above in cmd returns

```
C:\Users\xxxxxxx>netsh advfirewall firewall add rule action=\"allow\" enable=\"yes\" dir=\"In\" 
name=\"smtp\" profile=\"current\" protocol=\"TCP\" localport=\"25\"

One or more of the specified profiles is  not valid. 'Any' cannot be specified
 if other profiles are specified.

```

Dirty fix was to comment out  $fwsettings.Add("Profiles", $winprofile).  
Excluding profiles alltoghether was the only way to add/remove rules that have profile "All" in GUI, and return to the idempotent behaviour of the module.
