### ISSUE TITLE
yumrepo listed in Ansible module packaging documentation, but not shipped in epel package

### ISSUE THREAD

**Issue by ahuffman** [ansible/ansible-modules-extras#2063]
##### ISSUE TYPE
- Bug Report
- Documentation Report
##### COMPONENT NAME

yumrepo
##### ANSIBLE VERSION

```
ansible 2.0.1.0
```
##### CONFIGURATION

forks=50
scp_if_ssh = True
##### OS / ENVIRONMENT

RHEL7
##### SUMMARY

Trying to use the yumrepo module in a role, but getting error: 
ERROR! no action detected in task. This often indicates a misspelled module name, or incorrect module path.

This corresponds to the task trying to make use of the yumrepo module.
##### STEPS TO REPRODUCE

```
- name: Setup CentOS7-Extras Repository for cockpit-kubernetes
  yum_repository:
    file: centos7-extras.repo
    name: centos7-extras
    description: CentOS7 - Extras
    baseurl: http://mirror.centos.org/centos/7/extras/x86_64/
    enabled: yes
    gpgcheck: yes
    gpgkey: http://mirror.centos.org/centos/RPM-GPG-KEY-CentOS-7
    includepkgs: cockpit-kubernetes
  when: k8s_cockpit == 'yes'
```
##### EXPECTED RESULTS

A yumrepo would be created on the selected host.
##### ACTUAL RESULTS

ERROR! no action detected in task. This often indicates a misspelled module name, or incorrect module path.

The error appears to have been in '/etc/ansible/roles/k8s-master/tasks/main.yml': line 12, column 3, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:
- name: 'Setup CentOS7-Extras Repository for cockpit-kubernetes'
  ^ here
