### ISSUE TITLE
win_iis_webapppool failing with 'Specified cast is not valid'

### ISSUE THREAD

**Issue by michelleperz** [ansible/ansible-modules-extras#2072]
##### ISSUE TYPE

- Bug Report
##### COMPONENT NAME

win_iis_webapppool
##### ANSIBLE VERSION

```
ansible --version
ansible 2.0.0.2
  config file = 
  configured module search path = Default w/o overrides
```
##### CONFIGURATION

No changes
##### OS / ENVIRONMENT

N/A
##### SUMMARY

The win_iis_webappool documentation states that you can separate attributes by a pipe and name values by colon like  "foo:1|bar:2"  However, doing this in the task results in a 'Specified cast is not valid error.'
##### STEPS TO REPRODUCE

Create a basic playbook with attributes that are separated by a pipe:

```
- name: Setting up IIS application pool 
    win_iis_webapppool: 
      name: PoolParty
      state: started 
      attributes: "managedRuntimeVersion:v4.0|managedPipelineMode:0|queueLength:30000"
```

##### EXPECTED RESULTS

App pool would get created successfully.
##### ACTUAL RESULTS

```
TASK [Setting up IIS application pool] *****************************************
fatal: [52.39.68.141]: FAILED! => {"changed": false, "failed": true, "msg": "Specified cast is not valid."}
```
