### ISSUE TITLE
win_firewall_rule: is broke under strict-mode

### ISSUE THREAD

**Issue by dreamcat4** [ansible/ansible-modules-extras#2073]
##### ISSUE TYPE
- Bug Report
##### COMPONENT NAME

win_firewall_rule
##### ANSIBLE VERSION

```
id@emachines-e520:~/ansible$ ansible --version
ansible 2.0.0.2
  config file = /home/id/ansible/ansible.cfg
  configured module search path = ./library
```

Where `./library` is checked out from `ansible/$repo_name:devel`.
##### CONFIGURATION

``` ini
[defaults]
bin_ansible_callbacks=True
inventory = ./inventory/lan
callback_plugins = ./callback_plugins
library = ./library
hash_behaviour = merge
```

AFAIK nothing was changed since `1.9.4`, and this same playbook used to work back then.
##### OS / ENVIRONMENT
- Linux (ubuntu 15.10) control node.
- Windows 10 (WINRM) target host.
##### SUMMARY

As predicted, more bugs fall out of win_firewall_rule if you shake it. This error can be effectively supressed by inserting the following line near the top of the module's .ps1 file:

``` powershell
# temporarily disable strictmode, for this module only
Set-StrictMode -Off
```
##### STEPS TO REPRODUCE

``` yaml
- name: Firewall - Be sure mongoose is allowed
  win_firewall_rule:
    name: Allow mongoose HTTP
    enable: yes
    profile: Domain,Private,Public
    program: "{{ mongoose_bin_win }}"
    direction: in
    action: allow
    state: present
    force: yes
```
##### EXPECTED RESULTS

It to work.
##### ACTUAL RESULTS

It doesnt work.

Comes back with some 'missing property for `Program` / cannot be set on this object' type error. Meaning its due to strict-mode. Sorry I don't have the exact logs at hand anymore. Had to move on.

Thing is here: I tried really hard to fix this module. But it just kept coming back with the same error. Its due to the weird ways it works / doesnt work. I strongly recommend to disable strict-mode (for this particular module only). And consider a re-write / re-think of the whole code. Since fixing these strict-mode errors certianly isnt magically gonna turn it into good / clear / consise / well-thought-out code. So there's no benefit here leaving it in place as things stand.

I'm making a PR now with many other strict-mode fixes. So I would like to include a disable strict-mode for this one too. To simply get it working again. As firewall is an important feature for many users.
