### ISSUE TITLE
win_regedit: no longer possible to specify binary values as yaml array of bytes.

### ISSUE THREAD

**Issue by jhawkesworth** [ansible/ansible-modules-extras#2090]
##### ISSUE TYPE
- Bug Report
##### COMPONENT NAME

win_regedit
##### ANSIBLE VERSION

```
ansible 2.1.0 (devel ba74f5f3e5) last updated 2016/04/20 23:46:56 (GMT +100)
  lib/ansible/modules/core: (devel 36755e5fe2) last updated 2016/04/24 16:06:03 (GMT +100)
  lib/ansible/modules/extras: (devel de22b721db) last updated 2016/04/24 16:03:40 (GMT +100)
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides

```
##### CONFIGURATION

default configuration
##### OS / ENVIRONMENT

Ansible OS: Lubuntu 14.04 64 bit
Managed nodes: Windows 10
##### SUMMARY

Since https://github.com/ansible/ansible-modules-extras/pull/2034 was merged it is no longer possible to use generic YAML array of bytes syntax to specify binary registry entry values.

https://github.com/ansible/ansible-modules-extras/pull/2034 introduced the capability to set binary values using a string representation of binary values which matches the representation which is exported by the windows binary regedit.exe.  Unfortunately this has broken the ability to specify using a YAML array of bytes.
##### STEPS TO REPRODUCE

To reproduce:

run a playbook containing the following task against 1 or more windows hosts:

```
 - name: regedit binary data using yaml syntax (currently failing)
   win_regedit:
      key: HKCU:\Software\Classes\Local Settings\Software\Microsoft\Windows\CurrentVersion\AppContainer\Storage\microsoft.microsoftedge_8wekyb3d8bbwe\MicrosoftEdge\Main
      value: IE10TourShownTime
      data: [0x21,0xb3,0x33,0xf9,0x0d,0xff,0xd0,0x01]
```
##### EXPECTED RESULTS

success
##### ACTUAL RESULTS

Exception (results similar to below)

```
An exception occurred during task execution. The full traceback is:
At C:\Users\ansible\AppData\Local\Temp\ansible-tmp-1461253469.93-78361801785042\win_regedit.ps1:348 char:57
+ ...  $registryData = Convert-RegExportHexStringToByteArray($registryData)
+                                                           ~~~~~~~~~~~~~~~
failed: [ga-z170x-g3] => (item=[{u'sid': u'S-1-5-21-1869920885-1910292401-595555687-1001', u'localpath': u'C:\\Users\\id', u'name': u'id'}, {u'name': u'Microsoft Edge>Settings> IE 10 Tour Shown Time', u'descr': u'Skips this one-time only first-use feature', u'datatype': u'binary', u'value': u'IE10TourShownTime', u'state': u'present', u'subkey': u'SOFTWARE\\Classes\\Local Settings\\Software\\Microsoft\\Windows\\CurrentVersion\\AppContainer\\Storage\\microsoft.microsoftedge_8wekyb3d8bbwe\\MicrosoftEdge\\Main', u'data': [33, 179, 51, 249, 13, 255, 208, 1]}]) => {"failed": true, "invocation": {"module_name": "win_regedit"}, "item": [{"localpath": "C:\\Users\\id", "name": "id", "sid": "S-1-5-21-1869920885-1910292401-595555687-1001"}, {"data": [33, 179, 51, 249, 13, 255, 208, 1], "datatype": "binary", "descr": "Skips this one-time only first-use feature", "name": "Microsoft Edge>Settings> IE 10 Tour Shown Time", "state": "present", "subkey": "SOFTWARE\\Classes\\Local Settings\\Software\\Microsoft\\Windows\\CurrentVersion\\AppContainer\\Storage\\microsoft.microsoftedge_8wekyb3d8bbwe\\MicrosoftEdge\\Main", "value": "IE10TourShownTime"}], "msg": "Cannot process argument transformation on parameter 'String'. Cannot convert value to type System.String."}
```
