### ISSUE TITLE
maven_artifact does not use classifier when constructing destination name of artifact

### ISSUE THREAD

**Issue by tmoschou** [ansible/ansible-modules-extras#2139]
##### ISSUE TYPE
- Bug Report
##### COMPONENT NAME

maven_artifact
##### ANSIBLE VERSION

```
$ ansible --version
ansible 2.2.0 (devel 1fc44e4103) last updated 2016/05/02 13:44:52 (GMT +1050)
  lib/ansible/modules/core: (detached HEAD b6ad3b6773) last updated 2016/05/02 13:45:21 (GMT +1050)
  lib/ansible/modules/extras: (devel 1846de2809) last updated 2016/05/02 13:28:20 (GMT +1050)
  config file = xxx/ansible-playbooks/ansible.cfg
  configured module search path = Default w/o overrides
```
##### CONFIGURATION

```
[defaults]
host_key_checking = False
[ssh_connection]
control_path = %(directory)s/%%h-%%r
```
##### OS / ENVIRONMENT

OS X El Capitan v10.11.4
##### SUMMARY

When specifying a classifier for maven_artifact and a directory as the dest parameter, the destination filename is constructed assuming no classifier. I.e.

`artifact_id + "-" + version + "." + extension` vs
`artifact_id + "-" + version + "-" + classifier + "." + extension`

This causes problems when say downloading multiple artifacts with same same groupId:artifactId:version coordinates. Depending of the version of lib/ansible/modules/extras used, either subsequent artifacts are skipped because the destination exists, or is overwritten as the MD5 hash is different.
##### STEPS TO REPRODUCE

```

---
- hosts: test-hosts
  tasks:
    - name: Create temporary directory
      file:
        path: /tmp/ansible-test
        state: directory

    - name: Download Stanford Core NLP
      maven_artifact:
        group_id: edu.stanford.nlp
        artifact_id: stanford-corenlp
        version: 3.6.0
        dest: /tmp/ansible-test/
        state: present

    - name: Download Stanford Core NLP Models
      maven_artifact:
        group_id: edu.stanford.nlp
        artifact_id: stanford-corenlp
        version: 3.6.0
        classifier: models
        dest: /tmp/ansible-test/
        state: present
```
##### EXPECTED RESULTS

Should download two artifacts to

```
/tmp/ansible-test/stanford-corenlp-3.6.0.jar, and
/tmp/ansible-test/stanford-corenlp-3.6.0-models.jar
```
##### ACTUAL RESULTS

One file `/tmp/ansible-test/stanford-corenlp-3.6.0.jar`
