### ISSUE TITLE
consul_session: feature - add "behavior" to session creation

### ISSUE THREAD

**Issue by irlevesque** [ansible/ansible-modules-extras#2154]
##### ISSUE TYPE
- Feature Idea
##### COMPONENT NAME

consul_session
##### ANSIBLE VERSION

```
ansible 2.0.2.0
  config file =
  configured module search path = Default w/o overrides
```
##### CONFIGURATION

N/A
##### OS / ENVIRONMENT

```
pip freeze | grep consul
python-consul==0.6.0
```
##### SUMMARY

python-consul provides the [`behavior` parameter](http://python-consul.readthedocs.io/en/latest/#consul.base.Consul.Session) when creating a session:

> behavior can be set to either ‘release’ or ‘delete’. This controls the behavior when a session is invalidated. By default, this is ‘release’, causing any locks that are held to be released. Changing this to ‘delete’ causes any locks that are held to be deleted. ‘delete’ is useful for creating ephemeral key/value entries

Implemented here: https://github.com/quantopian/ansible-modules-extras/commit/763c8f75c19b926618d1a066ec792c058872fd43
##### STEPS TO REPRODUCE

```
    - name: Register new session
      consul_session:
        name: "{{ consul_session_name }}"
        behavior: delete
```
##### EXPECTED RESULTS

Consul session created with a "delete" behavior.
