### ISSUE TITLE
consul_kv: Fix session-based kv acquire/release

### ISSUE THREAD

**Issue by irlevesque** [ansible/ansible-modules-extras#2155]
##### ISSUE TYPE
- Bug Report
##### COMPONENT NAME

consul_kv
##### ANSIBLE VERSION

```
ansible 2.0.2.0
  config file =
  configured module search path = Default w/o overrides
```
##### CONFIGURATION

N/A
##### OS / ENVIRONMENT

```
pip freeze | grep consul
python-consul==0.6.0
```
##### SUMMARY

Following the documented procedure for adding a KV with an associated session fails in multiple ways:
- setting `state` to `acquire` or `release` results in an error that the only valid options are `present` or `absent`
- setting the `session` attribute does nothing; it is not actually used in the code
##### STEPS TO REPRODUCE

``` yaml
    - name: Register KV with session
      consul_kv:
        key: 'stg/metadata/sessionkv'
        value: testing
        session: "{{ sessionid }}"
        state: acquire
```

ansible-playbook -i 'localhost,' -c local consul-kv.yml
##### EXPECTED RESULTS
- successful playbook execution
- registration of a kv pair in consul with an associated session lock
##### ACTUAL RESULTS

```
fatal: [ec2.compute-1.amazonaws.com]: FAILED! => {"changed": false, "failed": true, "msg": "value of state must be one of: present,absent, got: acquire"}
```

After fixing this error and the associated `lock()` method which appears to have never been wired, I noticed that the session wasn't even being passed into the params.

Fixes here: https://github.com/quantopian/ansible-modules-extras/commit/552ab6bb97d08353f66171149ca7fb305570a0bb
