### ISSUE TITLE
bigip_virtual_server module not found

### ISSUE THREAD

**Issue by mrafieee** [ansible/ansible-modules-extras#2174]
##### ISSUE TYPE

- Bug Report
##### COMPONENT NAME

bigip_virtual_server
##### ANSIBLE VERSION

```
ansible 2.0.2.0
```
##### STEPS TO REPRODUCE

```
# add virtual servers
- hosts: localhost
  tasks:
  - name: Add VS http
    local_action:
        module: bigip_virtual_server
        server: "{{ f5_host }}"
        user: "{{ f5_user }}"
        password: "{{ f5_password }}"
        state: present
        partition: "{{ f5_partition }}"
        name: "vs.http"
        destination: "{{ vip }}"
        port: 80
        snat: Automap
        description:  Virtual Server
        all_profiles:
            - http
            - tcp
```
##### EXPECTED RESULTS

to create virtual server
##### ACTUAL RESULTS

```
FAILED! => {"failed": true, "msg": "The module bigip_virtual_server was not found in configured module paths. Additionally, core modules are missing. If this is a checkout, run 'git submodule update --init --recursive' to correct this problem."}
```
