### ISSUE TITLE
creating a secondary ec2_eni with secondary ips results in error 'get_ec2_security_group_ids_from_names' is not defined

### ISSUE THREAD

**Issue by christonog** [ansible/ansible-modules-extras#2176]
##### ISSUE TYPE

- Bug Report
##### COMPONENT NAME

ec2_eni
##### ANSIBLE VERSION

```
ansible 2.0.2.0
  config file = /home/ec2-user/Ansible/ansible.cfg
  configured module search path = ./library
```
##### OS / ENVIRONMENT

Mac OSX 10.11.4
##### STEPS TO REPRODUCE

1. add the parameter: secondary_private_ip_address_count to the ec2_eni module
2. Run playbook to add eni to an ec2 instance

Note I didn't test this with a primary eni, only when adding a secondary. Not sure if it makes a difference.

```
<!--- Paste example playbooks or commands between quotes -->

- name: Create a 2nd separate ENI
  ec2_eni:
    subnet_id: "{{ vpc_subnet_id }}"
    instance_id: "{{ item }}"
    device_index: 1
    region: "{{ region }}"
    state: present
    secondary_private_ip_address_count: '{{ number_of_secondary_ips }}'
  ignore_errors: true


```

##### EXPECTED RESULTS

The specified number of secondary ips should be added.
##### ACTUAL RESULTS

```
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: NameError: global name 'get_ec2_security_group_ids_from_names' is not defined
fatal: [localhost]: FAILED! => {"changed": false, "failed": true, "module_stderr": "Traceback (most recent call last):\n  File \"<stdin>\", line 4674, in <module>\n  File \"<stdin>\", line 473, in main\n  File \"<stdin>\", line 237, in create_eni\nNameError: global name 'get_ec2_security_group_ids_from_names' is not defined\n", "module_stdout": "", "msg": "MODULE FAILURE", "parsed": false}
```

I can add additional verbosity if needed.
