### ISSUE TITLE
known_hosts returns changes even if there are none

### ISSUE THREAD

**Issue by crane-denny** [ansible/ansible-modules-extras#2177]
##### ISSUE TYPE
- Bug Report
##### COMPONENT NAME

known_hosts
##### ANSIBLE VERSION

```
ansible --version
ansible 2.0.2.0
  config file = /Users/crane/unify/helpers/ansible/ansible-projects.cfg
  configured module search path = Default w/o overrides
```
##### CONFIGURATION

N/A
##### OS / ENVIRONMENT

N/A
##### SUMMARY

When running know_hosts module Ansible keeps on telling that it has changed stuff even if the key is present.
##### STEPS TO REPRODUCE

```

---
- hosts: localhost
  become: no
  vars:
    servers
      - pub: "[example.net]:223,[192.168.0.1]:223 ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQCpPJFmRyCeAp2IiZJ/x4J7iGr8DJCfmGyvmgc9KPh1OPe+xTdwDvB9aCDEQkSe674oiuyomnLkendFTyFSAGFLhqwdm6bcTjdIKm8zFkCgqNnlIEhUS4CAMg8MKnHi3D/IqieVjydg4aMLl4w4y0jMT7aJNi5355Hp0ckK5jZ4N/PPyK9tFacuzZsa4PZzImWOw8BlIZj2rFLvLc6Xa3xo5+        9BMECrifexSryK9heiUStF/MU4y8hUU6MoQdEp1qZUPvDJ7UreCxwCnLRTI4GonqrdEM7TVp3MMk9uLHWR9X3EM/jQbGlE0hNhc3MpgAaKZEaJxOFRa12evcRjS7TiM524ezNGsF5Cx8Keac/ZblTqUMQfukjpRtavaZWRcYHD8h9V2hCX21zqV9wH8QXhjm0Ynmcv1rDq2EfjH5r23rHYtqhF/KBggxWLuSOq/x4QXEmfIFFJx/jLrPTQ8vHVvy4ItUA+itDWI4BB9WsUKnCshAQpZAj8/                               v0HEhcpTdXh0TSHg6o5BgXOQOchUhX4Xvc2WIDksg1uLJ9X/CMu8pkYXwgLrqARLajNdTeW4sfIgCtXKUN9d34fDONyKnTyd/m31rLSJJTkeQ6v0b3P9rAVAYlgfMSuf/abdSIfojql364Ung/7/1859lJr9S4XM6CXsb/IlsCCQ4bH9ndy1w=="
        hosts:
          - "[example.net]:223"
          - "[192.168.0.1]:223"
  tasks:
    - name: Adding servers to know hosts 
      known_hosts:
        key: "{{ item.0.pub }}"
        name: "{{ item.1 }}"
      with_subelements:
        - "{{ servers }}"
        - hosts
```
##### EXPECTED RESULTS

Only once a change and after this no more changes
##### ACTUAL RESULTS

I keep on getting "changes" with every run.
