### ISSUE TITLE
consul_acl documentation for token type option appears to be incorrect

### ISSUE THREAD

**Issue by coconitro** [ansible/ansible-modules-extras#2213]
##### ISSUE TYPE

- Documentation Report
##### COMPONENT NAME

consul_acl
##### ANSIBLE VERSION

```
ansible 2.0.2.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
```
##### CONFIGURATION

N/A
##### OS / ENVIRONMENT

N/A
##### SUMMARY

The documentation for the consul_acl module lists the option `type` for controlling token type, but using this option results in an error. Internally it appears the actual option name is `token_type`. Documentation should reflect this.
##### STEPS TO REPRODUCE

A task with the following will fail:

```
- name: create deploy token
  consul_acl:
    mgmt_token: 'super-top-secret'
    name: 'special token'
    token: 'top-secret'
    type: management
    state: present
```

A task with the following will succeed:

```
- name: create deploy token
  consul_acl:
    mgmt_token: 'super-top-secret'
    name: 'special token'
    token: 'top-secret'
    token_type: management
    state: present
```

##### EXPECTED RESULTS

The documented option should work as described.
##### ACTUAL RESULTS

Using the documented option results in the following output:

```
TASK [acls : create alerts token] **********************************************
fatal: [localhost]: FAILED! => {"changed": false, "failed": true, "msg": "unsupported parameter for module: type"}
```
