### ISSUE TITLE
win_environment cannot append to Path in System Variable

### ISSUE THREAD

**Issue by sayantandas** [ansible/ansible-modules-extras#2215]
win_environment cannot append values to Path in System Variable. It replaces existing variables
##### ISSUE TYPE

- Feature Request
##### COMPONENT NAME

win_environment module
##### ANSIBLE VERSION

```
2.0.0.2
```
##### CONFIGURATION

ansible --version
ansible 2.0.0.2
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
##### OS / ENVIRONMENT

 cat /etc/lsb-release 
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=16.04
DISTRIB_CODENAME=xenial
DISTRIB_DESCRIPTION="Ubuntu 16.04 LTS"
##### SUMMARY

win_environment cannot append values to Path in System Variable
##### STEPS TO REPRODUCE

Run below ansible script on a windows host to check the system Path is replaced not appended

```

- name: Set Perl Environment Path
  win_environment:
   state: present
   name: PATH
   value: 'C:\Perl\bin'
   level: machine
```

##### EXPECTED RESULTS

Expecting a way to append Values to existing Path Variable
##### ACTUAL RESULTS

``` It replaces PATH values

<!--- Paste verbatim command output between quotes -->

```
```
