### ISSUE TITLE
maven_artifact should support version=release.

### ISSUE THREAD

**Issue by tmoschou** [ansible/ansible-modules-extras#2219]
##### ISSUE TYPE
- Bug Report
##### COMPONENT NAME

maven_artifact
##### ANSIBLE VERSION

ansible-modules-extras
commit cd03f10b9ccb9f972a4cf84bc3e756870257da59 (HEAD -> devel, origin/stable-21, origin/devel, origin/HEAD)
##### SUMMARY

A few problems with the maven_artifact module.

It supports a version=latest parameter but not a version=release parameter to download the latest release (non snapshot) artifact. 

The current way the module determines the latest is by retrieving the last version tag in a potentially unordered list.

```
v = xml.xpath("/metadata/versioning/versions/version[last()]/text()")
```

when if fact it should be using the `/metadata/versioning/latest` field. Likewise for release `/metadata/versioning/release`. 

Further there is no way to know what version was actually downloaded. As by default the destination file (when dest is specified as a directory) uses the string `latest` for the version in the filename. 

Our current workaround is to use the the get_url module with our repos' [Sonatype REST API](https://repository.sonatype.org/nexus-restlet1x-plugin/default/docs/path__artifact_maven_redirect.html). E.g.

```
- name: Download the latest release of c6-api
  get_url:
    url: "{{ mirror }}/service/local/artifact/maven/redirect?r=releases&g={{ group }}&a={{ artifact }}&v=RELEASE&c={{ classifier }}"
    url_username: "{{ maven_user }}"
    url_password: "{{ maven_password }}"
    dest: "/path/to/dir"
  register: result
```

And parse `result.dest` to get version.
