### ISSUE TITLE
sns_topic: policy issue

### ISSUE THREAD

**Issue by mirakl577** [ansible/ansible-modules-extras#2298]
##### ISSUE TYPE
- Bug Report
##### COMPONENT NAME

  sns_topic
##### ANSIBLE VERSION

```
ansible 2.0.2.0
```
##### CONFIGURATION

Default
##### OS / ENVIRONMENT

N/A
##### SUMMARY

I tried to create SNS topic via sns_topic ansible module with described policy:
First case:
  policy:
        Version: "2008-10-17"
        Id: "{{ sns_policy.id }}"
        Statement:
          - Sid: "example-statement-ID"
            Effect: "Allow"
            Principal:
              AWS: "_"
            Action: "SNS:Publish"
            Resource: "arn:aws:sns:us-east-1:{{ sns_policy.account_id }}:{{ sns_name }}"
            Condition:
              ArnLike: {"aws:SourceArn": "arn:aws:s3:_:_:{{ s3_bucket_name }}"}
Second case:
  policy: "{{ lookup('template', 'sns_policy.json.j2') }}"
  sns_policy.json.j2:
      {
    "Version": "2008-10-17",
    "Id": "{{ sns_policy.id }}",
    "Statement": [
      {
        "Sid": "example-statement-ID",
        "Effect": "Allow",
        "Principal": {
          "AWS": "_"
        },
        "Action": "SNS:Publish",
        "Resource": "arn:aws:sns:us-east-1:{{ sns_policy.account_id }}:{{ sns_name }}",
        "Condition": {
          "Arnlike": {
            "aws:SourceArn": "arn:aws:s3:_:_:{{ s3_bucket_name }}"
          }
        }
      }
    ]
  }
##### STEPS TO REPRODUCE

```
tasks:
- name: Create alarm SNS topic
  sns_topic:
    name: "{{ sns_name }}"
    policy:
        Version: "2008-10-17"
        Id: "{{ sns_policy.id }}"
        Statement:
          - Sid: "example-statement-ID"
            Effect: "Allow"
            Principal:
              AWS: "*"
            Action: "SNS:Publish"
            Resource: "arn:aws:sns:us-east-1:{{ sns_policy.account_id }}:{{ sns_name }}"
            Condition:
              ArnLike: {"aws:SourceArn": "arn:aws:s3:*:*:{{ s3_bucket_name }}"}
    delivery_policy:
      http:
        defaultHealthyRetryPolicy:
            minDelayTarget: 20
            maxDelayTarget: 20
            numRetries: 3
            numMaxDelayRetries: 0
            backoffFunction: "linear"
        disableSubscriptionOverrides: True
        defaultThrottlePolicy:
            maxReceivesPerSecond: 10
    state: "{{ sns_state }}"
    display_name: "{{ sns_name }}"
    subscriptions: '{{ sns_subscriptions }}'
```
##### EXPECTED RESULTS

SNS Topic: created
Policy: created
DeliveryPolicy: created
Subscriptions: created
##### ACTUAL RESULTS

SNS Topic: created
Policy: Failed
DeliveryPolicy: created
Subscriptions: created

```
An exception occurred during task execution. The full traceback is:
Traceback (most recent call last):
  File "<stdin>", line 2519, in <module>
  File "<stdin>", line 256, in main
KeyError: 'policy'
```
