### ISSUE TITLE
Local docker registry + images failing to build

### ISSUE THREAD

**Issue by jordy25519** [ansible/ansible-modules-extras#2312]
##### ISSUE TYPE

- Bug Report
##### COMPONENT NAME

docker_image
##### ANSIBLE VERSION

```
ansible 2.1.0.0
  config file = /home/user/scratch/deployment/ansible/ansible.cfg
  configured module search path = Default w/o overrides
```
##### CONFIGURATION

N/A
##### OS / ENVIRONMENT

OS: N/A
docker-py 1.8.1
docker version

```
Client:
 Version:      1.11.1
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   5604cbe
 Built:        Tue Apr 26 23:30:23 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.11.1
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   5604cbe
 Built:        Tue Apr 26 23:30:23 2016
 OS/Arch:      linux/amd64
```
##### SUMMARY

When building a docker image locally Ansible fails to find a locally available base image specified in the  `FROM` directive of the dockerfile. 
Resulting Error:

```
fatal: [localhost]: FAILED! => {"changed": false, "failed": true, "msg": "Error building localhost:5000/image - code: None message: Error: image library/base_image not found"}
```

[See this similar issue with docker compose](https://github.com/docker/compose/issues/1568)
##### STEPS TO REPRODUCE

Create docker registry

```
-   name: Creating docker registry
    docker:
        name: registry
        image: "registry:2"
        state: started
        restart_policy: always
        ports:
            - "5000:5000"
        env:
            REGISTRY_STORAGE_FILESYSTEM_ROOTDIRECTORY: /var/lib/registry
        volumes:
            "{{host_registry_dir}}:/var/lib/registry"
```

Build, tag, push base image

```
-   name: Create base_image locally
    docker_image:
        name: "{{private_docker_registry}}/base_image"
        path: "{{build_folder}}/dockerfiles/base_image"
        dockerfile: base_image.Dockerfile
        tag: latest
```

Build,tag,push child image

```
-   name: Create image locally
    docker_image:
        name: "{{private_docker_registry}}/image"
        path: "{{build_folder}}/dockerfiles/image"
        dockerfile: image.Dockerfile
```

Simplified `image.Dockerfile` using the locally built base_image as its base:

```
FROM base_image

EXPOSE 5555

ENTRYPOINT ["./entrypoint.sh"]
```
##### EXPECTED RESULTS

docker image to be built, tagged, and pushed to the local registry.
##### ACTUAL RESULTS

The image failed to build as its base image could not be located.

Output:

```
fatal: [localhost]: FAILED! => {"changed": false, "failed": true, "msg": "Error building localhost:5000/image - code: None message: Error: image library/base_image not found"}
```

Setting `pull: no` seemed to resolve this. But there are two issues with this firstly it is confusing as the docs state 

> "When building an image downloads any updates to the FROM image in Dockerfile." 

and secondly executed unusually slow and produced another error:

```
fatal: [localhost]: FAILED! => {"changed": false, "failed": true, "msg": "Error: configuration for localhost:5000 not found. Try logging into localhost:5000 first."}
```
