### ISSUE TITLE
Slack - markdown when color defined

### ISSUE THREAD

**Issue by 45413** [ansible/ansible-modules-extras#2393]
##### ISSUE TYPE

- Bug Report
##### COMPONENT NAME

notification/slack.py
##### ANSIBLE VERSION

```
ansible 2.0.2.0
```
##### CONFIGURATION

N/A
##### OS / ENVIRONMENT

N/A
##### SUMMARY

When using slack notifications with the any color option besides normal causes markdown to not be respected in slack.
##### STEPS TO REPRODUCE

```
    - name: Send Notification
      local_action:
        module: slack
        token: token/from/slack
        msg: "Ansible note for *{{ inventory_hostname }}*"
        parse: 'full'
        link_names: 1
        channel: "#ansible"
        color: warning
```

##### EXPECTED RESULTS

I expect to see a message like

> Ansible note for - **hostname**

but instead see

> Ansible note for - *hostname*
##### ACTUAL RESULTS

```
ok: [localhost -> localhost] => {"changed": false, "invocation": {"module_args": {"attachments": null, "channel": "#ansible", "color": "warning", "domain": null, "icon_emoji": null, "icon_url": "http://www.ansible.com/favicon.ico", "link_names": 1, "msg": "Ansible not for - *localhost*", "parse": null, "token": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER", "username": "Ansible", "validate_certs": true}, "module_name": "slack"}, "msg": "OK"}
```
