### ISSUE TITLE
Win_FirewallRule does not work as intended

### ISSUE THREAD

**Issue by trondhindenes** [ansible/ansible-modules-extras#2424]
##### ISSUE TYPE
- Bug Report
##### COMPONENT NAME

win_firewall_rule
##### ANSIBLE VERSION

2.1.0
##### CONFIGURATION

Example playbook snippet:

``` yaml
    - name: Firewall rule for ES (9200)
      action: win_firewall_rule
      args:
          name: elasticsearch_9200
          enable: yes
          state: present
          localport: 9200
          action: allow
          direction: In
          protocol: TCP
```
##### OS / ENVIRONMENT

Target node: Windows 2012R2 w/powershell 4.0
##### SUMMARY

The module uses the `netsh advfirewall` command, however the options used are not valid. The above playbook results in the following string:
`netsh advfirewall firewall add rule action="allow" enable="yes" dir="In" name="elasticsearch_9300" profile="current" protocol="TCP" localport="9300"`. 
The "profile=current" is not allowed according to docs: [ profile = { public | private | domain | any | [ ,... ] } ]

Furthermore, the module does not seem to check the value of $LastExitCode, which results in false positives.
##### STEPS TO REPRODUCE

Execute the listed playbook on a target node with the listed OS. The module reports success, although no change is actually done on the server.
##### EXPECTED RESULTS

Either a successful change or an error
##### ACTUAL RESULTS

Module reports success even if it fails

```
```
