### ISSUE TITLE
the zabbix_host module won't link multiple templates.

### ISSUE THREAD

**Issue by kalloa** [ansible/ansible-modules-extras#2433]
##### ISSUE TYPE

- Bug Report
##### COMPONENT NAME

monitoring/zabbix_host.py
##### ANSIBLE VERSION

```
ansible 2.1.0.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
```
##### CONFIGURATION

```
- name: Create a new host or update an existing host's info
  local_action:
    module: zabbix_host
    server_url: "http://ubuntu2/zabbix"
    login_user: Admin
    login_password: zabbix
    host_name: ubuntu3
    host_groups: 
      - Linux Servers
    status: enabled
    state: present
    force: yes
    link_templates:
      - Template App Zabbix Agent
      - Template OS Linux
    inventory_mode: automatic
    interfaces:
      - type: 1
        main: 1
        useip: 0
        ip: 192.168.122.13
        dns: ubuntu3
        port: 10050
```
##### OS / ENVIRONMENT

ansible from OS: trusty, with zabbix-api installed.
ansible target OS: trusty
I've tested both with 2.4 and 3.0 zabbix versions.
##### SUMMARY

I am not able to link multiple templates with this module, with one template works well.
##### STEPS TO REPRODUCE

Create a role with a task like this (I used this role without it's "library" directory https://github.com/dj-wasabi/ansible-zabbix-agent):

```
- name: Create a new host or update an existing host's info
  local_action:
    module: zabbix_host
...
    link_templates:
      - Template App Zabbix Agent
      - Template OS Linux
    inventory_mode: automatic
...
```

The setting above mentioned isn't working, but with single template works well:

```
- name: Create a new host or update an existing host's info
  local_action:
    module: zabbix_host
...
    link_templates:
      - Template App Zabbix Agent
    inventory_mode: automatic
...
```

```

```

##### EXPECTED RESULTS

The host should be created with multiple template links.
##### ACTUAL RESULTS

```
TASK [ansible-zabbix-agent : Create a new host or update an existing host's info] ***
task path: /home/user/git/ansible-zabbix-agent/roles/ansible-zabbix-agent/tasks/main.yml:118
<localhost> ESTABLISH LOCAL CONNECTION FOR USER: user
<localhost> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo $HOME/.ansible/tmp/ansible-tmp-1465990158.6-117222479846934 `" && echo ansible-tmp-1465990158.6-117222479846934="` echo $HOME/.ansible/tmp/ansible-tmp-1465990158.6-117222479846934 `" ) && sleep 0'
<localhost> PUT /tmp/tmpArup6W TO /home/user/.ansible/tmp/ansible-tmp-1465990158.6-117222479846934/zabbix_host_updated
<localhost> EXEC /bin/sh -c 'sudo -H -S -n -u root /bin/sh -c '"'"'echo BECOME-SUCCESS-qenoluelmlflqthhcowtqvhtdgkszhuf; LANG=en_US.UTF-8 LC_ALL=en_US.UTF-8 LC_MESSAGES=en_US.UTF-8 /usr/bin/python /home/user/.ansible/tmp/ansible-tmp-1465990158.6-117222479846934/zabbix_host_updated; rm -rf "/home/user/.ansible/tmp/ansible-tmp-1465990158.6-117222479846934/" > /dev/null 2>&1'"'"' && sleep 0'
fatal: [ubuntu3 -> localhost]: FAILED! => {"changed": false, "failed": true, "invocation": {"module_args": {"force": true, "host_groups": ["Linux servers"], "host_name": "ubuntu3", "http_login_password": null, "http_login_user": null, "interfaces": [{"dns": "ubuntu3", "interfaceid": "10", "ip": "192.168.122.13", "main": 1, "port": 10050, "type": 1, "useip": 0}], "inventory_mode": "automatic", "link_templates": ["Template App Zabbix Agent", "Template OS Linux"], "login_password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER", "login_user": "Admin", "proxy": null, "server_url": "http://ubuntu2/********", "state": "present", "status": "enabled", "timeout": 10}, "module_name": "zabbix_host_updated"}, "msg": "Failed to link template to host: (u'Error -32602: Invalid params., Template cannot be linked to another template more than once even through other templates. while sending {\"params\": {\"templates\": [\"10001\", \"10050\"], \"hostid\": \"10113\", \"templates_clear\": []}, \"jsonrpc\": \"2.0\", \"method\": \"host.update\", \"auth\": \"3f511caf5a6dd04e0cb2a5a6d76c8880\", \"id\": 13}', -32602)"}
```
