### ISSUE TITLE
ecs_service module - Add support for deployment configuration

### ISSUE THREAD

**Issue by jqmtor** [ansible/ansible-modules-extras#2434]
##### ISSUE TYPE
- Feature Idea
##### COMPONENT NAME

`ecs_service` module
##### SUMMARY

The module does not support that a deployment configuration is provided. In particular, it does not allow to set the values for the minimum healthy percent and maximum percent.
##### DETAILS

For more information on this configuration, search for `--deployment-configuration` on [this AWS CLI documentation page](http://docs.aws.amazon.com/cli/latest/reference/ecs/create-service.html) or check the API reference for the explanation of the [DeploymentConfiguration](http://docs.aws.amazon.com/AmazonECS/latest/APIReference/API_DeploymentConfiguration.html) data structure.
##### EXPECTED RESULTS

Being able to create/update an ECS service with the following task:

```
- name: Configure ECS service for the web application
  ecs_service:
    name: test-service
    cluster: test-cluster
    task_definition: test-task-definition
    desired_count: 3
    deployment_configuration:
      minimum_healthy_percent: 75
      maximum_percent: 150
    state: present
```
##### ACTUAL RESULTS

The module currently assumes the default values for the deployment configuration (`minimumHealthyPercent = 100` and `maximumPercent = 200`).
