### ISSUE TITLE
win_regedit: change detection doesn't work for environment variables in registry keys of type expandstring

### ISSUE THREAD

**Issue by chrwen-omicron** [ansible/ansible-modules-extras#2446]
##### ISSUE TYPE

- Bug Report
##### COMPONENT NAME

win_regedit
##### ANSIBLE VERSION

```
ansible 2.1.0.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
```
##### SUMMARY

Setting an environment variable as data of an expandstring data type leads to a change every run.
##### STEPS TO REPRODUCE

```
- name: set an environment variable as data
  win_regedit:
    key: "HKCU:\\Environment"
    value: HOME
    data: "%USERPROFILE%"
    type: expandstring
```

##### EXPECTED RESULTS

No change if the registry contains `%USERPROFILE%.`
##### ACTUAL RESULTS

When win_regedit is reading the registry key, it gets the expanded data instead of the real data.
E.g. `C:\Users\<username>` instead of `%USERPROFILE%`
