### ISSUE TITLE
vmware extra module vmware_vm_facts.py output result

### ISSUE THREAD

**Issue by liam-lai** [ansible/ansible-modules-extras#2475]
##### ISSUE TYPE

- Documentation Report
##### COMPONENT NAME

ansible-modules-extras/cloud/vmware/vmware_vm_facts.py
##### ANSIBLE VERSION

```
ansible 2.1.0.0
```
##### CONFIGURATION

ANSIBLE_HOSTS=~/ansible/hostname/hosts
ANSIBLE_HOST_KEY_CHECKING=False
ANSIBLE_SSH_ARGS=''
ANSIBLE_TRANSPORT=ssh
ANSIBLE_SCP_IF_SSH=y
ANSIBLE_LIBRARY=~/ansible/modules/ansible-modules-extras
##### OS / ENVIRONMENT

Fedora release 22 (Twenty Two)
##### SUMMARY

Need more explain on how to get the facts from module output.

Suggest add completed example in doc.

```
- name: Gather all registered virtual machines
     local_action:
       module: vmware_vm_facts
       hostname: esxi_or_vcenter_ip_or_hostname
       username: username
       password: password
+  register : result
+ - debug : var=result
```
##### STEPS TO REPRODUCE

```
   tasks:
    - name: get all vmware_vm_facts
      vmware_vm_facts:
            hostname: "{{vcenter_hostname}}"
            username: "{{username}}"
            password: "{{password}}"
```

##### EXPECTED RESULTS

```

TASK [get all vmware_vm_facts] *************************************************
ok: [localhost]
"result": {
        "changed": false,
        "virtual_machines": {
            "vm01": {
                "guest_fullname": "Red Hat Enterprise Linux 7",
                "ip_address": "10.10.10.10",
                "power_state": "poweredOn"
          ...
          ...
            }
        }
    }
```
##### ACTUAL RESULTS

PLAY [Gather all registered virtual machines] **********************************

TASK [setup] *******************************************************************
ok: [localhost]

TASK [get all vmware_vm_facts] *************************************************
ok: [localhost]

```
```
