### ISSUE TITLE
win_regedit failing due to checking for registryValue default value

### ISSUE THREAD

**Issue by watsonb** [ansible/ansible-modules-extras#2495]
##### ISSUE TYPE
- Bug Report
##### COMPONENT NAME

win_regedit
##### ANSIBLE VERSION

ansible 2.1.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
##### CONFIGURATION

N/A --> pretty much "stock"/default values
##### OS / ENVIRONMENT

Ansible: RHEL 7.2 (Maipo)
Target: Windows Server 2012 R2
##### SUMMARY

Attempting to set Windows Registry key values.  This has worked in the past, but (perhaps with Ansible 1.9.x and 2.0.x), but seems to be failing now.
##### STEPS TO REPRODUCE

Try to set registry key values to set IE11's Protection Mode

```
#==========
# Set Zone 1 (Local Intranet Zone)
#==========
- name: WIN_REGEDIT | Set IE Zone 1 (Local Intranet Zone) Protection Mode (HKCU)
  win_regedit:
    key: 'HKCU:\SOFTWARE\Microsoft\Windows\CurrentVersion\Internet Settings\Zones\1'
    value: 2500
    data: "{{ie_zone_value}}"
    datatype: dword
  when: do_set_ie_zones_pm_hkcu and ansible_os_family == "Windows"
  tags:
    - setIEZonesPM
```

For the key, I have tried with and without single quotes due to a space in the key's path (FYI, this has worked in the past without single quotes even when the key's path had spaces)

For the data, this is an Ansible variable that will hold a single character: either 0, 1, or 3
##### EXPECTED RESULTS

I expect the value of 2500 at the key's path to be set to 0, and the datatype is a dword
##### ACTUAL RESULTS

```
TASK [protractor-tests : WIN_REGEDIT | Set IE Zone 1 (Local Intranet Zone) Protection Mode (HKCU)] ***
task path: /home/jenkins/repo/playbooks/roles/protractor-tests/tasks/main.yml:254
skipping: [sv2-int-integ-test-01] => {"changed": false, "skip_reason": "Conditional check failed", "skipped": true}
skipping: [sv2-int-integ-test-02] => {"changed": false, "skip_reason": "Conditional check failed", "skipped": true}
<172.16.62.63> ESTABLISH WINRM CONNECTION FOR USER: Jenkins on PORT 5986 TO 172.16.62.63
<172.16.62.62> ESTABLISH WINRM CONNECTION FOR USER: Jenkins on PORT 5986 TO 172.16.62.62
<172.16.62.63> EXEC Set-StrictMode -Version Latest
(New-Item -Type Directory -Path $env:temp -Name "ansible-tmp-1467127707.18-11037291361204").FullName | Write-Host -Separator '';
<172.16.62.62> EXEC Set-StrictMode -Version Latest
(New-Item -Type Directory -Path $env:temp -Name "ansible-tmp-1467127707.19-159967279778272").FullName | Write-Host -Separator '';
<172.16.62.63> PUT "/tmp/tmprU3ZVQ" TO "C:\Users\Jenkins\AppData\Local\Temp\ansible-tmp-1467127707.18-11037291361204\win_regedit.ps1"
<172.16.62.62> PUT "/tmp/tmp80CHE0" TO "C:\Users\Jenkins\AppData\Local\Temp\ansible-tmp-1467127707.19-159967279778272\win_regedit.ps1"
<172.16.62.62> EXEC Set-StrictMode -Version Latest
Try
{
& 'C:\Users\Jenkins\AppData\Local\Temp\ansible-tmp-1467127707.19-159967279778272\win_regedit.ps1'
}
Catch
{
$_obj = @{ failed = $true }
If ($_.Exception.GetType)
{
$_obj.Add('msg', $_.Exception.Message)
}
Else
{
$_obj.Add('msg', $_.ToString())
}
If ($_.InvocationInfo.PositionMessage)
{
$_obj.Add('exception', $_.InvocationInfo.PositionMessage)
}
ElseIf ($_.ScriptStackTrace)
{
$_obj.Add('exception', $_.ScriptStackTrace)
}
Try
{
$_obj.Add('error_record', ($_ | ConvertTo-Json | ConvertFrom-Json))
}
Catch
{
}
Echo $_obj | ConvertTo-Json -Compress -Depth 99
Exit 1
}
Finally { Remove-Item "C:\Users\Jenkins\AppData\Local\Temp\ansible-tmp-1467127707.19-159967279778272" -Force -Recurse -ErrorAction SilentlyContinue }
<172.16.62.63> EXEC Set-StrictMode -Version Latest
Try
{
& 'C:\Users\Jenkins\AppData\Local\Temp\ansible-tmp-1467127707.18-11037291361204\win_regedit.ps1'
}
Catch
{
$_obj = @{ failed = $true }
If ($_.Exception.GetType)
{
$_obj.Add('msg', $_.Exception.Message)
}
Else
{
$_obj.Add('msg', $_.ToString())
}
If ($_.InvocationInfo.PositionMessage)
{
$_obj.Add('exception', $_.InvocationInfo.PositionMessage)
}
ElseIf ($_.ScriptStackTrace)
{
$_obj.Add('exception', $_.ScriptStackTrace)
}
Try
{
$_obj.Add('error_record', ($_ | ConvertTo-Json | ConvertFrom-Json))
}
Catch
{
}
Echo $_obj | ConvertTo-Json -Compress -Depth 99
Exit 1
}
Finally { Remove-Item "C:\Users\Jenkins\AppData\Local\Temp\ansible-tmp-1467127707.18-11037291361204" -Force -Recurse -ErrorAction SilentlyContinue }
An exception occurred during task execution. The full traceback is:
At C:\Users\Jenkins\AppData\Local\Temp\ansible-tmp-1467127707.18-11037291361204\win_regedit.ps1:359 char:17
+             if ($registryValue.ToLower() -eq "(default)") {
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
fatal: [172.16.62.63]: FAILED! => {"changed": false, "failed": true, "invocation": {"module_name": "win_regedit"}, "msg": "Method invocation failed because [System.Int32] does not contain a method named 'ToLower'."}
An exception occurred during task execution. The full traceback is:
At C:\Users\Jenkins\AppData\Local\Temp\ansible-tmp-1467127707.19-159967279778272\win_regedit.ps1:359 char:17
+             if ($registryValue.ToLower() -eq "(default)") {
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
fatal: [172.16.62.62]: FAILED! => {"changed": false, "failed": true, "invocation": {"module_name": "win_regedit"}, "msg": "Method invocation failed because [System.Int32] does not contain a method named 'ToLower'."}
```

It would appear that efforts to make win_regedit idempotent via checking existing registry values (e.g. $registryValue.ToLower()) is breaking me here.

**Comment by watsonb** [comment]
After tinkering a bit, this may be a "special case".  The key's value of 2500 needs to be set to either 0, 1, or 3.  The datatype of the value is a dword.  However, as specified in the playbook, it appears that 2500 is being picked up as an integer, hence the fail on the call to ToLower().

I quoted the 2500, so the task now looks like this:

```
#==========
# Set Zone 1 (Local Intranet Zone)
#==========
- name: WIN_REGEDIT | Set IE Zone 1 (Local Intranet Zone) Protection Mode (HKCU)
  win_regedit:
    key: 'HKCU:\SOFTWARE\Microsoft\Windows\CurrentVersion\Internet Settings\Zones\1'
    value: "2500"
    data: "{{ie_zone_value}}"
    datatype: dword
  when: do_set_ie_zones_pm_hkcu and ansible_os_family == "Windows"
  tags:
    - setIEZonesPM
```

Now it appears to work without failing.  However, it reports the value as "changed" on each and every run of the task.  This improper status reporting isn't a big deal to me, as I'm not using it for any downward tasks triggers.
