### ISSUE TITLE
openvswitch_port module errors if port already present in bridge

### ISSUE THREAD

**Issue by scottslowe** [ansible/ansible-modules-extras#2500]
##### ISSUE TYPE

- Bug Report
##### COMPONENT NAME

openvswitch_port module
##### ANSIBLE VERSION

```
ansible 2.1.0.0
  config file = /Users/slowe/Public/Repos/learning-tools/ovs-multi-br/ansible.cfg
  configured module search path = Default w/o overrides
```
##### CONFIGURATION

Contents of `ansible.cfg` (being used in a Vagrant environment):

```
[defaults]
inventory = ./.vagrant/provisioners/ansible/inventory/vagrant_ansible_inventory
private_key_file = ~/.vagrant.d/insecure_private_key
remote_user = vagrant
host_key_checking = False
```

I've also tried without `ansible.cfg` at all, just using default values.
##### OS / ENVIRONMENT

Guest VM is running Ubuntu 14.04 (kernel version 3.16.0-30-generic), Python version 2.7.6. Ansible modules are being executed on this guest VM. OVS 2.0.2 (from the Trusty repos) is installed.

Host system is OS X 10.11.2 (Ansible 2.1.0.0 is installed here). I'm using Vagrant 1.8.1 and VMware Fusion 8.1.0.
##### SUMMARY

I have an Ansible playbook that attempts to ensure physical interfaces are added to an OVS bridge using the openvswitch_port extras module. On first run, the playbook succeeds; on subsequent runs, it returns an error when attempting to add the port. If I manually remove the port and re-run the playbook, it will succeed again.
##### STEPS TO REPRODUCE

Here are the OVS-related portions of the playbook I'm using:

```
  - name: "Create OVS bridges"
    openvswitch_bridge:
      bridge: "{{ item }}"
      state: "present"
    with_items:
      - "br0"
      - "br1"

  - name: "Configure OVS bridge br0"
    openvswitch_port:
      bridge: "br0"
      port: "eth1"
      state: "present"

  - name: "Configure OVS bridge br1"
    openvswitch_port:
      bridge: "br1"
      port: "eth2"
      state: "present"
```

The openvswitch_bridge task works fine (creates bridge if not present, otherwise no action), but the openvswitch_port tasks fail if the port is already part of the specified bridge. If I manually remove the ports from the bridge, the playbook will succeed. If you run the playbook with the ports already in the bridge, it will error out.

##### EXPECTED RESULTS

I expected idempotent behavior from the openvswitch_port module (add ports if not already present, otherwise no action).
##### ACTUAL RESULTS

The playbook ends with an error when trying to add ports to the bridge. Here is the output of `ansible-playbook` for the OVS-related tasks:

```
TASK [Create OVS bridges] ******************************************************
ok: [hv-01] => (item=br0)
ok: [hv-01] => (item=br1)

TASK [Configure OVS bridge br0] ************************************************
fatal: [hv-01]: FAILED! => {"changed": false, "failed": true, "msg": "'str' object has no attribute 'items'"}
```

If I manually remove the ports from the bridge (or if this is the first time the playbook is running and therefore the ports are not already in the bridge), the playbook works:

```
TASK [Create OVS bridges] ******************************************************
ok: [hv-01] => (item=br0)
ok: [hv-01] => (item=br1)

TASK [Configure OVS bridge br0] ************************************************
changed: [hv-01]

TASK [Configure OVS bridge br1] ************************************************
changed: [hv-01]
```

I've tried running the playbook both via Vagrant (using the Ansible provisioner in Vagrant) as well as via standalone invocation of `ansible-playbook`. The behaviors are identical in both cases.
