### ISSUE TITLE
known_hosts module changes ownership of existing file

### ISSUE THREAD

**Issue by Rthur** [ansible/ansible-modules-extras#2513]
##### ISSUE TYPE
- Bug Report
##### ANSIBLE VERSION

```
ansible 2.0.1.0
  config file = /etc/ansible/ansible.cfg
```
##### OS / ENVIRONMENT

CentOS Linux release 7.2.1511 (Core)
##### SUMMARY

If known_hosts replaces an existing entry with a new key, the module changes the ownership of the file to root.
##### STEPS TO REPRODUCE

These plays replace the known_host when a system is rebuilt, so that man-in-the-middle warnings are properly addressed:

```
- name: get localhost pubkey
  shell: cat /etc/ssh/ssh_host_rsa_key.pub
  register: local_key
  changed_when: false

- name: add pubkey to ansible@ known_hosts
  known_hosts:
    path: '/home/ansible/.ssh/known_hosts'
    name: '{{ inventory_hostname }}'
    key: '{{ inventory_hostname }},{{ some_ip_address }} {{ local_key.stdout }}'
  delegate_to: localhost
```
##### EXPECTED RESULTS

Key changes if different. File ownership do not change.
##### ACTUAL RESULTS

Key is successfully changed in known_hosts, but file ownership also change

```
$ sudo ls -alh /home/ansible/.ssh/known_hosts
-rw------- 1 root root 45K Jul  1 14:14 /home/ansible/.ssh/known_hosts
$
```
##### WORKAROUND

add become and become_user to play to match owner of the known_hosts file

```
- name: add pubkey to ansible@ known_hosts
  known_hosts:
    path: '/home/ansible/.ssh/known_hosts'
    name: '{{ inventory_hostname }}'
    key: '{{ inventory_hostname }},{{ some_ip_address }} {{ local_key.stdout }}'
  become: yes
  become_user: ansible
  delegate_to: localhost
  tags: ssh_keys
```
