### ISSUE TITLE
Brew install when package name contains "/"

### ISSUE THREAD

**Issue by kdisneur** [ansible/ansible-modules-extras#252]
I tried to install `cask` with `ansible` and I have the following errors: `msg: Invalid package: caskroom/cask/brew-cask.`

It's because there is some slashes in the name and, in the ansible task, the `/` seems to not be allowed. I tried to add the slash in the `VALID_PACKAGE_CHARS` constant, it works like a charm.

I've not opened a pull request yet, because I would like to have your feedback before: there is a reason the slash was not allowed in the regex or is it just an oversight?

Cheers,

**Comment by tobywf** [comment]
I've also hit this issue. `homebrew_tap` does provide a workaround in some cases, but it's not ideal. This sounds similar to ansible/ansible#7991 and ansible/ansible#8413 where "+" and "." where left out of the filter.

Edit: `VALID_PACKAGE_CHARS` isn't the only change. The module calls `brew outdated` and then checks the complete output, but this only outputs short names (`caskroom/cask/brew-cask` -> `brew-cask`). `brew outdated <package>` accepts full names and returns a non-zero return code if `<package>` needs updating, which is probably simpler in the long run. So the methods `_current_package_is_outdated`  and `_outdated_packages` need changing, I'll prepare a PR this week.

**Comment by kdisneur** [comment]
@tobywf Nope. I am sorry but I've no longer a PullRequest ready for this one and I think I will not have time to work on it this week. 
If you don't have time this week, I can take a look at this issue next week I guess. But feel free to create one if you have time before. :)

**Comment by tresni** [comment]
To add to this, I have a custom Forumla that I use hosted in a gist.
`brew install --HEAD https://gist.githubusercontent.com/tresni/0abf5c8017b082d4717a/raw/superspark.rb` is a completely acceptable command and works.  But I can't do:

``` yaml
homebrew:
        name: https://gist.githubusercontent.com/tresni/0abf5c8017b082d4717a/raw/superspark.rb
        state: head
```

Fails with the "Invalid package".  Adding `:` & `/` allows it to work.

**Comment by tobywf** [comment]
@tresni: Interesting, I'll have a look at that in the morning, try and get it incorporated into the PR I've prepared. I'm thinking there isn't much point in "validating" the package name at all, since brew will do that for us anyway? Interestingly enough, the URI works with `brew outdated`, so keeping the action idempotent should be no problem:

``` bash
$ brew outdated https://gist.githubusercontent.com/tresni/0abf5c8017b082d4717a/raw/superspark.rb
######################################################################## 100.0%
Error: No such file or directory - /usr/local/Cellar/superspark
$ echo $?
1
$ brew install --HEAD https://gist.githubusercontent.com/tresni/0abf5c8017b082d4717a/raw/superspark.rb
[...]
$ brew outdated https://gist.githubusercontent.com/tresni/0abf5c8017b082d4717a/raw/superspark.rb
######################################################################## 100.0%
$ echo $?
0
```

**Comment by glennr** [comment]
+1. Also getting the same error with; 

```
  failed: [localhost] => (item=homebrew/dupes/grep) => {"failed": true, "item": "homebrew/dupes/grep"}
  msg: Invalid package: homebrew/dupes/grep.
```

**Comment by tobywf** [comment]
Sorry, bit of a delay.  My pull request is for the colons and using `brew outdated <forumula>` instead of parsing the output of `brew outdated`.

@enriclluelles fixed the slash issue in #542 way back in May. It doesn't seem to be in a stable release yet though, so @glennr, I suspect that's what you're seeing.You might try an install from source until the fix is in a stable release.

**Comment by JPry** [comment]
@tobywf @glennr I tried an install from source, and still got the same problem. However, I found that the homebrew packages from taps can be specified without the full tap name. Here's a sample playbook (and vars) that is working for me:

(defaults/main.yml -- vars)

``` yaml
brew_taps:
  - bradp/vv
  - homebrew/dupes
  - homebrew/php
brew_install:
  - git
  - hub
  - vcprompt
  - ansible
  - automake
  - bash
  - bash-completion
  - box
  - byobu
  - dpkg
  - libtool
  - node
  - phpunit
  - python3
  - rbenv
  - ruby-build
  - wget
  - zsh

  # Taps
  - php55
  - php55-memcached
  - php55-xdebug
  - composer
  - vv
```

(tasks/homebrew.yml)

``` yaml
---
# Tasks related to installing homebrew

- name: Ensure Homebrew is installed
  shell: ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
  args:
    creates: /usr/local/Cellar
    executable: /bin/bash

- name: Install Homebrew taps
  homebrew_tap: tap={{ item }} state=present
  with_items: "{{ brew_taps }}"

- name: Install Homebrew formulae
  homebrew: name={{ item }} state=present
  with_items: "{{ brew_install }}"
```

Until the slash fix is added to a stable release, you _may_ be able to get away with not using the full tapped path.

**Comment by gregdek** [comment]
Ping @indrajitr for your feedback.

**Comment by indrajitr** [comment]
#542 and #732 should resolve the issue. The following worked as expected on ansible 2.0.0 (devel 10a4a4e986) on a freshly installed OS X.

``` yaml
- name: Install Homebrew formulae
  homebrew: name={{ item }} state=present
  # Note: 'run_command' would not have '/usr/local/bin' in PATH.
  # Adjust PATH appropriately to ensure 'brew tap' finds 'git'
  # in path in older version of OS X (probable 10.8 and below).
  environment:
    PATH: "{{ ansible_env.PATH }}:/usr/local/bin"
  with_items:
    - 'lesspipe'
    - 'homebrew/dupes/less'
    - 'caskroom/cask/brew-cask'
```

Note: Homebrew automatically `tap`s a repo as necessary. However, it expects `git` to be available in the path. This would be an issue with older version of OS X (I think 10.8 and below) or if you don't have XCode command line developer tool installed. Adjust `PATH` environment at task level to ensure `git` becomes available in `PATH`.

This can be closed once #732 is merged.
