### ISSUE TITLE
ec2_elb_facts module can't use

### ISSUE THREAD

**Issue by shencan** [ansible/ansible-modules-extras#2543]
##### ISSUE TYPE
- Bug Report
##### COMPONENT NAME

ec2_elb_facts.py
##### ANSIBLE VERSION

```
ansible 2.0.1.0
```
##### OS / ENVIRONMENT

CentOS 6.5
##### SUMMARY

ec2_elb_facts module can't  get elb information
##### STEPS TO REPRODUCE

```
 - name: test
   hosts: 127.0.0.1
   gather_facts: False
   become: yes
   tasks:
     - name: get elb facts
       local_action: ec2_elb_facts region='eu-west-1' name='test' aws_access_key='xxxxx'  aws_secret_key='yyyy'
       register: elb_facts
     - name: debug
       local_action: debug msg="{{ elb_facts }}"
```

##### ACTUAL RESULTS

```
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: ValueError: invalid literal for int() with base 10: '80/api?url=http%3A%2F%2Fwww.shencan.net'
fatal: [localhost -> localhost]: FAILED! => {"changed": false, "failed": true, "parsed": false}
```
