### ISSUE TITLE
Jira modules failes with "dictionary update sequence element #0 has length 1; 2 is required" in Ansible 2.0.2.0

### ISSUE THREAD

**Issue by tuabache** [ansible/ansible-modules-extras#2600]
##### ISSUE TYPE

Bug Report
##### COMPONENT NAME

Jira
##### ANSIBLE VERSION

```
ansible 2.1.0.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
```
##### SUMMARY

Using the jira module with Ansible 2.1.0.0 results in the following error message:

```
dictionary update sequence element #0 has length 1; 2 is required
```

Playbooks worked with Ansible 2.0.2.0
##### STEPS TO REPRODUCE

```
- hosts: xxxx

  tasks:
  - name: (JIRA) Sample ansible issue
    jira: description=something issuetype=Bug operation=create password=XXXX project=xxx summary=test uri=https://hostname.com username=XXX
```

##### ACTUAL RESULTS

```

```

**Comment by ansibot** [comment]
@tarka ping, this issue is waiting for your response.
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by sradvan** [comment]
Hi, I have the same problem. I would love to see this fixed! Thank you,

**Comment by ansibot** [comment]
@tarka, ping. This issue is still waiting on your response.
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibot** [comment]
@tarka, ping. This issue is still waiting on your response.
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by jhawkesworth** [comment]
@tuabache For what it's worth, I had to change the syntax to yaml style key: value instead of the key=value pair syntax following migration to ansble 2.x - please could you try changing your playbook syntax too?

**Comment by mohclips** [comment]
Proposed Fix:

change

`# Merge in any additional or overridden fields
    if params['fields']:
        createfields.update(params['fields'])
`

to

`# Merge in any additional or overridden fields
    if params['fields']:
        createfields.update(ast.literal_eval(params['fields']))
`

You also need to `import ast`

It's something to do with params['fields'] being a string and needs to be a python dict.

Tested and working on:
- ansible 2.1.1.0
- Python 2.6.6

Test case:

```
  - name: "Create a task"
    jira:
      uri: "{{server}}"
      username: "{{user}}"
      password: "{{pass}}"
      project: "{{project}}"
      operation: "create"
      summary: "Ansible Example Issue"
      description: "Created using Ansible"
      issuetype: "Task"
      fields:
        labels:
          - "autocreated"
          - "ansible"
          - "yaml"
        components:
          - name: "Linux Server"
          - name: "Linux Desktop"
        priority:
          name: "Trivial"
        fixVersions:
          - name: "rhel6.7-1.0"
          - name: "rhel7.2-1.0"

```
