### ISSUE TITLE
F5 LTM Error: ansible requires the stdlib json or simplejson module, neither was found

### ISSUE THREAD

**Issue by carterfields** [ansible/ansible-modules-extras#2602]
#### Issue Type:
- Bug Report
#### Component Name:

bigip_facts
#### Summary:

@mhite 
@caphrim007

I can't seem to get Ansible to talk to my F5 (BIG-IP 11.6.0 Build 6.0.442 Hotfix HF6).  I get: `error fatal: [f5ltm1.mydomain.com]: FAILED! => {"changed": false, "failed": true, "msg": "Error: ansible requires the stdlib json or simplejson module, neither was found!"}`

```

    ansible@ansible:~$ python -V
    Python 2.7.12
    ansible@ansible:~$ pip list | grep json
    simple-json (1.1)
    simplejson (3.3.1)
    ansible@ansible:~$ pip list | grep bigsuds
    bigsuds (1.0.4)
    ansible@ansible:~$ ansible --version
    ansible 2.1.0.0
      config file = /etc/ansible/ansible.cfg
      configured module search path = Default w/o overrides
```

I've tried two variations on the pb:

```
 ---
    # file bigip-test.yml
    # ...
    - hosts: loadbalancers
      tasks:
        - name: "Collect BIG-IP facts"
          bigip_facts:
            include: "interface,vlan"
            password: ansible
            server: f5ltm1.mydomain.com
            user: ansible
          delegate_to: localhost
```

and

```

---
    # file bigip-test.yml
    # ...
    - hosts: loadbalancers
      tasks:
      - name: Collect BIG-IP facts
        local_action: >
          bigip_facts
          server=f5ltm1.mydomain.com
          user=ansible
          password=ansible
          include=interface,vlan
```

YAML syntax has been validated locally, please ignore any issues here with syntax 

/etc/ansible/hosts:

```
    [loadbalancers]
    f5ltm1.mydomain.com
```

SSH & Ping to the LTM are also fine.

If anyone has had a similar problem and found a solution, please let me know.
