### ISSUE TITLE
Full service url for consul health checking

### ISSUE THREAD

**Issue by galkinrost** [ansible/ansible-modules-extras#2608]
##### ISSUE TYPE
- Feature Idea
##### COMPONENT NAME

consul
##### ANSIBLE VERSION

```
ansible 2.1.1.0
  config file = 
  configured module search path = Default w/o overrides
```
##### SUMMARY

When we register health checking with a path in the `http` option, e.g. `http: /ping`, consul fails with message `Get /ping: unsupported protocol scheme ""`. But if we set full url `http: http://{{service_address}}:{{service_port}}/ping` it`s ok. How about building a full service url before registering?

**Comment by alikins** [comment]
Could you provide a sample playbook that would use this feature?

The doc examples at http://docs.ansible.com/ansible/consul_module.html look like

```
- name: register nginx with an http check
  consul:
    name: nginx
    service_port: 80
    interval: 60s
    http: /status
```

Should work (if not, that's a bug in docs or code...)

EDIT: needs_info
