### ISSUE TITLE
Yum module is very slow

### ISSUE THREAD

**Issue by gadelkareem** [ansible/ansible-modules-extras#2615]
##### ISSUE TYPE
- Bug Report
##### COMPONENT NAME

yum module
##### ANSIBLE VERSION

```
> ansible --version
ansible 2.1.0.0
  config file = 
  configured module search path = Default w/o overrides
```
##### CONFIGURATION

Vagrant box "centos/7" with vagrant-vbguest plugin

```
config.vm.synced_folder ".", "/var/www/application", :nfs => { group: "vagrant", owner: "vagrant" }, :mount_options => ['nolock,vers=3,udp,noatime']
```
##### OS / ENVIRONMENT

CentOS 7
##### SUMMARY

Yum module slows down or hangs when provisioning vagrant.
##### STEPS TO REPRODUCE

```
- set_fact:
      common_libs:
          - curl
          - wget
          - ntp
          - ntpdate
      env_libs:
          - git-core      

- name: Update Yum
  yum: name=* state=latest

- name: install common packages
  yum: name={{ item }} state=latest update_cache=yes
  with_flattened:
    - "{{common_libs}}"
    - "{{env_libs}}"
```
##### EXPECTED RESULTS

Takes less than 1 min to complete on cli or using the command module

```
- set_fact:
      common_libs:
          - curl
          - wget
          - ntp
          - ntpdate
      env_libs:
          - git-core      

- name: Update Yum
  command: yum update -y

- name: install common packages
  command: yum install -y {{ item }} && yum clean all
  with_flattened:
    - "{{common_libs}}"
    - "{{env_libs}}"
```
##### ACTUAL RESULTS

Takes forever

```
TASK [common : Update Yum] *****************************************************
task path: /Users/Gadelkareem/ansible/roles/common/tasks/main.yml:3
<192.168.30.30> ESTABLISH SSH CONNECTION FOR USER: vagrant
<192.168.30.30> SSH: EXEC ssh -C -vvv -o UserKnownHostsFile=/dev/null -o IdentitiesOnly=yes -i /Users/Gadelkareem/.vagrant.d/insecure_private_key -o ForwardAgent=yes -o ControlMaster=auto -o ControlPersist=60s -o StrictHostKeyChecking=no -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o User=vagrant -o ConnectTimeout=30 -o ControlPath=/Users/Gadelkareem/.ansible/cp/ansible-ssh-%h-%p-%r 192.168.30.30 '/bin/sh -c '"'"'( umask 77 && mkdir -p "` echo $HOME/.ansible/tmp/ansible-tmp-1469176432.55-163006202630710 `" && echo ansible-tmp-1469176432.55-163006202630710="` echo $HOME/.ansible/tmp/ansible-tmp-1469176432.55-163006202630710 `" ) && sleep 0'"'"''
<192.168.30.30> PUT /var/folders/xl/4pst_jzn4tzd96mv1cr9ddvw0000gn/T/tmpKhxOp5 TO /home/vagrant/.ansible/tmp/ansible-tmp-1469176432.55-163006202630710/yum
<192.168.30.30> SSH: EXEC sftp -b - -C -vvv -o UserKnownHostsFile=/dev/null -o IdentitiesOnly=yes -i /Users/Gadelkareem/.vagrant.d/insecure_private_key -o ForwardAgent=yes -o ControlMaster=auto -o ControlPersist=60s -o StrictHostKeyChecking=no -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o User=vagrant -o ConnectTimeout=30 -o ControlPath=/Users/Gadelkareem/.ansible/cp/ansible-ssh-%h-%p-%r '[192.168.30.30]'
<192.168.30.30> ESTABLISH SSH CONNECTION FOR USER: vagrant
<192.168.30.30> SSH: EXEC ssh -C -vvv -o UserKnownHostsFile=/dev/null -o IdentitiesOnly=yes -i /Users/Gadelkareem/.vagrant.d/insecure_private_key -o ForwardAgent=yes -o ControlMaster=auto -o ControlPersist=60s -o StrictHostKeyChecking=no -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o User=vagrant -o ConnectTimeout=30 -o ControlPath=/Users/Gadelkareem/.ansible/cp/ansible-ssh-%h-%p-%r -tt 192.168.30.30 '/bin/sh -c '"'"'sudo -H -S -n -u root /bin/sh -c '"'"'"'"'"'"'"'"'echo BECOME-SUCCESS-ckqepejvhdjmvhzefnwalnzfaihghivx; LANG=en_US.UTF-8 LC_ALL=en_US.UTF-8 LC_MESSAGES=en_US.UTF-8 /usr/bin/python /home/vagrant/.ansible/tmp/ansible-tmp-1469176432.55-163006202630710/yum; rm -rf "/home/vagrant/.ansible/tmp/ansible-tmp-1469176432.55-163006202630710/" > /dev/null 2>&1'"'"'"'"'"'"'"'"' && sleep 0'"'"''
changed: [vagrant] => {"changed": true, "invocation": {"module_args": {"conf_file": null, "disable_gpg_check": false, "disablerepo": null, "enablerepo": null, "exclude": null, "install_repoquery": true, "list": null, "name": ["*"], "state": "latest", "update_cache": false, "validate_certs": true}, "module_name": "yum"}, "msg": "", "rc": 0, "results": ["Loaded plugins: fastestmirror\nLoading mirror speeds from cached hostfile\n * base: centos.mirror1.spango.com\n * extras: nl.mirror.babylon.network\n * updates: centos.mirror1.spango.com\nResolving Dependencies\n--> Running transaction check\n---> Package tzdata.noarch 0:2016e-1.el7 will be updated\n---> Package tzdata.noarch 0:2016f-1.el7 will be an update\n--> Finished Dependency Resolution\n\nDependencies Resolved\n\n================================================================================\n Package         Arch            Version                 Repository        Size\n================================================================================\nUpdating:\n tzdata          noarch          2016f-1.el7             updates          439 k\n\nTransaction Summary\n================================================================================\nUpgrade  1 Package\n\nTotal download size: 439 k\nDownloading packages:\nRunning transaction check\nRunning transaction test\nTransaction test succeeded\nRunning transaction\n  Updating   : tzdata-2016f-1.el7.noarch                                    1/2 \n  Cleanup    : tzdata-2016e-1.el7.noarch                                    2/2 \n  Verifying  : tzdata-2016f-1.el7.noarch                                    1/2 \n  Verifying  : tzdata-2016e-1.el7.noarch                                    2/2 \n\nUpdated:\n  tzdata.noarch 0:2016f-1.el7                                                   \n\nComplete!\n"]}

TASK [common : install common packages] ****************************************
task path: /Users/Gadelkareem/ansible/roles/common/tasks/main.yml:7
<192.168.30.30> ESTABLISH SSH CONNECTION FOR USER: vagrant
<192.168.30.30> SSH: EXEC ssh -C -vvv -o UserKnownHostsFile=/dev/null -o IdentitiesOnly=yes -i /Users/Gadelkareem/.vagrant.d/insecure_private_key -o ForwardAgent=yes -o ControlMaster=auto -o ControlPersist=60s -o StrictHostKeyChecking=no -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o User=vagrant -o ConnectTimeout=30 -o ControlPath=/Users/Gadelkareem/.ansible/cp/ansible-ssh-%h-%p-%r 192.168.30.30 '/bin/sh -c '"'"'( umask 77 && mkdir -p "` echo $HOME/.ansible/tmp/ansible-tmp-1469176435.05-181802808481713 `" && echo ansible-tmp-1469176435.05-181802808481713="` echo $HOME/.ansible/tmp/ansible-tmp-1469176435.05-181802808481713 `" ) && sleep 0'"'"''
<192.168.30.30> PUT /var/folders/xl/4pst_jzn4tzd96mv1cr9ddvw0000gn/T/tmpwheH8G TO /home/vagrant/.ansible/tmp/ansible-tmp-1469176435.05-181802808481713/yum
<192.168.30.30> SSH: EXEC sftp -b - -C -vvv -o UserKnownHostsFile=/dev/null -o IdentitiesOnly=yes -i /Users/Gadelkareem/.vagrant.d/insecure_private_key -o ForwardAgent=yes -o ControlMaster=auto -o ControlPersist=60s -o StrictHostKeyChecking=no -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o User=vagrant -o ConnectTimeout=30 -o ControlPath=/Users/Gadelkareem/.ansible/cp/ansible-ssh-%h-%p-%r '[192.168.30.30]'
<192.168.30.30> ESTABLISH SSH CONNECTION FOR USER: vagrant
<192.168.30.30> SSH: EXEC ssh -C -vvv -o UserKnownHostsFile=/dev/null -o IdentitiesOnly=yes -i /Users/Gadelkareem/.vagrant.d/insecure_private_key -o ForwardAgent=yes -o ControlMaster=auto -o ControlPersist=60s -o StrictHostKeyChecking=no -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o User=vagrant -o ConnectTimeout=30 -o ControlPath=/Users/Gadelkareem/.ansible/cp/ansible-ssh-%h-%p-%r -tt 192.168.30.30 '/bin/sh -c '"'"'sudo -H -S -n -u root /bin/sh -c '"'"'"'"'"'"'"'"'echo BECOME-SUCCESS-gfjgvmccefiqojyatypodtcammnimyex; LANG=en_US.UTF-8 LC_ALL=en_US.UTF-8 LC_MESSAGES=en_US.UTF-8 /usr/bin/python /home/vagrant/.ansible/tmp/ansible-tmp-1469176435.05-181802808481713/yum; rm -rf "/home/vagrant/.ansible/tmp/ansible-tmp-1469176435.05-181802808481713/" > /dev/null 2>&1'"'"'"'"'"'"'"'"' && sleep 0'"'"''
```

**Comment by alikins** [comment]
> Takes forever

Rough approximation of forever? 2min? 10min? a day?

**Comment by gadelkareem** [comment]
I think the max I left it running was over 30 min. I also tried it with_items and got the same problem.

**Comment by archonik** [comment]
@gadelkareem Try using with state=present instead of state=latest otherwise it really takes forever on slower internet connection. Also with state=latest the network usage is really high (it can generate 200MiB/s traffic)

Or just use enablerepo or disablerepo for specific repos only with state=latest

**Comment by gadelkareem** [comment]
I don't think it is a connection problem the command slows down only with the yum module.

**Comment by rquadling** [comment]
I'm having the same issue.

In trying to do things by hand, I found that `--disableplugin=fastestmirror` worked for me.

I'm a novice at this and I don't know how to have that parameter mixed into my scripts/process.

**Comment by rquadling** [comment]
As an indicator, running `yum install -y --enable-repo=remi-php70 php-pdo-dblib` takes around 5 minutes to get from `'Loading mirror speeds from cached hostfile'` to the next line.

Whereas with `yum install -y --enable-repo=remi-php70 php-pdo-dblib --disableplugin=fastestmirror` is as fast as near instant.

**Comment by rquadling** [comment]
The thing I can't find in the code base I'm working on is a shell command to run yum. Instead it is like this

``` yml
---
- name: Install php-fpm and deps
  yum: name={{ item }} state=present
  with_items:
    - php-bcmath
    - php-cli
    - php-common
    - php-dba
    - php-fpm
    - php-gd
    - php-mbstring
    - php-mcrypt
    - php-mysqlnd
    - php-opcache
    - php-pdo
    - php-pecl-imagick
    - php-pecl-zip
    - php-php-gettext
    - php-process
    - php-soap
    - php-tcpdf-dejavu-sans-fonts
    - php-tcpdf
    - php-tidy
    - php-xml
  register: phpfpm_installed
```
