### ISSUE TITLE
Add proxied support to CloudFlare

### ISSUE THREAD

**Issue by samhamilton** [ansible/ansible-modules-extras#2617]
##### ISSUE TYPE
- Feature Idea
##### COMPONENT NAME

cloudflare_dns.py
##### ANSIBLE VERSION

```
ansible 2.1.0.0
  config file =
  configured module search path = Default w/o overrides
```
##### CONFIGURATION

N/A
##### OS / ENVIRONMENT

N/A
##### SUMMARY

I would be really great if you can add support for the CloudFlare "proxied" flag, so that you can set true/false flag on creation and/or update of records
##### STEPS TO REPRODUCE

```
- name: "Create @ A Record 1"
  cloudflare_dns:
    zone: example.com
    type: A
    value: 10.10.10.10
    proxied: true
    account_email: "{{ cloudflare_email }}"
    account_api_token: "{{ cloudflare_api_token }}"
  register: record
```
##### EXPECTED RESULTS

This would turn on CloudFlare's DNS/HTTP proxy 
##### ACTUAL RESULTS

```
ok: [localhost] => {"changed": false, "invocation": {"module_args": {"account_api_token": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER", "account_email": "sam@madjungle.com", "port": null, "priority": 1, "proto": null, "record": "@", "service": null, "solo": null, "state": "present", "timeout": 30, "ttl": 1, "type": "A", "value": "10.10.10.10", "weight": 1, "zone": "example.com"}, "module_name": "cloudflare_dns"}, "result": {"record": {"content": "10.10.10.10", "created_on": "2016-07-18T11:10:09.100198Z", "id": "1234567890", "locked": false, "meta": {"auto_added": false}, "modified_on": "2016-07-18T11:10:09.100198Z", "name": "example.com", "proxiable": true, "proxied": true, "ttl": 1, "type": "A", "zone_id": "1234567890", "zone_name": "example.com"}}}
```
