### ISSUE TITLE
Support lists of packages in pacman module

### ISSUE THREAD

**Issue by kampka** [ansible/ansible-modules-extras#262]
Just like the apt and yum module, it would be nice of the pacman module would accept a yaml list of names in addition to a comma separated string.

Example:

```
pacman:
  name:
    - python
    - python2
    - ansible
    - someCoolPackage
  state: present
```

The simple reason is that a yaml list of is easier to read and especially easier to diff in source control that a long, comma separated string.

**Comment by dirtyharrycallahan** [comment]
I do not know how pacman works but you may want to look here:
 ansible/lib/ansible/runner/**init**.py

**Comment by newportd** [comment]
Are you able to use the with_items construct to accomplish this?

``` yaml
pacman: name={{ item }} state=present
with_items:
  - python
  - python2
  - ansible
  - someCoolPackage
```
