### ISSUE TITLE
Win_firewall is not working with ansible  2.0.0.2

### ISSUE THREAD

**Issue by badial** [ansible/ansible-modules-extras#2624]
##### ISSUE TYPE

- Bug Report
##### COMPONENT NAME

win_firewall_rule
##### ANSIBLE VERSION

```
ansible 2.0.0.2
```
##### SUMMARY

Win_firewall is not working with ansible 2.0.0.2
##### ACTUAL RESULTS

```

An exception occurred during task execution. To see the full traceback, use -vvv. The error was: + ~~~~~~~~~~~~~~~~~~~~~~~
fatal: [52.77.237.246]: FAILED! => {"changed": false, "failed": true, "msg": "The property 'failed' cannot be found on this object. Verify that the property exists."}                                                                              


```

**Comment by ansibot** [comment]
@TimothyVandenbrande ping, this issue is waiting for your response.
[click here for bot help](https://github.com/jctanner/ansibullbot/blob/ISSUE_TRIAGE_CLASS/ISSUE_HELP.md)

**Comment by t-v** [comment]
I believe this issue has also been resolved_by_pr #2432
Otherwise, for extra testing, could you give me the task you were trying to run?
needs_info

**Comment by trondhindenes** [comment]
I'm also seeing an issue with the current version of this module. 
I'm getting an error that the property "service" doesn't exist on the object. This seems related to the parsed output of netsh advfirewall, where there is no property called "service", while the compare object has this (set to any, which is coming from the parsed ansible module input). Can be tested with:

```
- name: Firewall rule for logstash IIS (6001)
  action: win_firewall_rule
  args:
      name: Logstash_6001
      enable: yes
      state: present
      localport: 6001
      action: allow
      direction: In
      protocol: TCP
      profile: any
      force: True
  notify: restart logstash-iis
```

In my case, it fails when the rule already exists.
