### ISSUE TITLE
Using win_regedit with DWORD values always results in "changed" state

### ISSUE THREAD

**Issue by refinedcranberry** [ansible/ansible-modules-extras#2663]
##### ISSUE TYPE

- Bug Report
##### COMPONENT NAME

win_regedit
##### ANSIBLE VERSION

```
ansible 2.1.0.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
```
##### SUMMARY

using win_regedit with dword values always results in "changed" state
##### STEPS TO REPRODUCE

```
    - name: Set UrlSegmentMaxLength
      win_regedit: 
        key: "HKLM:\\SYSTEM\\CurrentControlSet\\Services\\HTTP\\Parameters" 
        value: "UrlSegmentMaxLength"
        datatype: "dword"
        data: 7000
```

##### EXPECTED RESULTS

after second run it should be in "ok" state
##### ACTUAL RESULTS

after second run still "changed" - though the value seems to be correct in the registry editor

**Comment by ansibot** [comment]
@joshludwig, @smadam813, ping. This issue is waiting on your response.
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by jhawkesworth** [comment]
@mdorenkamp Please try ansible 2.1.1 as I believe this issue is fixed in 2.1.1 following a fix I made to this module.

EDIT: needs_info

**Comment by refinedcranberry** [comment]
nope, its still not working
one thing i observed is that ansible --version returns 2.1.0.0 though dpkg -l returns 2.1.1.0-1ppa~xenial

**Comment by ansibot** [comment]
@joshludwig, @smadam813, ping. This issue is still waiting on your response.
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by jhawkesworth** [comment]
Another thought then, could you try without the double quotes and double backslashes.  You would need quotes (single quotes would do) if there was a space in the key name but I think they can be omitted otherwise as of ansible 2.x

```
    - name: Set UrlSegmentMaxLength
      win_regedit: 
        key: HKLM:\SYSTEM\CurrentControlSet\Services\HTTP\Parameters
        value: UrlSegmentMaxLength
        datatype: dword
        data: 7000
```
