### ISSUE TITLE
vmware_guest requires disk.size_gb, but ignores on clone

### ISSUE THREAD

**Issue by phips** [ansible/ansible-modules-extras#2706]
##### ISSUE TYPE
- Bug Report
##### COMPONENT NAME

vmware_guest
##### ANSIBLE VERSION

```
(ansible)[vagrant@tower3 cm]$ ansible --version
ansible 2.2.0
  config file = /home/vagrant/cm/ansible.cfg
  configured module search path = Default w/o overrides

(ansible)[vagrant@tower3 cm]$ rpm -q ansible
ansible-2.2.0-0.git201608051506.1714279.devel.el7.centos.noarch
```
##### OS / ENVIRONMENT

```
(ansible)[vagrant@tower3 cm]$ cat /etc/redhat-release 
CentOS Linux release 7.2.1511 (Core) 
```
##### SUMMARY

'disk' option is required for vmware_guest module to work, but providing it when cloning a template is irrelevant - the settings are ignored anyway.
##### STEPS TO REPRODUCE

```
    - name: Create VM from template
      vmware_guest:
        validate_certs: False
        hostname: "{{ vcenter_hostname }}"
        username: "{{ vcenter_user }}"
        password: "{{ vcenter_pass }}"
        esxi_hostname: "{{ esxhost }}"
        datacenter: BOX
        name: "{{ name }}"
        template: "{{ vmtemplate }}"
        disk:
          - size_gb: 10
            type: thin
            datastore: "{{ datastore }}"
        nic:
          - type: vmxnet3
            network: "{{ network }}"
        hardware:
          memory_mb: "{{ vm_memory | default(1024) }}"
        wait_for_ip_address: True
        state: present
      register: newvm
```
##### EXPECTED RESULTS

Disk size to be 10gb
##### ACTUAL RESULTS

Disk size is the same as the underlying template - 20gb

![vmware](https://cloud.githubusercontent.com/assets/329022/17557183/238b6d8e-5f0e-11e6-80c7-645364a04b2f.png)
