### ISSUE TITLE
Doc: ec2_vpc_route_table_facts: example for VPC ID filter has error

### ISSUE THREAD

**Issue by ralfbergs** [ansible/ansible-modules-extras#2719]
##### ISSUE TYPE

- Documentation Report
##### COMPONENT NAME

ec2_vpc_route_table_facts
##### ANSIBLE VERSION

```
ansible 2.1.1.0
```
##### SUMMARY

At [this URL](https://docs.ansible.com/ansible/ec2_vpc_route_table_facts_module.html) it says:

```
# Gather facts about any VPC route table within VPC with ID vpc-abcdef00
- ec2_vpc_route_table_facts:
    filters:
      vpc-id: vpc-abcdef00
```

However, the actual filter expression should be as follows (confirmed this thru coding):

```
      vpc_id: vpc-abcdef00
```

Note the underscore vs. the dash.
