### ISSUE TITLE
ec2_vpc_route_table returns plural or singular variable depending CGW status

### ISSUE THREAD

**Issue by db-beachbody** [ansible/ansible-modules-extras#2773]
##### ISSUE TYPE
- Bug Report
##### COMPONENT NAME

ec2_vpc_route_table
##### ANSIBLE VERSION

```
ansible 2.2.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
```
##### CONFIGURATION

standard
##### OS / ENVIRONMENT

Mac / RHEL
##### SUMMARY

If the CGW doesn't exist I get the variable "customer_gateway" back, when it does exist I get the plural back customer_gateways.  I am unable to write code around the registered variable due to this problem.

CGW doesn't exist.
"gateway": {
"customer_gateway": {
"bgp_asn": "12345",
"customer_gateway_id": "cgw-8c03da92",

CGW already exists.
"gateway": {
"customer_gateways": [
{
"bgp_asn": "12345",
"customer_gateway_id": "cgw-8c03da92",
##### STEPS TO REPRODUCE

Execute without CGW returns, gateway.customer_gateway[0].customer_gateway_id
Execute with the CGW in place returns, gateway.customer_gateways[0].customer_gateway_id

```
    - name: Create Customer Gateway (CGW)
      ec2_customer_gateway:
        aws_access_key: "{{ assumed_role.sts_creds.access_key }}"
        aws_secret_key: "{{ assumed_role.sts_creds.secret_key }}"
        security_token: "{{ assumed_role.sts_creds.session_token }}"
        name: "{{ item }}"
        bgp_asn: "{{ bgp_asn }}"
        ip_address: "{{ item }}"
        region: "{{ region }}"
      register: cgw
      with_items:
        - "{{ networking.cgwip }}"
```
##### EXPECTED RESULTS

Return a predictable variable name so I can reference it later in the playbook,
##### ACTUAL RESULTS

```
CGW doesn't exist.
"gateway": {
"customer_gateway": {
"bgp_asn": "12345",
"customer_gateway_id": "cgw-8c03da92",

CGW already exists.
"gateway": {
"customer_gateways": [
{
"bgp_asn": "12345",
"customer_gateway_id": "cgw-8c03da92",
```
