### ISSUE TITLE
unable to get stdout from asa_command 

### ISSUE THREAD

**Issue by atul-ram** [ansible/ansible-modules-extras#2781]
##### COMPONENT NAME

asa_command
##### ANSIBLE VERSION

2.2
##### OS / ENVIRONMENT

centos 7
##### STEPS TO REPRODUCE

```
- name: add src ips to object
    asa_command:
      provider: "{{ cli }}"
      commands:
        - config t
        - object-group network "CR_{{ item.ChangeId }}_src"
        - "network-object host {{ item.SrcIp }}"
    with_items: '{{ Rules }}'
    when: item.state == 'present'
    register: result
-  debug: var=result.stdout

```

##### EXPECTED RESULTS

 "stdout": [
        "",
        "",
        "Adding obj (network-object host 122.14.15.43) to grp (CR_56116_dest) failed; object already exists\n"
    ],
##### ACTUAL RESULTS

 "result.stdout": "VARIABLE IS NOT DEFINED!"

```

```

**Comment by ansibot** [comment]
@privateip, @ogenstad, ping. This issue is waiting on your response.
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ogenstad** [comment]
I will have to take a look at this. The ios_command now supports a warnings variable, as asa_command uses the same underlying utils this new variable might also work in asa_command. @privateip would know if this is the case. I also don't know by heart how the register variable behaves in this case when using with_items.

Having said that I would ask your about the end goal. I wouldn't view the above as the "ansible way" to handle this config. I would instead do something like:

```
- name: add src ips to object
    asa_config:
      provider: "{{ cli }}"
      parents:  "object-group network CR_{{ item.ChangeId }}_src"
      lines: 
        - "network-object host {{ item.SrcIp }}"
    with_items: '{{ Rules }}'
    when: item.state == 'present'
```

This would be idempotent where the asa_command option would always try to do the change even if it wasn't needed.
