### ISSUE TITLE
Set notes and resource_pool on vmware_guest

### ISSUE THREAD

**Issue by DenysLP** [ansible/ansible-modules-extras#2796]
##### ISSUE TYPE
- Feature Idea
##### COMPONENT NAME

vmware_guest
##### ANSIBLE VERSION

ansible 2.1.1.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides

```

```
##### OS / ENVIRONMENT

CentOS Linux release 7.2.1511 (Core)
##### SUMMARY

Set notes and resource_pool
##### STEPS TO REPRODUCE

```
- name: Create VM
  vmware_guest:
    validate_certs: False
    hostname: "{{ vsphere_vcenter_hostname }}"
    username: "{{ vsphere_vcenter_username }}"
    password: "{{ vsphere_vcenter_password }}"
    name: "{{ inventory_hostname }}"
    state: poweredoff
    folder: "{{ vsphere_vm_folder }}"
    disk:
        - size_gb: 16
          type: thin
          datastore: "{{ vsphere_datastore_name }}"
    nic:
        - type: vmxnet3
          network: DMZ
          network_type: dvs
    datacenter: "{{ vsphere_datacenter_name }}"
    esxi_hostname: "{{ vsphere_vcenter_password }}"
    template: "{{ vsphere_template_name }}"
    wait_for_ip_address: False
  register: deploy
```

where set notes and resource_pool?
##### EXPECTED RESULTS

is set the pool resource and a description for notes.
##### ACTUAL RESULTS

data not septate

```

```
