### ISSUE TITLE
Cannot request certificate (letsencrypt) with error message "Error validating challenge: ..."

### ISSUE THREAD

**Issue by tkt028** [ansible/ansible-modules-extras#2799]
##### ISSUE TYPE

- Bug Report
##### COMPONENT NAME

letsencrypt
##### ANSIBLE VERSION

```
ansible 2.2.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
```
##### OS / ENVIRONMENT

Laptop (Linux Manjaro) execute Ansible playbook against CentOS 7 server
##### SUMMARY

Cannot request certificate (letsencrypt) with error message "Error validating challenge: ..."
##### STEPS TO REPRODUCE

Follow the example of letsencrypt at https://docs.ansible.com/ansible/letsencrypt_module.html#requirements-on-host-that-executes-module
- step 1. generate RSA key and CSR at my laptop (Manjaro Linux) and copy to the CentOS 7 server
- step 2. check nginx config in CentOS server to guarantee that we can retrieve challenge file at path like http://mydomain.com/.well-known/acme-challenge/-EJuzZ8j_qy8g8zB9B4C9Zy2jXEAqwyGoSSB819Rxvc
- step 3. run ansible example script against that server

```
$ ansible-playbook -i inventory -u root bases.yml -v
```

> RESULT: certificate issuing failed with error message "Error validating challenge ......" (see below for full log)

```
- name: install certificates for Test Zabbix
  letsencrypt:
    account_key: /path/to/mydomain.com/mydomain.com.key
    csr: /path/to/mydomain.com/mydomain.com.csr
    dest: /path/to/mydomain.com/mydomain.com.crt
  register: mydomain_com_challenge

# perform the necessary steps to fulfill the challenge for example:
- copy:
    dest: /var/www/html/{{ mydomain_com_challenge['challenge_data']['mydomain.com']['http-01']['resource'] }}
    content: "{{ mydomain_com_challenge['challenge_data']['mydomain.com']['http-01']['resource_value'] }}"
  when: mydomain_com_challenge|changed

- name: install certificates for Zabbix
  letsencrypt:
    account_key: /path/to/mydomain.com/mydomain.com.key
    csr: /path/to/mydomain.com/mydomain.com.csr
    dest: /path/to/mydomain.com/mydomain.com.crt
    data: "{{ mydomain_com_challenge }}"
```

##### EXPECTED RESULTS

I expect the certificate issuing succeed (even though the default URL of letsencrypt is staging server) according to example described in Ansible official document.
##### ACTUAL RESULTS

```
TASK [ansible-letsencrypt : install certificates for Test Zabbix] **************
changed: [63.142.XX.YY] => {"authorizations": [{"challenges": [{"status": "pending", "token": "a6D8LriXpYFWBqPCCR9TLYcLhkuX78TTwDrwUWt_cD0", "type": "tls-sni-01", "uri": "https://acme-staging.api.letsencrypt.org/acme/challenge/x2O9olBftqYw-1qfR2wXDyK-tTaDhkAOjq8qtyyXGH4/11844425"}, {"status": "pending", "token": "-EJuzZ8j_qy8g8zB9B4C9Zy2jXEAqwyGoSSB819Rxvc", "type": "http-01", "uri": "https://acme-staging.api.letsencrypt.org/acme/challenge/x2O9olBftqYw-1qfR2wXDyK-tTaDhkAOjq8qtyyXGH4/11844426"}, {"status": "pending", "token": "5n9Z5muezqi911qAPPChA7rnnwxSPqcqphRJSnO7qXo", "type": "dns-01", "uri": "https://acme-staging.api.letsencrypt.org/acme/challenge/x2O9olBftqYw-1qfR2wXDyK-tTaDhkAOjq8qtyyXGH4/11844427"}], "combinations": [[0], [1], [2]], "expires": "2016-09-03T07:39:24.419769206Z", "identifier": {"type": "dns", "value": "mydomain.com"}, "status": "pending", "uri": "https://acme-staging.api.letsencrypt.org/acme/authz/x2O9olBftqYw-1qfR2wXDyK-tTaDhkAOjq8qtyyXGH4"}], "cert_days": -1, "challenge_data": {"mydomain.com": {"dns-01": {"resource": "_acme-challenge", "resource_value": "ECW-zJ-oqqa0NrZwtpNNNFDoOrAX2HkpD5v1FhS0KI8"}, "http-01": {"resource": ".well-known/acme-challenge/-EJuzZ8j_qy8g8zB9B4C9Zy2jXEAqwyGoSSB819Rxvc", "resource_value": "-EJuzZ8j_qy8g8zB9B4C9Zy2jXEAqwyGoSSB819Rxvc.qyzD-ebStixuyLGMoFX7gLRCsylHqV5tZEOuzBX8bec"}}}, "changed": true}

TASK [ansible-letsencrypt : copy] **********************************************
changed: [63.142.XX.YY] => {"changed": true, "checksum": "2f898e335a26d8ba37ff9bd3d51e8bb25e85472b", "dest": "/var/www/html/.well-known/acme-challenge/-EJuzZ8j_qy8g8zB9B4C9Zy2jXEAqwyGoSSB819Rxvc", "gid": 0, "group": "root", "md5sum": "111c6531ebea8561bec0f77389fe921b", "mode": "0644", "owner": "root", "size": 87, "src": "/root/.ansible/tmp/ansible-tmp-1472283569.85-125669089251342/source", "state": "file", "uid": 0}

TASK [ansible-letsencrypt : install certificates for Zabbix] *******************
fatal: [63.142.XX.YY]: FAILED! => {"changed": false, "failed": true, "msg": "Error validating challenge: CODE: ************************ RESULT: {u'status': u'********', u'keyAuthorization': u'********', u'token': u'-EJuzZ8j_qy8g8zB9B4C9Zy********jXEAqwyGoSSB8********9Rxvc', u'type': u'http-****************', u'uri': u'********'}"}
        to retry, use: --limit @bases.retry
```

By executing the script again, I received another error (this times, I used high verbosity -vvv)

```
TASK [ansible-letsencrypt : install certificates for Test Zabbix] **************
task path: /home/my_user/MY_USER/path/to/ansible-letsencrypt/tasks/main.yml:50
Using module file /usr/lib/python2.7/site-packages/ansible/modules/extras/web_infrastructure/letsencrypt.py
<63.142.XX.YY> ESTABLISH SSH CONNECTION FOR USER: root
<63.142.XX.YY> SSH: EXEC ssh -q -C -o ControlMaster=auto -o ControlPersist=60s -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o User=root -o ConnectTimeout=10 -o ControlPath=/home/my_user/.ansible/cp/ansible-ssh-%h-%p-%r 63.142.XX.YY '/bin/sh -c '"'"'( umask 77 && mkdir -p "` echo $HOME/.ansible/tmp/ansible-tmp-1472285560.26-149187906418373 `" && echo ansible-tmp-1472285560.26-149187906418373="` echo $HOME/.ansible/tmp/ansible-tmp-1472285560.26-149187906418373 `" ) && sleep 0'"'"''
<63.142.XX.YY> PUT /tmp/tmpOjTggd TO /root/.ansible/tmp/ansible-tmp-1472285560.26-149187906418373/letsencrypt.py
<63.142.XX.YY> SSH: EXEC sftp -b - -C -o ControlMaster=auto -o ControlPersist=60s -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o User=root -o ConnectTimeout=10 -o ControlPath=/home/my_user/.ansible/cp/ansible-ssh-%h-%p-%r '[63.142.XX.YY]'
<63.142.XX.YY> ESTABLISH SSH CONNECTION FOR USER: root
<63.142.XX.YY> SSH: EXEC ssh -q -C -o ControlMaster=auto -o ControlPersist=60s -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o User=root -o ConnectTimeout=10 -o ControlPath=/home/my_user/.ansible/cp/ansible-ssh-%h-%p-%r 63.142.XX.YY '/bin/sh -c '"'"'chmod u+x /root/.ansible/tmp/ansible-tmp-1472285560.26-149187906418373/ /root/.ansible/tmp/ansible-tmp-1472285560.26-149187906418373/letsencrypt.py && sleep 0'"'"''
<63.142.XX.YY> ESTABLISH SSH CONNECTION FOR USER: root
<63.142.XX.YY> SSH: EXEC ssh -q -C -o ControlMaster=auto -o ControlPersist=60s -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o User=root -o ConnectTimeout=10 -o ControlPath=/home/my_user/.ansible/cp/ansible-ssh-%h-%p-%r -tt 63.142.XX.YY '/bin/sh -c '"'"'/usr/bin/python2 /root/.ansible/tmp/ansible-tmp-1472285560.26-149187906418373/letsencrypt.py; rm -rf "/root/.ansible/tmp/ansible-tmp-1472285560.26-149187906418373/" > /dev/null 2>&1 && sleep 0'"'"''
fatal: [63.142.XX.YY]: FAILED! => {
    "changed": false,
    "failed": true,
    "invocation": {
        "module_args": {
            "account_email": null,
            "account_key": "/path/to/mydomain.com.key",
            "acme_directory": "https://acme-staging.api.letsencrypt.org/directory",
            "agreement": "https://letsencrypt.org/documents/LE-SA-v1.1.1-August-1-2016.pdf",
            "challenge": "http-01",
            "csr": "/path/to/mydomain.com.csr",
            "data": null,
            "dest": "/path/to/mydomain.com.crt",
            "remaining_days": 10
        },
        "module_name": "letsencrypt"
    },
    "msg": "Error new cert: CODE: 400 RESULT: None"
}
        to retry, use: --limit @bases.retry

PLAY RECAP *********************************************************************
```
