### ISSUE TITLE
Cannot run os_server_group

### ISSUE THREAD

**Issue by alitvak69** [ansible/ansible-modules-extras#2893]
##### ISSUE TYPE

- Bug Report
##### COMPONENT NAME

os_server_group
##### ANSIBLE VERSION

```
ansible 2.2.0
  config file = /home/vagrant/ansible/ansible.cfg
  configured module search path = Default w/o overrides
```
##### CONFIGURATION

[defaults]
force_color = 1
hostfile = /home/vagrant/ansible/inventory.ini
roles_path = /home/vagrant/ansible/roles
forks=10
##### OS / ENVIRONMENT

ubuntu 16.04.1 
##### SUMMARY

When using os_server_group I receive an error
##### STEPS TO REPRODUCE

ansible-playbook -vvv  -f 10 --check --diff openstack-utilities-instance.yml

```
#clouds.yml
clouds:
  losangeles:
    user_domain_name: Default
    project_domain_name: Default
    auth:
      username: 'admin'
      password: 'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx'
      project_name: 'admin'
      auth_url:  xxxxxxxxxxxxxx

#openstack-utilities-instance.yml

---
- hosts: localhost
  gather_facts: False
  roles:
    - openstack-utilities-instance-launch

# /home/vagrant/ansible/roles/openstack-utilities-instance-launch/tasks/main.yml

---

# Create a server group
- name: Create a server group
  os_server_group:
    state: present
    cloud: losangeles
    name: utility-container
    policies:
      - soft-anti-affinity
```

##### EXPECTED RESULTS

A successful dry run of the module
##### ACTUAL RESULTS

Play book run fails with error
AttributeError: 'OpenStackCloud' object has no attribute 'get_server_group'

```
vagrant@mgmt:~/ansible$ ansible-playbook -vvv  -f 10 --check --diff openstack-utilities-instance.yml 
Using /home/vagrant/ansible/ansible.cfg as config file

PLAYBOOK: openstack-utilities-instance.yml *************************************
1 plays in openstack-utilities-instance.yml

PLAY [localhost] ***************************************************************

TASK [openstack-utilities-instance-launch : Create a server group] *************
task path: /home/vagrant/ansible/roles/openstack-utilities-instance-launch/tasks/main.yml:4
Using module file /usr/lib/python2.7/dist-packages/ansible/modules/extras/cloud/openstack/os_server_group.py
<127.0.0.1> ESTABLISH LOCAL CONNECTION FOR USER: vagrant
<127.0.0.1> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo $HOME/.ansible/tmp/ansible-tmp-1473573110.09-254951870083661 `" && echo ansible-tmp-1473573110.09-254951870083661="` echo $HOME/.ansible/tmp/ansible-tmp-1473573110.09-254951870083661 `" ) && sleep 0'
<127.0.0.1> PUT /tmp/tmpyWgLmf TO /home/vagrant/.ansible/tmp/ansible-tmp-1473573110.09-254951870083661/os_server_group.py
<127.0.0.1> EXEC /bin/sh -c 'chmod u+x /home/vagrant/.ansible/tmp/ansible-tmp-1473573110.09-254951870083661/ /home/vagrant/.ansible/tmp/ansible-tmp-1473573110.09-254951870083661/os_server_group.py && sleep 0'
<127.0.0.1> EXEC /bin/sh -c '/usr/bin/python /home/vagrant/.ansible/tmp/ansible-tmp-1473573110.09-254951870083661/os_server_group.py; rm -rf "/home/vagrant/.ansible/tmp/ansible-tmp-1473573110.09-254951870083661/" > /dev/null 2>&1 && sleep 0'
An exception occurred during task execution. The full traceback is:
Traceback (most recent call last):
  File "/tmp/ansible_wqTo33/ansible_module_os_server_group.py", line 182, in <module>
    main()
  File "/tmp/ansible_wqTo33/ansible_module_os_server_group.py", line 145, in main
    server_group = cloud.get_server_group(name)
AttributeError: 'OpenStackCloud' object has no attribute 'get_server_group'

fatal: [localhost]: FAILED! => {
    "changed": false, 
    "failed": true, 
    "invocation": {
        "module_name": "os_server_group"
    }, 
    "module_stderr": "Traceback (most recent call last):\n  File \"/tmp/ansible_wqTo33/ansible_module_os_server_group.py\", line 182, in <module>\n    main()\n  File \"/tmp/ansible_wqTo33/ansible_module_os_server_group.py\", line 145, in main\n    server_group = cloud.get_server_group(name)\nAttributeError: 'OpenStackCloud' object has no attribute 'get_server_group'\n", 
    "module_stdout": "", 
    "msg": "MODULE FAILURE"
}
    to retry, use: --limit @openstack-utilities-instance.retry

PLAY RECAP *********************************************************************
localhost                  : ok=0    changed=0    unreachable=0    failed=1   

```
