### ISSUE TITLE
Unable to download Mavin Artifact

### ISSUE THREAD

**Issue by rmauc** [ansible/ansible-modules-extras#2906]
##### ISSUE TYPE

- Documentation Report
   After extensive deep googling I am unable to find the reason why this maven_artifact playbook fails to run:
##### COMPONENT NAME

maven_artifact
##### ANSIBLE VERSION

```
 ansible --version
ansible 2.1.0.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides

```
##### CONFIGURATION

none
##### OS / ENVIRONMENT

RHEL7
##### SUMMARY

Unable to get an artifact back from Maven
This is my Maven declaration:
<dependency>
    <groupId>200</groupId>
    <artifactId>2001</artifactId>
    <version>1.0</version>
    <type>xls</type>
</dependency>
##### STEPS TO REPRODUCE

I have the python  and lxml dependencies in place.

```
- name: Download artifact from maven repository
  hosts: localhost
  tasks:
    - maven_artifact: group_id=200 artifact_id=2001 version=1.0 repository_url:"http://XXXXXX.XXXcorp.com:8081/artifactory/" extension:xls dest=/tmp/2001-1.0.xls state=present validate_certs=no

I have tried to add the "user=XXX" & "password=YYYY" but that also fails.
```

##### EXPECTED RESULTS

We have the file pulled into /tmp
##### ACTUAL RESULTS

ERROR! this task 'maven_artifact' has extra params, which is only allowed in the following modules: command, shell, script, include, include_vars, add_host, group_by, set_fact, raw, meta

The error appears to have been in '/ansible/playbooks/richard/maven_art_download2.yml': line 4, column 7, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:

  tasks:
    - maven_artifact: group_id=200 artifact_id=2001 version=1.0 repository_url:"http://XXXXX.XXXX.com:8081/artifactory/" extension:xls dest=/tmp/2001-1.0.xls state=present validate_certs=no
      ^ here

The error appears to have been in '/ansible/playbooks/richard/maven_art_download2.yml': line 4, column 7, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:

  tasks:
    - maven_artifact: group_id=200 artifact_id=2001 version=1.0 repository_url:"http://XXXXX.XXXX.com:8081/artifactory/" extension:xls dest=/tmp/2001-1.0.xls state=present validate_certs=no
      ^ here

```
Thanks
```
