### ISSUE TITLE
vmware_guest.py Clone operation not working

### ISSUE THREAD

**Issue by ikkaro** [ansible/ansible-modules-extras#2911]
##### ISSUE TYPE
- Bug Report
##### COMPONENT NAME

vmware_guest.py
##### ANSIBLE VERSION

```
ansible 2.2.0 (devel 28feba2fb3) last updated 2016/09/14 10:52:02 (GMT +200)
  lib/ansible/modules/core: (detached HEAD ae6992bf8c) last updated 2016/09/14 10:52:09 (GMT +200)
  lib/ansible/modules/extras: (devel 6d37aa4260) last updated 2016/09/14 10:53:58 (GMT +200)
  config file = 
  configured module search path = Default w/o overrides
```
##### CONFIGURATION

Default configuration
##### OS / ENVIRONMENT

N/A
##### SUMMARY

Deploy a VM from a template is not working
##### STEPS TO REPRODUCE

```
  tasks:
    - name: create the VM
      vmware_guest:
        validate_certs: False
        hostname: "{{ vcenter_hostname }}"
        username: "{{ vcenter_user }}"
        password: "{{ vcenter_pass }}"
        name: "{{ vm_name }}"
        state: present
        folder: DevDeploys
        disk:
            - size_gb: 25
              type: thin
              datastore: my-datastore
        nic:
            - type: vmxnet3
              network: VMNetwork
              network_type: standard
        hardware:
            memory_mb: 512
            num_cpus: 2
            #osid: ubuntu64guest
            scsi: paravirtual
        datacenter: datacenter
        esxi_hostname: host01.compute.domain.net
        template: test2.template
        wait_for_ip_address: no
      register: deploy
```
##### EXPECTED RESULTS

The VM is cloned with the required parameters.
##### ACTUAL RESULTS

```
fatal: [localhost]: FAILED! => {
    "changed": false,                                                                                                                                                                           
    "failed": true,                                                                                                                                                                             
    "invocation": {                                                                                                                                                                             
        "module_args": {                                                                                                                                                                        
            "datacenter": "datacenter",                                                                                                                                                   
            "disk": [                                                                                                                                                                           
                {                                                                                                                                                                               
                    "datastore": "my-datastore", 
                    "size_gb": 25, 
                    "type": "thin"
                }
            ], 
            "esxi_hostname": "host01.compute.domain.net", 
            "folder": "DevDeploys", 
            "force": false, 
            "hardware": {
                "memory_mb": 512, 
                "num_cpus": 2, 
                "scsi": "paravirtual"
            }, 
            "hostname": "vcenter100.es.clara.net", 
            "name": "igh77", 
            "name_match": "first", 
            "nic": [
                {
                    "network": "VMNetwork", 
                    "network_type": "standard", 
                    "type": "vmxnet3"
                }
            ], 
            "password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER", 
            "state": "present", 
            "template": "test2.template", 
            "template_src": "tes2.template", 
            "username": "MY USERNAME", 
            "uuid": null, 
            "validate_certs": false, 
            "wait_for_ip_address": false
        }, 
        "module_name": "vmware_guest"
    }, 
    "msg": "A specified parameter was not correct. \n"
}
```
