### ISSUE TITLE
Ansible Reports Twilio Failure Yet SMS Sent Successfullly

### ISSUE THREAD

**Issue by ifelsefi** [ansible/ansible-modules-extras#3029]
##### ISSUE TYPE

- Bug Report
##### COMPONENT NAME

Twilio
##### ANSIBLE VERSION

```
ansible 2.1.1.0
  config file = /home/douglas/repos/ansible/ansible.cfg
  configured module search path = Default w/o overrides
```
##### CONFIGURATION

```
Pipelining and threads but nothing else

```
##### OS / ENVIRONMENT

```
Linux Mint

```
##### SUMMARY

```

TASK [accounts : send sms challenge] *******************************************
fatal: [pascal -> localhost]: FAILED! => {"changed": false, "failed": true, "msg": "unable to send message to +15163205079"}
...ignoring

Yet Twilio console shows SMS delivered while recipient confirms SMS 

```
##### STEPS TO REPRODUCE

```
ansible-playbook accounts.yml "-e hosts=server -e csms=[] -e number=+blah -e user=blah" -t csms --sudo -K --ask-vault-pass

cat accounts.yml 

---
- hosts: "{{ hosts }}"
  roles: 
    - accounts
  gather_facts: True


cat roles/accounts/tasks/main.yml 

- include: create_user.yml
  when: create is defined

- include: remove_user.yml
  when: remove is defined

- include: xfs.yml
  when: ansible_hostname == "blah" or "blah"

- include: lab_email.yml
  when: lab is defined

- include: challenge.yml
  when: csms is defined

cat roles/accounts/tasks/challenge.yml 

- name: send sms challenge
  tags: csms 
  twilio:
   msg: "{{ challenge }}"
   account_sid: "SID"
   auth_token: "TOKEN"
   from_number: "+BLAH"
   to_number: "{{ number }}"
  delegate_to: localhost    
  ignore_errors: True

```

##### EXPECTED RESULTS

SMS works without reported error
##### ACTUAL RESULTS

SMS works but module reports error 

```

 ansible-playbook accounts.yml "-e hosts=host -e csms=[] -e number=+blah -e user=blah" -t csms --sudo -K --ask-vault-pass -vvv
Using /home/user/repos/ansible/ansible.cfg as config file
SUDO password: 
Vault password: 

PLAYBOOK: accounts.yml *********************************************************
1 plays in accounts.yml

PLAY [pascal] ******************************************************************

TASK [setup] *******************************************************************
<pascal> ESTABLISH SSH CONNECTION FOR USER: None
<pascal> SSH: EXEC ssh -C -q -o ControlMaster=auto -o ControlPersist=60s -o Port=22 -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o ConnectTimeout=20 -o ControlPath=/home/user/.ansible/cp/ansible-ssh-%h-%p-%r host '/bin/sh -c '"'"'sudo -H -S  -p "[sudo via ansible, key=dovdppgsmmkpysizwmmmanqpnsnbhkbn] password: " -u root /bin/sh -c '"'"'"'"'"'"'"'"'echo BECOME-SUCCESS-dovdppgsmmkpysizwmmmanqpnsnbhkbn; LANG=C LC_ALL=C LC_MESSAGES=C /usr/bin/python'"'"'"'"'"'"'"'"' && sleep 0'"'"''
ok: [pascal]

TASK [accounts : send sms challenge] *******************************************
task path: /home/user/repos/ansible/playbooks/roles/accounts/tasks/challenge.yml:11
<localhost> ESTABLISH LOCAL CONNECTION FOR USER: user
<localhost> EXEC /bin/sh -c 'sudo -H -S  -p "[sudo via ansible, key=pgyfxtpxffqiposwtecseosepacqessa] password: " -u root /bin/sh -c '"'"'echo BECOME-SUCCESS-pgyfxtpxffqiposwtecseosepacqessa; LANG=C LC_ALL=C LC_MESSAGES=C /usr/bin/python'"'"' && sleep 0'
fatal: [user -> localhost]: FAILED! => {"changed": false, "failed": true, "invocation": {"module_args": {"account_sid": "blah", "auth_token": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER", "from_number": "+blah", "media_url": null, "msg": "challenge", "to_number": "+blahblah", "url_password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER", "url_username": "blah"}, "module_name": "twilio"}, "msg": "unable to send message to +blah"}
...ignoring

PLAY RECAP *********************************************************************
host                     : ok=2    changed=0    unreachable=0    failed=0   

```
