### ISSUE TITLE
Blockinfile overwrites symlink with file if changed

### ISSUE THREAD

**Issue by techhazard** [ansible/ansible-modules-extras#3052]
##### ISSUE TYPE
- Bug Report
##### COMPONENT NAME

blockinfile
##### ANSIBLE VERSION

```
ansible 2.1.0.0
  config file = /Users/vince/ansible/ansible.cfg
  configured module search path = Default w/o overrides
```
##### CONFIGURATION

ansible.cfg mentioned above:

```
[defaults]
roles_path = ./roles:/etc/ansible/roles
forks=25
retry_files_save_path = ./.retry/
```
##### OS / ENVIRONMENT

I'm running ansible on OSX El Capitain (10.11.6) and managing localhost
I'm also running ansible on debian jessie with ansible 2.2.0 and the same config (as localhost)
##### SUMMARY

blockinfile overwrites the file with the new version if the old version does not have the block.
The problem arises when the file is a symlink. The symlink is overwritten with the file version of the linked file with the new block added. (happens on both OSs/ansible versions)

The links remains in existence if the content does not need to be not changed
##### STEPS TO REPRODUCE

To test:
put the following in `~/test_file`:

```
this is a regular file
```

then symlink `~/test_file` as `~/test_link` like so:

```
$ ln -s ~/test_file ~/test_link
```

Then run the following playbook

``` yaml
- hosts: localhost
  become: no
  tasks:
    - blockinfile:
        block: |
          hostsum="$(hostname | cksum | awk '{print $1}')";
          export hostnum="$((hostsum%253))";
          export hostcolor="$(tput setaf $hostnum)"
        dest: ~/test_link
        marker: "# hostcolor {mark} ANSIBLE MANAGED BLOCK"
```
##### EXPECTED RESULTS

note the filetype `l` of the link and the filesize of `228` of the linked file

```
$ ls -laF ~/test_link ~/test_file
-rw-r--r-- 1 vince vince 228 Sep 28 10:37 /home/vince/test_file
lrwxrwxrwx 1 vince vince  21 Sep 28 10:32 /home/vince/test_link -> /home/vince/test_file
```

I also expect both files to have the same content:

```
$ diff -s ~/test_file ~/test_link
Files /home/vince/test_file and /home/vince/test_link are identical
```
##### ACTUAL RESULTS

```
$ ls -laF ~/test_link ~/test_file
-rw-r--r-- 1 vince vince  23 Sep 28 10:39 /home/vince/test_file
-rw-r--r-- 1 vince vince 228 Sep 28 10:39 /home/vince/test_link
```

```
$ diff -s ~/test_file ~/test_link
1a2,6
> # hostcolor BEGIN ANSIBLE MANAGED BLOCK
> hostsum="$(hostname | cksum | awk '{print $1}')";
> export hostnum="$((hostsum%253))";
> export hostcolor="$(tput setaf $hostnum)"
> # hostcolor END ANSIBLE MANAGED `BLOCK`
```

If I can find the time I'll do some additional research, but this should be enough to get started 😉

**Comment by ansibot** [comment]
@yaegashi ping, this issue is waiting for your response.
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibot** [comment]
@yaegashi, ping. This issue is still waiting on your response.
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by yaegashi** [comment]
You can achieve that expected result by adding `follow: yes`.

``` yaml
- hosts: localhost
  become: no
  tasks:
    - blockinfile:
        block: |
          hostsum="$(hostname | cksum | awk '{print $1}')";
          export hostnum="$((hostsum%253))";
          export hostcolor="$(tput setaf $hostnum)"
        dest: ~/test_link
        marker: "# hostcolor {mark} ANSIBLE MANAGED BLOCK"
        follow: yes
```
