### ISSUE TITLE
Rabbitmq_plugin only installs the last plugin when using with_items

### ISSUE THREAD

**Issue by ivandigiusto** [ansible/ansible-modules-extras#306]
I am using with_items to load each of the plugins that need to be installed.  Only the last of the 6 plugins specified gets installed.

Example:

```
- name: enable rabbitmq plugins
  rabbitmq_plugin: names={{ item }} state=enabled
  with_items:
    - rabbitmq_management
    - rabbitmq_management_visualiser
    - rabbitmq_shovel
    - rabbitmq_shovel_management
    - rabbitmq_federation
    - rabbitmq_federation_management
  notify:
    - restart rabbitmq
```

with_items is an allowed Ansible approach but it does not work as expected here.

After troubleshooting, I have used a different format, where I have specified the plugins on one line.

```
- name: enable rabbitmq plugins
  rabbitmq_plugin: names=rabbitmq_management,rabbitmq_management_visualiser,rabbitmq_shovel,rabbitmq_shovel_management,rabbitmq_federation,rabbitmq_federation_management state=enabled
  notify:
    - restart rabbitmq
```

I got it working, but there are two problems that this issue raises:
-with_items syntax is not properly supported by this module (it applies each item but only keeps enabled the last one)
-listing all plugins on one line becomes hard to manage and troubleshoot - so using with_items (when it works properly) would help greatly.

Thanks,
Ivan
