### ISSUE TITLE
win_package not accepting exit code 3010 as success

### ISSUE THREAD

**Issue by romaindup** [ansible/ansible-modules-extras#3067]
##### ISSUE TYPE
- Bug Report
##### COMPONENT NAME

win_package
##### ANSIBLE VERSION

```
ansible 2.1.0.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
```
##### CONFIGURATION

Default options
##### OS / ENVIRONMENT

Ansible on RHEL 6, deploying to a Windows 2008 R2 server
##### SUMMARY

When installing some msi, the return code is 3010 (requires restart). This is considered as a failed return code instead of a successful return code
##### STEPS TO REPRODUCE

Call the win_package module for an installer that returns exit code 3010 when installing (Visual C++ 2008 redistributable for example)

```
- name: Install Visual C++ 2008 Runtime
  win_package:
    name: 'Microsoft Visual C++ 2008 Runtime'
    path: 'C;\temp\vcredist_x86.exe'
    product_id: '{FF66E9F6-83E7-3A3E-AF14-8DE9A809A6A4}'
    arguments: '/q'
```
##### EXPECTED RESULTS

The step should be successful and changed as the package was installed. As an example, chocolatey accept several return codes as valid. It could also be implemented by having a new property to list valid return codes.
##### ACTUAL RESULTS

returned json:
{
  "_ansible_no_log": false,
  "changed": false,
  "failed": true,
  "msg": "The return code 3010 was not expected. Configuration is likely not correct",
  "name": "Microsoft Visual C++ 2008 Runtime",
  "play": "Deploy VC++",
  "event_loop": null,
  "task": "vcredist : Install Visual C++ 2008 Runtime",
  "role": "vcredist",
  "ignore_errors": null,
  "status": "failed",
  "module_name": "win_package",
  "created": "2016-09-29T13:55:09.750Z",
  "host_id": 852,
  "host_name": "targetserv",
  "id": 101457,
  "parent": 101456,
  "event": "Host Failed"
}
