### ISSUE TITLE
Template in block is not running filters properly

### ISSUE THREAD

**Issue by aj-jaswanth** [ansible/ansible-modules-extras#3105]
##### ISSUE TYPE

- Bug Report
##### COMPONENT NAME

blockinfile  module
##### ANSIBLE VERSION

```
ansible 2.3.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides

```
##### OS / ENVIRONMENT

Centos 6.7
##### SUMMARY

When using a template as block, if the template uses a filter regex_replace, the filter is not working as expected. The second argument to regex_replace has to be set as \1 instead of \1 to get it working.
##### STEPS TO REPRODUCE

```
play.yml

---
# vim: set ft=ansible:
- name: play test
  hosts: localhost
  gather_facts: no
  vars:
    url: "http://wibble.wobbble.com:9091/some/path?param=value&param2=othervalue"

  tasks:
      - name: abcd
        blockinfile:
         dest: temp
         marker: "#<!-- {mark} ANSIBLE MANAGED BLOCK erp-ssl -->"
         insertafter: "#erp-ssl"
         state: present
         block: |
            RewriteCond %{HTTP_HOST} ={{ url | regex_replace('(?:https?://)?([^/:]+)?.*', '\\1')  }}

```

##### EXPECTED RESULTS

file temp should contain :

```
#<!-- BEGIN ANSIBLE MANAGED BLOCK erp-ssl -->
RewriteCond %{HTTP_HOST} =wibble.wobbble.com
#<!-- END ANSIBLE MANAGED BLOCK erp-ssl -->
```
##### ACTUAL RESULTS

```
#<!-- BEGIN ANSIBLE MANAGED BLOCK erp-ssl -->
RewriteCond %{HTTP_HOST} =\1
#<!-- END ANSIBLE MANAGED BLOCK erp-ssl -->

```

```

```
