### ISSUE TITLE
Using win_regedit with binary values always results in "changed" state

### ISSUE THREAD

**Issue by jmighion** [ansible/ansible-modules-extras#3134]
##### ISSUE TYPE

- Bug Report
##### COMPONENT NAME

win_regedit
##### ANSIBLE VERSION

```
ansible 2.2.0.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
```
##### OS / ENVIRONMENT

OS : OS X 10.11.6
Managing: Windows 2008 R2 MS and Windows 2012 R2 DC
##### SUMMARY

Module changed data when it didn't need to when setting binary values without 2 bytes represented by hex.
I'm trying to set a registry data to 0 when the datatype is binary. The module reports the data changed unless you provide the data as data: hex:0,0 or data: 0x0,0x0. Windows represents those slightly differently in the registry. The default binary value is shown as 00, but passing 0x0,0x0 shows in Windows as 0000. Manually editing the registry allows 1 octect, but the module requires 2 to verify if a change is needed.
##### STEPS TO REPRODUCE

```
- name: "Set binary data"
  win_regedit: 
      key: 'HKLM:\System\CurrentControlSet\Control\Lsa'
      value: FullPrivilegeAuditing
      data: 0x0
      datatype: binary
```

##### EXPECTED RESULTS

After 2nd run : 

```
ok: [] => {
    "changed": false, 
    "data_changed": false, 
    "data_type_changed": false, 
    "invocation": {
        "module_name": "win_regedit"
    }
}
```
##### ACTUAL RESULTS

```
changed: [] => {
    "changed": true, 
    "data_changed": true, 
    "data_type_changed": false, 
    "invocation": {
        "module_name": "win_regedit"
    }
}
```
