### ISSUE TITLE
lvg fails if pvs option omitted when state=absent

### ISSUE THREAD

**Issue by jsok** [ansible/ansible-modules-extras#3140]
##### ISSUE TYPE
- Bug Report
##### COMPONENT NAME

`lvg` module
##### ANSIBLE VERSION

```
ansible 2.1.2.0
  config file = /Users/jsok/workspace/ansible.cfg
  configured module search path = Default w/o overrides
```
##### CONFIGURATION

N/A
##### OS / ENVIRONMENT

CentOS 6.7
##### SUMMARY

The `pvs` option is not necessary when `state=absent`, however failing to supply an empty string will cause the module to fail.
##### STEPS TO REPRODUCE

```

---
- name: Remove a volume group
  hosts: localhost
  tasks:
    - name: Remove vg01
      lvg:
        vg: vg01
        state: absent
```
##### EXPECTED RESULTS

The volume group is removed successfully.
##### ACTUAL RESULTS

```
fatal: [localhost]: FAILED! => {"changed": false, "failed": true, "module_stderr": "", "module_stdout": "Traceback (most recent call last):\r\n  File \"/tmp/ansible_tj_9JM/ansible_module_lvg.py\", line 255, in <module>\r\n    main()\r\n  File \"/tmp/ansible_tj_9JM/ansible_module_lvg.py\", line 140, in main\r\n    for idx, dev in enumerate(dev_list):\r\nUnboundLocalError: local variable 'dev_list' referenced before assignment\r\n", "msg": "MODULE FAILURE"}
```

**Comment by jsok** [comment]
To make the task succeed, it is necessary to include `pvs` like:

```
---

- name: Remove a volume group
  hosts: localhost
  tasks:
    - name: Remove vg01
      lvg:
        vg: vg01
        state: absent
        pvs: ''
```
