### ISSUE TITLE
f5 bigip_irule always reports changed

### ISSUE THREAD

**Issue by perbly** [ansible/ansible-modules-extras#3145]
##### ISSUE TYPE
- Bug Report
##### COMPONENT NAME

network/f5/bigip_irule.py
##### ANSIBLE VERSION

```
2.2.0
```
##### OS / ENVIRONMENT

N/A
##### SUMMARY

module always reports changed as status even if irule isn´t changed.
##### STEPS TO REPRODUCE

Add a irule using bigip_irule. Run the task again without any change.

```

---
- name: Add the iRule irule to partition partition_name
  bigip_irule:
      validate_certs: no
      content: "{{ lookup('template', '../files/irules/{{ f5_irule_name }}.irule') }}"
      module: "ltm"
      name: irule
      password: password
      server: 127.0.0.1
      state: enabled
      user: username
      partition: partition_name
  tags:
     - f5_irule
     - f5
  delegate_to: localhost
  when: f5_irule_name is defined
```

##### EXPECTED RESULTS

Check if state is present and don´t change anything.
##### ACTUAL RESULTS

Module reports changed

I´m not sure but i think the current content from F5 has an extra newline and that´s why the compare isn´t equal.

```

```
