### ISSUE TITLE
Certificate expiration date parsing fails in letsencrypt module

### ISSUE THREAD

**Issue by ptorkko** [ansible/ansible-modules-extras#3155]
##### ISSUE TYPE
- Bug report
##### COMPONENT NAME

letsencrypt

##### ANSIBLE VERSION

```
ansible 2.2.0.0
  config file = 
  configured module search path = Default w/o overrides
```

Installed from rc1 tarball `sudo python setup.py install` after purging previous .deb installation.
##### CONFIGURATION

Default everything
##### OS / ENVIRONMENT

Ubuntu 16.04, python 2.7, managed platform centos7
##### SUMMARY

letsencrypt module fails to parse dates from generated certificate I
##### STEPS TO REPRODUCE

letsencrypt module manages to create a certificate:

```

---
- hosts: somegroup
  tasks:
    - name: challenge
      letsencrypt:
        account_key: /etc/ssl/letsencrypt/letsencrypt2.key
        csr: /etc/ssl/letsencrypt/letsencrypt2.csr
        dest: /etc/ssl/letsencrypt/letsencrypt-temp.crt
      register: le_challenge

    - name: create challenge data
      copy:      
        dest: "/usr/share/nginx/html/{{ le_challenge['challenge_data']['example.org']['http-01']['resource'] }}"
        content: "{{ le_challenge['challenge_data']['example.org']['http-01']['resource_value'] }}"
      when: le_challenge|changed

    - name: create cert
      letsencrypt:
        account_key: /etc/ssl/letsencrypt/letsencrypt2.key
        csr: /etc/ssl/letsencrypt/letsencrypt2.csr
        dest: /etc/ssl/letsencrypt/letsencrypt-temp.crt
        data: "{{ le_challenge }}"
```

With above configuration the current result is:

```
FAILED! => {"changed": false, "failed": true, "msg": "No 'Not after' date found in /etc/ssl/letsencrypt/letsencrypt-temp.crt"}
```

If i open the cert like the module does, I can see:

```
$ openssl x509 -in letsencrypt-temp.crt -noout -text
Certificate:
    Data:
        Version: 3 (0x2)
        Serial Number:
            fa:5b:41:27:f9:65:85:43:9e:dc:b3:bd:a2:d1:45:6f:d0:3e
    Signature Algorithm: sha256WithRSAEncryption
        Issuer: CN=Fake LE Intermediate X1
        Validity
            Not Before: Oct 13 04:30:00 2016 GMT
            Not After : Jan 11 04:30:00 2017 GMT
        Subject: CN=example.org
        ... etc
```

Additionally, the following snippet works fine:

```
import re
import time
from datetime import datetime

src = """Certificate:
    Data:
        Version: 3 (0x2)
        Serial Number:
            fa:5b:41:27:f9:65:85:43:9e:dc:b3:bd:a2:d1:45:6f:d0:3e
    Signature Algorithm: sha256WithRSAEncryption
        Issuer: CN=Fake LE Intermediate X1
        Validity
            Not Before: Oct 13 04:30:00 2016 GMT
            Not After : Jan 11 04:30:00 2017 GMT
        Subject: CN=example.org"""

try:
    not_after_str = re.search(r"\s+Not After\s*:\s+(.*)", src).group(1)
    not_after = datetime.fromtimestamp(time.mktime(time.strptime(not_after_str,'%b %d %H:%M:%S %Y %Z')))
except ValueError as ve:
    print ve
print not_after
```

```
$ python test.py 
2017-01-11 04:30:00
```
