### ISSUE TITLE
Windows Core and Extra modules not found

### ISSUE THREAD

**Issue by davivcgarcia** [ansible/ansible-modules-extras#3163]
##### ISSUE TYPE
- Bug Report
##### COMPONENT NAME

module (win_shell and win_command)
##### ANSIBLE VERSION

```
$ ansible --version
ansible 2.1.2.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
```
##### CONFIGURATION

Default configuration for Fedora 24.
##### OS / ENVIRONMENT

Controller Node: GNU/Linux Fedora 24 x86-64
Managed Node: Microsoft Windows Server 2012 R2 64bits
##### SUMMARY

The modules **win_command** and **win_shell** are not included in the distribution of Ansible core.
##### STEPS TO REPRODUCE

Try to run any play including any of the listed modules, **win_command** and **win_shell**.

```

---
- name: Install Apache Server from an MSI package.
  hosts: windows

  tasks:
    - name: Download the Apache installer
      win_get_url:
        url: 'https://archive.apache.org/dist/httpd/binaries/win32/httpd-2.2.25-win32-x86-no_ssl.msi'
        dest: 'C:\Users\Administrator\Downloads\httpd-2.2.25-win32-x86-no_ssl.msi'

    - name: Install Apache MSI package
      win_package:
        path: 'C:\Users\Administrator\Downloads\httpd-2.2.25-win32-x86-no_ssl.msi'
        product_id: "{85262A06-2D8C-4BC1-B6ED-5A705D09CFFC}"

    - name: Activate Apache as a system service
      win_command: httpd.exe -k install
      args:
        chdir: 'C:\Program Files (x86)\Apache Software Foundation\Apache2.2\bin'

    - name: Start Apache service
      win_command: httpd.exe -k start
      args:
        chdir: 'C:\Program Files (x86)\Apache Software Foundation\Apache2.2\bin'

    - name: Create firewall rule for incoming TCP/80
      win_firewall_rule:
        name: Allow incoming HTTP traffic
        enable: yes
        state: present
        localport: 80
        action: allow
        direction: In
protocol: TCP
```

https://github.com/davivcgarcia/ansible-windows/blob/master/install-package.yml
##### EXPECTED RESULTS

The expected result is to have both modules executing the command on host cmd.exe.
##### ACTUAL RESULTS

The run fails as the modules are not included in the Ansible core distribution. Looking for it manually, I couldn't find it either.

```
$ ansible-playbook -i inventory.ini install-package.yml -vvv
Using /etc/ansible/ansible.cfg as config file
ERROR! no action detected in task. This often indicates a misspelled module name, or incorrect module path.

The error appears to have been in '/home/dvercill/Projects/ansible-windows/install-package.yml': line 16, column 7, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:


    - win_shell: httpd.exe -k install
      ^ here


The error appears to have been in '/home/dvercill/Projects/ansible-windows/install-package.yml': line 16, column 7, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:


    - win_shell: httpd.exe -k install
      ^ here
```
