### ISSUE TITLE
Creating new gluster volume via Ansibale (Tower) fails

### ISSUE THREAD

**Issue by gwachter77** [ansible/ansible-modules-extras#3169]
##### ISSUE TYPE
- Bug Report
##### COMPONENT NAME

gluster_volume
##### ANSIBLE VERSION

```
ansible 2.1.0.0
```
##### CONFIGURATION

No changes to ansible.cfg and no environment variables
##### OS / ENVIRONMENT

RHEL7.2
ansible-2.1.0.0-1.el7.noarch
ansible-tower-3.0.1-1.el7.centos.x86_64
##### SUMMARY

Creating a new gluster volume using gluster_volume in Ansible on freshly installed gluster servers fails with the following error:

"msg": "error running gluster (/sbin/gluster volume create tri-repvol01-sdb replica 3 transport tcp 10.0.0.161:/glusterfs/brick-sdb 10.0.0.162:/glusterfs/brick-sdb 10.0.0.163:/glusterfs/brick-sdb force) command (rc=1): volume create: tri-repvol01-sdb: failed: Host 10.0.0.163 is not in 'Peer in Cluster' state\n"
##### STEPS TO REPRODUCE
- Install glusterfs-server on 3 RHEL systems (where /var/lib/glusterd doesn't exist)
- Create a new brick filesystem on all 3 nodes
- Create a volume via Ansible (via command line or via Tower)

After the failure a 'gluster peer status' shows all members 'Connected', so it seems this is a timing issue where the 'gluster volume create' is issued before all members are connected.

Possible fix:
This patch to gluster_volume.py makes sure the probe() function always waits for the peer to join the cluster:

```
--- /usr/lib/python2.7/site-packages/ansible/modules/extras/system/gluster_volume.py.org      2016-05-25 15:01:02.000000000 +0200
+++ /usr/lib/python2.7/site-packages/ansible/modules/extras/system/gluster_volume.py    2016-10-14 08:18:49.631562193 +0200
@@ -251,7 +251,7 @@
 def probe(host, myhostname):
     global module
     out = run_gluster([ 'peer', 'probe', host ])
-    if not out.find('localhost') and not wait_for_peer(host):
+    if not wait_for_peer(host) and not out.find('localhost'):
         module.fail_json(msg='failed to probe peer %s on %s' % (host, myhostname))
     changed = True

```

Ansible code:

```
    - name: Configure Gluster volume.
      gluster_volume:
        state: present
        name: "{{ gluster_volume_name }}-{{ item.item.key }}"
        brick: "{{ gluster_brick_dir }}-{{ item.item.key }}"
        replicas: "{{ gluster_replicas }}"
        cluster: "{{ groups.glusterfs_group | join(',') }}"
        host: "{{ inventory_hostname }}"
        force: yes
      run_once: true
      with_items: "{{ mkfs_action.results }}"
      when: ({{ item.changed }} == true)
```
##### EXPECTED RESULTS

A new gluster volume, visible with 'gluster volume list'
##### ACTUAL RESULTS

```

```
