### ISSUE TITLE
[Enhancement] Add a "provider" parameter to snmp_facts module

### ISSUE THREAD

**Issue by jean-christophe-manciot** [ansible/ansible-modules-extras#3176]
##### ISSUE TYPE
- Feature Idea
##### COMPONENT NAME

snmp_facts
##### ANSIBLE VERSION

```
ansible 2.3.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
```
##### CONFIGURATION

inventory   = ./hosts
gathering = explicit
roles_path = /home/actionmystique/Program-Files/Ubuntu/Ansible/git-Ansible/roles
private_role_vars = yes
log_path = /var/log/ansible.log
fact_caching = redis
fact_caching_timeout = 86400
retry_files_enabled = False
##### OS / ENVIRONMENT
- host: Ubuntu 16.04 4.4.0
- target: **all network devices**
##### SUMMARY

snmp_facts does not offer a provider parameter, unlike many other networking modules from Cisco, Arista, Juniper, and so on.... This feature would be very useful, allowing us to hand over only one structured variable which can be reused in other roles. 
This feature should be extended to all network, system, ... modules.
##### STEPS TO REPRODUCE

Structure which could be handed over as "**provider**": snmp.ssh

``````
snmp
...
        ssh:
          transport: cli 
          host: "{{ ansible_host }}"
          # Username is part of the following required group in v3
          group_name: admin
          # Username required if version is v3
          username: admin
          # New SNMP Version to use
          version: v3
          # community string, required if version is v1/v2c - up to 32 alphanumeric characters long. Spaces are not permitted.
          community: xxxxxxxx
          # Authentication level, required if version is v3
          level: authPriv
          # Authentication key, required if version is v3
          authkey: xxxxxxxx
          # Type of password
          authkey_type: 
          # Hashing algoritm, required if version is v3
          integrity: sha
          # Encryption algoritm, required if level is authPriv
          privacy: aes
          # Encryption key, required if version is authPriv
          privkey: xxxxxxxx```
``````
