### ISSUE TITLE
policy parameter of the sqs_queue module breaks idempotence

### ISSUE THREAD

**Issue by danvaida** [ansible/ansible-modules-extras#3220]
##### ISSUE TYPE
- Bug Report
##### COMPONENT NAME

sqs_queue
##### ANSIBLE VERSION

```
ansible --version
ansible 2.3.0 (devel 5215832f15) last updated 2016/10/17 17:34:50 (GMT +200)
  lib/ansible/modules/core: (detached HEAD 6f15dfd464) last updated 2016/10/17 17:34:58 (GMT +200)
  lib/ansible/modules/extras: (detached HEAD 3f77bb6857) last updated 2016/10/17 17:35:04 (GMT +200)
  config file = /role/tests/ansible.cfg
  configured module search path = Default w/o overrides
```
##### CONFIGURATION

n/a
##### OS / ENVIRONMENT

wheezy on control machine.
##### SUMMARY

Module's idempotence is broken if the policy parameter is used.
##### STEPS TO REPRODUCE

```
- name: Queues should be added
  sqs_queue:
    region: "{{ item.region }}"
    aws_access_key: "{{ item.access_key | default(omit) }}"
    aws_secret_key: "{{ item.secret_key | default(omit) }}"
    profile: "{{ item.boto_profile | default(omit) }}"
    name: "{{ item.name }}"
    default_visibility_timeout: "{{ item.default_visibility_timeout | default(omit) }}"
    delivery_delay: "{{ item.delivery_delay | default(omit) }}"
    maximum_message_size: "{{ item.maximum_message_size | default(omit) }}"
    message_retention_period: "{{ item.message_retention_period | default(omit) }}"
    policy: "{{ item.policy | default(omit) }}"
    receive_message_wait_time: "{{ item.receive_message_wait_time | default(omit) }}"
    redrive_policy: "{{ item.redrive_policy | default(omit) }}"
    state: present
  with_items: "{{ sqs_to_add }}"
  tags:
    - sqs
```

```
      sqs_to_add:
        - region: 'eu-central-1'
          name: 'test-one'
          default_visibility_timeout: 30
          delivery_delay: 0
          maximum_message_size: 262144
          message_retention_period: 86400
          receive_message_wait_time: 0
          policy:
            Id: "arn:aws:sqs:eu-central-1:{{ aws_account }}:test-one/SQSDefaultPolicy"
            Statement:
              Effect: Allow
              Principal: '*'
              Action: 'SQS:*'
              Resource: "arn:aws:sqs:eu-central-1:{{ aws_account }}:test-one"
          redrive_policy:
            maxReceiveCount: 3
            deadLetterTargetArn: "arn:aws:sqs:eu-central-1:{{ aws_account }}:test-one-dead"
```
##### EXPECTED RESULTS

If ran multiple times, the task should be idempotent.
##### ACTUAL RESULTS

Removing the policy parameter from the variable renders the task idempotent.
Adding it, as in the above example, makes the task always report as changed.

```
TASK [../../role : Queues should be added] *************************************
changed: [localhost] => (item={u'message_retention_period': 86400, u'name': u'test-one', u'delivery_delay': 0, u'default_visibility_timeout': 30, u'region': u'eu-central-1', u'maximum_message_size': 262144, u'policy': {u'Id': u'arn:aws:sqs:eu-central-1:xxx:test-one/SQSDefaultPolicy', u'Statement': {u'Action': u'SQS:*', u'Resource': u'arn:aws:sqs:eu-central-1:xxx:test-one', u'Effect': u'Allow', u'Principal': u'*'}}, u'redrive_policy': {u'maxReceiveCount': 3, u'deadLetterTargetArn': u'arn:aws:sqs:eu-central-1:xxx:test-one-dead'}, u'receive_message_wait_time': 0})
```
