### ISSUE TITLE
Can't delete a VM with vmware_guest module

### ISSUE THREAD

**Issue by phips** [ansible/ansible-modules-extras#3237]
##### ISSUE TYPE
- Bug Report
##### COMPONENT NAME

vmware_guest
##### ANSIBLE VERSION

```
(pip)c7:ansible-demos$ ansible --version
ansible 2.2.0.0
  config file = /home/vagrant/src/ansible-demos/ansible.cfg
  configured module search path = Default w/o overrides

(pip)c7:ansible-demos$ rpm -q ansible
ansible-2.2.0.0-100.git201610182035.bce9bfc.HEAD.el7.centos.noarch
```
##### OS / ENVIRONMENT

(pip)c7:ansible-demos$ cat /etc/centos-release
CentOS Linux release 7.1.1503 (Core) 
##### SUMMARY

Trying to delete a VM by setting 'state: absent' fails with vmware_guest module. First it fails if 'template' switch is not set, second it fails by trying to clone when 'template' is set. Also, if just `state: absent` is set before trying to power off, then nothing happens at all.
##### STEPS TO REPRODUCE

```
      - name: Shutdown VM first if delete required
        vmware_guest:
          validate_certs: False
          hostname: "{{ vcenter_hostname }}"
          username: "{{ vcenter_user }}"
          password: "{{ vcenter_pass }}"
          name: "{{ name }}"
          state: "poweredoff"
          template: ""
      when: state == "absent"

    - name: Set VM to desired state
      vmware_guest:
        validate_certs: False
        hostname: "{{ vcenter_hostname }}"
        username: "{{ vcenter_user }}"
        password: "{{ vcenter_pass }}"
        name: "{{ name }}"
        state: "{{ state }}"
        template: ""
```
##### EXPECTED RESULTS

VM powered off and deleted.
##### ACTUAL RESULTS

Nothing if just state: absent, failure if try to power off...

```
TASK [Shutdown VM first if delete required] ************************************
fatal: [linux]: FAILED! => {"changed": true, "failed": true, "msg": "The name 'ssp.box' already exists."}
```

Template missing...

```
TASK [Shutdown VM first if delete required] ************************************
fatal: [linux]: FAILED! => {"changed": false, "failed": true, "module_stderr": "/home/vagrant/pip/lib/python2.7/site-packages/requests/packages/urllib3/connectionpool.py:789: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.org/en/latest/security.html\n  InsecureRequestWarning)\nTraceback (most recent call last):\n  File \"/tmp/ansible_5ZzRF6/ansible_module_vmware_guest.py\", line 959, in <module>\n    main()\n  File \"/tmp/ansible_5ZzRF6/ansible_module_vmware_guest.py\", line 937, in main\n    wait_for_ip=module.params['wait_for_ip_address']\n  File \"/tmp/ansible_5ZzRF6/ansible_module_vmware_guest.py\", line 494, in deploy_template\n    template = get_obj(self.content, [vim.VirtualMachine], self.params['template'])\nKeyError: 'template'\n", "module_stdout": "", "msg": "MODULE FAILURE"}
```
