### ISSUE TITLE
Make authorize in ASA more user friendly

### ISSUE THREAD

**Issue by ogenstad** [ansible/ansible-modules-extras#3260]
Saw this a few days ago. I hope to find time to fix it, but haven't yet.
##### ISSUE TYPE
- Bug Report
- Feature Idea
##### COMPONENT NAME
- asa_acl
- asa_config
- asa_command
##### ANSIBLE VERSION

```
$ ansible --version
ansible 2.3.0 (devel 38d0f77a0f) last updated 2016/10/18 18:39:48 (GMT +200)
  lib/ansible/modules/core: (devel ecc4029753) last updated 2016/10/18 18:41:14 (GMT +200)
  lib/ansible/modules/extras: (devel 3f77bb6857) last updated 2016/10/18 18:41:28 (GMT +200)
  config file = /Users/patrick/src/tests/ansible-asa/ansible.cfg
  configured module search path = Default w/o overrides
```
##### CONFIGURATION

N/A
##### OS / ENVIRONMENT

N/A
##### SUMMARY

Unlike Cisco IOS the Cisco ASA cli doesn't ignore the `enable` command if the user already is in enable mode.

```
ns2903-asa-02# enable
                ^
ERROR: % Invalid input detected at '^' marker.
ns2903-asa-02#
```
##### STEPS TO REPRODUCE

Code in ASA

```
aaa authentication ssh console LOCAL
aaa authentication enable console LOCAL
aaa authorization exec LOCAL auto-enable
username cisco password 3USUcOPFUiMCO4Jk encrypted privilege 15
```

Playbook:

```

---
-  hosts: firewall
   connection: local
   gather_facts: false

   tasks:
     - name: Show version
       asa_command:
         host: "{{ inventory_hostname }}"
         auth_pass: cisco
         username: cisco
         password: cisco
         authorize: yes
         commands:
           - show run
```
##### EXPECTED RESULTS

It would be more userfriendly if [asa.py](https://github.com/ansible/ansible/blob/devel/lib/ansible/module_utils/asa.py) either looked at the prompt first and didn't run `enable` if the prompt ended with `#` instead of `>`, another option would be to ignore the warning when this command was issued.
##### ACTUAL RESULTS

```
$ ansible-playbook -i hosts asa-sanity.yml

PLAY [firewall] ****************************************************************

TASK [Show version] ************************************************************
fatal: [172.29.50.2]: FAILED! => {"changed": false, "failed": true, "msg": "matched error in response: enable\r\n                ^\r\nERROR: % Invalid input detected at '^' marker.\r\n"}
```
