### ISSUE TITLE
zabbix_host result is always 'changed' without zabbix proxy passed 

### ISSUE THREAD

**Issue by tbondarchuk** [ansible/ansible-modules-extras#3280]
##### ISSUE TYPE
- Bug Report
##### COMPONENT NAME

monitoring/zabbix_host.py
##### ANSIBLE VERSION

```
ansible 2.1.2.0
  config file =
  configured module search path = Default w/o overrides
```
##### OS / ENVIRONMENT

N/A
##### SUMMARY

When no zabbix proxy is set in _zabbix_host_ task, result is always '_changed_' on repeating runs, even though host's configuration is the same.
##### STEPS TO REPRODUCE

Run the following playbook twice:

```

---
- hosts: localhost
  connection: local
  gather_facts: no

  tasks:
    - name: Add host to zabbix
      zabbix_host:
        server_url: "http://localhost"
        login_user: Admin
        login_password: zabbix
        host_name: "host-1.example.com"
        host_groups: "Virtual machines"
        status: enabled
        state: present
        inventory_mode: manual
        interfaces:
         - type: 1
           main: 1
           useip: 1
           ip: "192.168.1.2"
           dns: "host-1.example.com"
           port: 10050
```
##### EXPECTED RESULTS

On second run task's result should be _'ok'_.
##### ACTUAL RESULTS

On second and following runs task's result is always _'changed'_

```
No config file found; using defaults
 [WARNING]: Host file not found: /etc/ansible/hosts

 [WARNING]: provided hosts list is empty, only localhost is available


PLAYBOOK: test.yml *************************************************************
1 plays in test.yml

PLAY [localhost] ***************************************************************

TASK [Add host to zabbix] ******************************************************
task path: /Users/alius/Projects/zabbix_host/test.yml:8
<127.0.0.1> ESTABLISH LOCAL CONNECTION FOR USER: alius
<127.0.0.1> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo $HOME/.ansible/tmp/ansible-tmp-1477308826.26-116453851164426 `" && echo ansible-tmp-1477308826.26-116453851164426="` echo $HOME/.ansible/tmp/ansible-tmp-1477308826.26-116453851164426 `" ) && sleep 0'
<127.0.0.1> PUT /var/folders/s_/ttdgq1112cd91sshfjcy3x7h0000gn/T/tmpDmdsru TO /Users/alius/.ansible/tmp/ansible-tmp-1477308826.26-116453851164426/zabbix_host
<127.0.0.1> EXEC /bin/sh -c 'chmod u+x /Users/alius/.ansible/tmp/ansible-tmp-1477308826.26-116453851164426/ /Users/alius/.ansible/tmp/ansible-tmp-1477308826.26-116453851164426/zabbix_host && sleep 0'
<127.0.0.1> EXEC /bin/sh -c 'LANG=en_US.UTF-8 LC_ALL=en_US.UTF-8 LC_MESSAGES=en_US.UTF-8 /usr/local/opt/python/bin/python2.7 /Users/alius/.ansible/tmp/ansible-tmp-1477308826.26-116453851164426/zabbix_host; rm -rf "/Users/alius/.ansible/tmp/ansible-tmp-1477308826.26-116453851164426/" > /dev/null 2>&1 && sleep 0'
changed: [localhost] => {"changed": true, "invocation": {"module_args": {"force": true, "host_groups": ["Virtual machines"], "host_name": "host-1.example.com", "http_login_password": null, "http_login_user": null, "interfaces": [{"dns": "host-1.example.com", "interfaceid": "33", "ip": "192.168.1.2", "main": 1, "port": 10050, "type": 1, "useip": 1}], "inventory_mode": "manual", "link_templates": null, "login_password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER", "login_user": "Admin", "proxy": null, "server_url": "http://localhost", "state": "present", "status": "enabled", "timeout": 10}, "module_name": "zabbix_host"}, "result": "Successfully update host host-1.example.com (192.168.1.2) and linked with template 'None'"}

PLAY RECAP *********************************************************************
localhost                  : ok=1    changed=1    unreachable=0    failed=0
```
