### ISSUE TITLE
win_chocolatey upgrade successfully even when the package with required version is missing.

### ISSUE THREAD

**Issue by maxim0r** [ansible/ansible-modules-extras#3287]
##### ISSUE TYPE
- Feature Idea
##### COMPONENT NAME

win_chocolatey
##### ANSIBLE VERSION

```
ansible 2.1.0.0
```
##### SUMMARY

Upgrade task successfully even when the package with required version is missing.
##### STEPS TO REPRODUCE

```
win_chocolatey:
  name: testpack
  version: 0.2
  source: http://example.com
  upgrade: yes

```

In this example, currently installed version 0.1 and package with version 0.2 is absent on source repo.
##### EXPECTED RESULTS

In most cases, the task should stop with an error.
##### ACTUAL RESULTS

Task successfully.

--failonunfound key for choco upgrade command can help. 
It can be implemented as a module option or to make the default.
