### ISSUE TITLE
npm always installing even if package is installed already

### ISSUE THREAD

**Issue by shaharmor** [ansible/ansible-modules-extras#3290]
##### ISSUE TYPE
- Bug Report
##### COMPONENT NAME

npm
##### ANSIBLE VERSION

```
ansible 2.1.2.0
```
##### CONFIGURATION

```
[defaults]
host_key_checking = False
```
##### OS / ENVIRONMENT

N/A
##### SUMMARY

When using the npm module to install a package globally, it doesn't check if the module is installed before installing, making it always "change" the module.
##### STEPS TO REPRODUCE

Run the follwing task multiple timesL

```
- name: update npm
  npm:
   name: npm
   global: yes
   state: present
   version: '3.10.8'
   production: yes
```
##### EXPECTED RESULTS

First run: changed
Second run: ok
##### ACTUAL RESULTS

First run: changed
Second run: changed
