### ISSUE TITLE
npm is not "becoming" root

### ISSUE THREAD

**Issue by shaharmor** [ansible/ansible-modules-extras#3291]
##### ISSUE TYPE
- Bug Report
##### COMPONENT NAME

npm
##### ANSIBLE VERSION

```
ansible 2.1.2.0
```
##### CONFIGURATION

```
[defaults]
host_key_checking = False

[ssh_connection]
pipelining = True
ssh_args = -o ForwardAgent=yes -o ControlMaster=auto -o ControlPersist=60s
control_path = /tmp/%%h-%%p-%%r
```
##### OS / ENVIRONMENT

OSX 10.10.5
##### SUMMARY

When installing anything with the npm module, its setting the permissions of all the modules files/directories to the user which was used to connect to the remote host, regardless of whether become is set or not.
##### STEPS TO REPRODUCE
1. Run the following task

```
- name: install pm2
  become: yes
  npm:
    name: pm2
    global: yes
    production: yes
    state: present
```
1. check permissions on the module directory/files (`/usr/lib/node_modules/pm2`)
##### EXPECTED RESULTS

Files/directories should have root user permissions
##### ACTUAL RESULTS

Files/directories have ssh user permissions
