### ISSUE TITLE
kubernetes.py ImportError: No module named yaml

### ISSUE THREAD

**Issue by ahuffman** [ansible/ansible-modules-extras#3301]
##### ISSUE TYPE

- Bug Report
##### COMPONENT NAME

kubernetes.py
##### ANSIBLE VERSION

```
ansible 2.1.2.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides

```
##### SUMMARY

Attempting to run the kubernetes module to create a namespace on my cluster.
##### STEPS TO REPRODUCE

```
 hosts: kubmst01rhel7
  remote_user: root
  tasks:
    - name: Create Wordpress Namespace
      kubernetes:
        api_endpoint: 192.168.122.40
        insecure: true
        inline_data:
          kind: Namespace
          apiVersion: v1
          metadata:
            name: wordpress-demo
        state: present

```

##### EXPECTED RESULTS

Creation of a namespace on my kubernetes cluster
##### ACTUAL RESULTS

```
fatal: [kubmst01rhel7]: FAILED! => {"changed": false, "failed": true, "module_stderr": "", "module_stdout": "Traceback (most recent call last):\r\n  File \"/tmp/ansible_5_IWnL/ansible_module_kubernetes.py\", line 153, in <module>\r\n    import yaml\r\nImportError: No module named yaml\r\n", "msg": "MODULE FAILURE"}

```
