### ISSUE TITLE
logentries module fails to correctly unfollow logs

### ISSUE THREAD

**Issue by jmehnle** [ansible/ansible-modules-extras#3307]
##### ISSUE TYPE
- Bug Report
##### COMPONENT NAME

`logentries` module
##### ANSIBLE VERSION

```
ansible 1.9.3
  configured module search path = None
```

(but broken in Ansible 2 as well)
##### OS / ENVIRONMENT

Managing Ubuntu 14.04 and 16.04.
`logentries` agent 1.4.39 (latest as of 2016-10-27), but tried various versions.
##### SUMMARY

The `logentries` module fails to correctly unfollow logs. The `le` command it issues is `le rm <logfile-path>`, but that only results in an error message:

```
failed: [<hostname>] => (item={'path': '/var/log/diskutil.log', 'state': 'absent', 'name': 'Diskutil'}) => {"failed": true, "item": {"name": "Diskutil", "path": "/var/log/diskutil.log", "state": "absent"}}
msg: failed to remove '/var/log/diskutil.log': Error: Resource var not found.
```

The play in the playbook is:

```
- name: logentries
  hosts: all
  sudo: yes
  roles:
    - role: logentries
      logentries_logs:
        - …
        - name: "Diskutil"
          path: "/var/log/diskutil.log"
          state: absent
```

The relevant task is:

```
- name: Follow logs
  logentries: path={{ item.path }} state={{ item.state | default('present') }}
  with_items: logentries_logs
```

According to https://docs.logentries.com/docs/linux-agent and https://github.com/logentries/le/issues/66, the correct argument to pass to `le rm` is not the log file's file system path but a virtual path composed of 1. the prefix `hosts/`, 2. the fully qualified name of the host, and 3. the symbolic name of the log file specified during the initial `follow` action (defaulting to the base name of the log file path), e.g., `hosts/<hostname>/diskutil.log`.
