### ISSUE TITLE
s3_bucket error: Your previous request to create the named bucket succeeded and you already own it

### ISSUE THREAD

**Issue by pako-pl** [ansible/ansible-modules-extras#3354]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
s3_bucket

##### ANSIBLE VERSION
ansible 2.1.2.0
ansible 2.2.0.0

##### OS / ENVIRONMENT
Linux Debian

##### SUMMARY
Trying to run s3_bucket task when the bucket already exists results in an "Your previous request to create the named bucket succeeded and you already own it" error.

##### STEPS TO REPRODUCE
Run more than once the following task:

```
- s3_bucket:
    name: my-test-bucket-12
    state: present
    region: eu-central-1
    versioning: yes
    delegate_to: management-server
    run_once: true
```

##### EXPECTED RESULTS
No error should be returned if the bucket already exists and is owned by the AWS account trying to create it. The "BucketAlreadyOwnedByYou" error returned by Boto can probably be ignored. However, the "versioning" setting for the bucket should be updated if necessary.

It's possible that this error is returned only for buckets in regions other that US Standard:

"BucketAlreadyOwnedByYou errors will only be returned outside of the US Standard region. Inside the US Standard region (i.e. when you don't specify a location constraint), attempting to recreate a bucket you already own will succeed." http://stackoverflow.com/a/16561451/226640

We use the `eu-central-1` region.

##### ACTUAL RESULTS
```
fatal: [dev -> management-server]: FAILED! => {"changed": false, "failed": true, "msg": "Your previous request to create the named bucket succeeded and you already own it."}
```
