### ISSUE TITLE
haproxy module failure after upgrade to ansible 2.2.0

### ISSUE THREAD

**Issue by willww64** [ansible/ansible-modules-extras#3364]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
- haproxy module

##### ANSIBLE VERSION

```
2.2.0
```

##### OS / ENVIRONMENT

Ubuntu 16.04

##### SUMMARY

After upgrade to ansible 2.2.0, haprox module execution failed. But the weight has been changed though.

##### STEPS TO REPRODUCE

```yml
  - name: "Set {{ backend }}/{{ host }} Weight to {{ weight }}"
    haproxy:
      state: enabled
      backend: "{{ backend }}"
      host: "{{ host }}"
      weight: "{{ weight }}"
      socket: "{{ socket }}"
    delegate_to: "{{ item }}"
    with_items: "{{ groups.upay }}"
```

##### EXPECTED RESULTS

Weight changed and no failure message.

##### ACTUAL RESULTS

I've formated the json output message.
```json
"failed: [s1-payment-001 -> s1-upay-001] (item=s1-upay-001) =>"
{
  "failed": true, 
  "item": "s1-upay-001", 
  "module_stderr": "Shared connection to s1-upay-001 closed.
", 
  "module_stdout": "Traceback (most recent call last):
  File \"/tmp/ansible_gz8hxE/ansible_module_haproxy.py\", line 350, in <module>
    main()
  File \"/tmp/ansible_gz8hxE/ansible_module_haproxy.py\", line 345, in main
    ansible_haproxy.act()
  File \"/tmp/ansible_gz8hxE/ansible_module_haproxy.py\", line 317, in act
    self.module.exit_json(**self.command_results)
  File \"/tmp/ansible_gz8hxE/ansible_modlib.zip/ansible/module_utils/basic.py\", line 1799, in exit_json
  File \"/tmp/ansible_gz8hxE/ansible_modlib.zip/ansible/module_utils/basic.py\", line 388, in remove_values
  File \"/tmp/ansible_gz8hxE/ansible_modlib.zip/ansible/module_utils/basic.py\", line 388, in <genexpr>
  File \"/tmp/ansible_gz8hxE/ansible_modlib.zip/ansible/module_utils/basic.py\", line 399, in remove_values
TypeError: Value of unknown type: <type 'itertools.imap'>, <itertools.imap object at 0x7ff363f2af90>
", 
  "msg": "MODULE FAILURE"
}
```
