### ISSUE TITLE
elasticsearch_plugin does not work with Elasticsearch 5.x

### ISSUE THREAD

**Issue by walbert947** [ansible/ansible-modules-extras#3376]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

elasticsearch_plugin module

##### ANSIBLE VERSION

```
ansible 2.2.0.0
  config file = /home/william/.ansible.cfg
  configured module search path = ['/usr/share/ansible', 'playbooks/library']

```

##### OS / ENVIRONMENT

The control host is running Ubuntu 16.04.
The target hosts are running CentOS 7.2 and CentOS 6.8

##### SUMMARY

The elasticsearch_plugin fails to run on Elasticsearch 5.x.

##### STEPS TO REPRODUCE

I tried two variations.

The first was a simple task:
```yaml
- name: Install Elasticsearch S3 repository plugin (ES 5.x)
  elasticsearch_plugin:
    name: repository-s3
```

The second was a task with the binary path specified:
```yaml
- name: Install Elasticsearch S3 repository plugin (ES 5.x)
  elasticsearch_plugin:
    name: repository-s3
    plugin_bin: '/usr/share/elasticsearch/bin/elasticsearch-plugin'
```

##### EXPECTED RESULTS

It would install the repository-s3 plugin.

##### ACTUAL RESULTS

The simple task (without specifying the binary path) produced the following output:
```
fatal: [es-c6-5]: FAILED! => {
    "changed": false, 
    "cmd": "/usr/share/elasticsearch/bin/plugin install repository-s3 --timeout 1m", 
    "failed": true, 
    "invocation": {
        "module_args": {
            "name": "repository-s3", 
            "plugin_bin": "/usr/share/elasticsearch/bin/plugin", 
            "plugin_dir": "/usr/share/elasticsearch/plugins/", 
            "proxy_host": null, 
            "proxy_port": null, 
            "state": "present", 
            "timeout": "1m", 
            "url": null, 
            "version": null
        }, 
        "module_name": "elasticsearch_plugin"
    }, 
    "msg": "[Errno 2] No such file or directory", 
    "rc": 2
}
```

The task where I explicitly provided the plugin binary path on Elasticsearch 5.x provided the following output:
```
fatal: [es-c6-5]: FAILED! => {
    "changed": false, 
    "failed": true, 
    "invocation": {
        "module_args": {
            "name": "repository-s3", 
            "plugin_bin": "/usr/share/elasticsearch/bin/elasticsearch-plugin", 
            "plugin_dir": "/usr/share/elasticsearch/plugins/", 
            "proxy_host": null, 
            "proxy_port": null, 
            "state": "present", 
            "timeout": "1m", 
            "url": null, 
            "version": null
        }, 
        "module_name": "elasticsearch_plugin"
    }, 
    "msg": "A tool for managing installed elasticsearch plugins\n\nCommands\n--------\nlist - Lists installed elasticsearch plugins\ninstall - Install a plugin\nremove - Removes a plugin from elasticsearch\n\nNon-option arguments:\ncommand              \n\nOption         Description        \n------         -----------        \n-h, --help     show help          \n-s, --silent   show minimal output\n-v, --verbose  show verbose output\nERROR: timeout is not a recognized option\n"
}
```
