### ISSUE TITLE
firewalld requirements on Centos 7

### ISSUE THREAD

**Issue by madrover** [ansible/ansible-modules-extras#3387]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
firewalld module

##### ANSIBLE VERSION

```
ansible 2.1.0.0
  config file =
  configured module search path = Default w/o overrides
```

##### OS / ENVIRONMENT

- Centos 7

##### SUMMARY

The [module documentation](http://docs.ansible.com/ansible/firewalld_module.html) states that: _Requires the python2 bindings of firewalld, which may not be installed by default if the distribution switched to python 3_ but these python2 bindings of firewalld do not seem to be available on Centos 7 and makes its execution fail. 

##### STEPS TO REPRODUCE
Execute the following statement:
```
- name: Allow http port in firewall
  firewalld:
    state: enabled
    permanent: true
    port: "{{ apache_http_port }}/tcp"
```

##### EXPECTED RESULTS

```
TASK [ansible-apache : Allow http port in firewall]
ok: [ansible]
```
##### ACTUAL RESULTS

```
fatal: [ansible]: FAILED! => {"changed": false, "failed": true, "msg": "firewalld and its python 2 module are required for this module"}
```
