### ISSUE TITLE
New OpenStack os_server module is not idempotent for metadata

### ISSUE THREAD

**Issue by rcarrillocruz** [ansible/ansible-modules-extras#340]
I've been using new OpenStack os_server modules from pull request https://github.com/ansible/ansible-modules-extras/pull/92.

I've noticed that if you create an instance without metadata at first and later you run the same play but adding metadata it won't be added to the instance.
This is the playbook:

```
- name: launch a compute instance
  hosts: localhost
  connection: local
  tasks:
    - name: launch a compute instance
      os_server:
          state: present
          auth:
            auth_url: "{{ lookup('env', 'OS_AUTH_URL') }}"
            username: "{{ lookup('env', 'OS_USERNAME') }}"
            password: "{{ lookup('env', 'OS_PASSWORD') }}"
            project_name: "{{ lookup('env', 'OS_TENANT_NAME') }}"
          name: test_instance
          region_name: region-b.geo-1
          availability_zone: az2
          image: 9d25fe2d-cf31-4b05-8c58-f238ec78e633
          key_name: workstation
          timeout: 200
          flavor: standard.small
          nics:
            - net-name: rcarrillocruz-network
          security_groups: default
          auto_floating_ip: yes
  #        meta:
  #          group: test
```

This is the first play result (with the meta lines commented):

```
(ansible-playground)ricky@virtualbox:~/ansible-playground$ ansible-playbook -i infra-ansible/hosts deploy_instance.yml

PLAY [launch a compute instance] **********************************************

GATHERING FACTS ***************************************************************
ok: [localhost]

TASK: [launch a compute instance] *********************************************
changed: [localhost]

PLAY RECAP ******************************************************************** 
localhost                  : ok=2    changed=1    unreachable=0    failed=0 
```

And this is the second play (with the meta lines uncommented):

```
(ansible-playground)ricky@virtualbox:~/ansible-playground$ ansible-playbook -i infra-ansible/hosts deploy_instance.yml -vv

PLAY [launch a compute instance] ********************************************** 

GATHERING FACTS *************************************************************** 
<localhost> REMOTE_MODULE setup
ok: [localhost]

TASK: [launch a compute instance] ********************************************* 
<localhost> REMOTE_MODULE os_server region_name=region-b.geo-1 flavor=standard.small security_groups=default state=present image=9d25fe2d-cf31-4b05-8c58-f238ec78e633 key_name=workstation availability_zone=az2 name=test_instance
ok: [localhost] => {"changed": false, "id": "247dc0ed-deb0-49a5-9960-89c7dbcb64d7", "openstack": {"HUMAN_ID": true, "NAME_ATTR": "name", "OS-EXT-AZ:availability_zone": "az2", "OS-EXT-STS:power_state": 1, "OS-EXT-STS:task_state": null, "OS-EXT-STS:vm_state": "active", "accessIPv4": "", "accessIPv6": "", "addresses": {"rcarrillocruz-network": [{"OS-EXT-IPS-MAC:mac_addr": "fa:16:3e:b4:8f:f9", "OS-EXT-IPS:type": "fixed", "addr": "10.0.0.10", "version": 4}, {"OS-EXT-IPS-MAC:mac_addr": "fa:16:3e:b4:8f:f9", "OS-EXT-IPS:type": "floating", "addr": "15.126.136.162", "version": 4}]}, "az": "az2", "cloud": "openstack", "config_drive": "", "created": "2015-03-26T12:08:04Z", "flavor": {"id": "101", "links": [{"href": "https://region-b.geo-1.compute.hpcloudsvc.com/11112764284823/flavors/101", "rel": "bookmark"}], "name": "standard.small"}, "hostId": "39c69fc9ae6e954b182a15ab00d122ea1967d9bd4b4970e231ec6ad5", "human_id": "test_instance", "id": "247dc0ed-deb0-49a5-9960-89c7dbcb64d7", "image": {"id": "9d25fe2d-cf31-4b05-8c58-f238ec78e633", "links": [{"href": "https://region-b.geo-1.compute.hpcloudsvc.com/11112764284823/images/9d25fe2d-cf31-4b05-8c58-f238ec78e633", "rel": "bookmark"}], "name": "9d25fe2d-cf31-4b05-8c58-f238ec78e633"}, "interface_ip": "15.126.136.162", "key_name": "workstation", "links": [{"href": "https://region-b.geo-1.compute.hpcloudsvc.com/v2/11112764284823/servers/247dc0ed-deb0-49a5-9960-89c7dbcb64d7", "rel": "self"}, {"href": "https://region-b.geo-1.compute.hpcloudsvc.com/11112764284823/servers/247dc0ed-deb0-49a5-9960-89c7dbcb64d7", "rel": "bookmark"}], "metadata": {}, "name": "test_instance", "networks": {"rcarrillocruz-network": ["10.0.0.10", "15.126.136.162"]}, "private_v4": "10.0.0.10", "progress": 0, "public_v4": "15.126.136.162", "region": "region-b.geo-1", "security_groups": [{"name": "default"}], "status": "ACTIVE", "tenant_id": "11112764284823", "updated": "2015-03-26T12:10:43Z", "user_id": "11796292308775", "volumes": []}}

PLAY RECAP ******************************************************************** 
localhost                  : ok=2    changed=0    unreachable=0    failed=0   
```

 As you can see, the metadata is empty, should have it populated with 'group: test'.

Regards
