### ISSUE TITLE
ovirt_vms: No module named enum

### ISSUE THREAD

**Issue by gelato** [ansible/ansible-modules-extras#3418]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

ovirt_vms
##### ANSIBLE VERSION

```
2.3.0
```

##### OS / ENVIRONMENT

Linux Mint 18
##### SUMMARY

ImportError: No module named enum While trying to use module - enum and enum34 are installed via pip
##### STEPS TO REPRODUCE

Clone ansible-modules-extras
run:

```
- name: Setup ovirt
    tags:
      - ovirt_deploy
    ovirt_vms:
      auth:
        username: "{{ ovirt_user }}"
        password: "{{ ovirt_pass }}"
        url: "{{ ovirt_control_url }}"
        insecure: true
      state: present
      name: "{{ item.login }}"
      template: unprovisioned
      cluster: "{{ item.cluster_zone }}"
    with_items: "{{ users_to_add }}"
```

```

```

##### EXPECTED RESULTS

Runs without errors
##### ACTUAL RESULTS

"module_stderr": "Shared connection to
10.150.0.250 closed.\r\n", "module_stdout": "Traceback (most recent call last):\r\n  File \"/tmp/ansible_DZX974/ansible_module_ovirt_vms.py\", lin
e 28, in <module>\r\n    from ansible.module_utils.ovirt import *\r\n  File \"/tmp/ansible_DZX974/ansible_modlib.zip/ansible/module_utils/ovirt.py
\", line 27, in <module>\r\nImportError: No module named enum\r\n", "msg": "MODULE FAILURE"}

```

```
