### ISSUE TITLE
known_hosts returns rc:1 

### ISSUE THREAD

**Issue by basictheprogram** [ansible/ansible-modules-extras#3443]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

known_hosts

##### ANSIBLE VERSION

```
$ ansible --version
ansible 2.3.0 (devel de13f91a50) last updated 2016/11/11 15:54:02 (GMT -500)
  lib/ansible/modules/core: (devel 1f0d62b36d) last updated 2016/11/11 15:54:02 (GMT -500)
  lib/ansible/modules/extras: (devel 2fb062604f) last updated 2016/11/11 15:54:03 (GMT -500)
  config file = /Users/tanner/projects/ansible.git/playbooks.git/ansible.cfg
  configured module search path = Default w/o overrides
```

##### CONFIGURATION

Stock configuration

##### OS / ENVIRONMENT

Management host macOS 10.12.1
Manage host Ubuntu Xenial 64-bit

##### SUMMARY

known_hosts fails when trying to add keys to known_hosts file

##### STEPS TO REPRODUCE

```
- name: get ssh_host key
  slurp:
    src: /etc/ssh/ssh_host_ecdsa_key.pub
  register: ssh_host_keys

- name: add ssh key to backuppc server known_hosts
  known_hosts:
    path: /tmp/ssh_known_hosts
    name: "{{ inventory_hostname }}"
    key: "{{ ssh_host_keys.content | b64decode }}"
    state: present
  delegate_to: "{{ backuppc_server_hostname }}"
  remote_user: ansible
```

##### EXPECTED RESULTS

 The contents of  /etc/ssh/ssh_host_ecdsa_key.pub would be put into "{{ backuppc_server_hostname }}" /tmp/ssh_known_hosts

##### ACTUAL RESULTS

Command exits rc:1 every time

```
{"stdout": "", "cmd": "/usr/bin/ssh-keygen -F testing_xenial64 -f /tmp/tmpuI1x8B", "failed": true, "stderr": "", "rc": 1, "invocation": {"module_args": {"path": "/tmp/ssh_known_hosts", "state": "present", "hash_host": false, "name": "testing_xenial64", "key": "ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBFyLyD07x3u20pWB4HS+yDwG1MIy2rFW2txlpERLbK1tP2G9j5VAoPzdAuMZ3H8lOfPG5kgdX/DXguBmVFCdDUs= root@ubuntu-xenial\n"}}, "msg": ""}
```
```
fatal: [testing_xenial64 -> None]: FAILED! => {
    "changed": false,
    "cmd": "/usr/bin/ssh-keygen -F testing_xenial64 -f /tmp/tmpZH3HgP",
    "failed": true,
    "invocation": {
        "module_args": {
            "hash_host": false,
            "key": "ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBFyLyD07x3u20pWB4HS+yDwG1MIy2rFW2txlpERLbK1tP2G9j5VAoPzdAuMZ3H8lOfPG5kgdX/DXguBmVFCdDUs= root@ubuntu-xenial\n",
            "name": "testing_xenial64",
            "path": "/tmp/ssh_known_hosts",
            "state": "present"
        },
        "module_name": "known_hosts"
    },
    "msg": "",
    "rc": 1,
    "stderr": "",
    "stdout": "",
    "stdout_lines": []
}
```
