### ISSUE TITLE
vmware_guest scsi controller type ignored

### ISSUE THREAD

**Issue by pa7ac** [ansible/ansible-modules-extras#3482]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

vmware_guest

##### ANSIBLE VERSION

```
ansible 2.2.0.0
```

##### CONFIGURATION

Default
##### OS / ENVIRONMENT

N/A

##### SUMMARY

When cloning a new vm from template the given value for parameter scsi is ignored and controller in vm is always paravirtual even if controller in template is LSI_parallel

##### STEPS TO REPRODUCE

Create vm from template using vmware_guest and set scsi parameter to other than paravirtual.

```
    - name: Create the VM
      vmware_guest:
        validate_certs: False
        hostname: "{{ vcenter_hostname }}"
        username: "{{ vcenter_user }}"
        password: "{{ vcenter_pass }}"
        name: "{{ inventory_hostname }}"
        state: poweredon
        disk:
            - size_gb: "{{ vm_hdd }}"
              type: thick
              datastore: "{{ esx_datastore }}"
        nic:
            - type: e1000e
              network: "{{ vm_network }}"
              network_type: standard
        hardware:
            memory_mb: "{{ vm_mem }}"
            num_cpus: "{{ vm_cpu }}"
            osid: centos64guest
            scsi: lsi
        datacenter: "{{ vcenter_dc }}"
        esxi_hostname: "{{ esx_host }}"
        template: "{{ vm_template }}"
        wait_for_ip_address: yes
      register: deploy

```

##### EXPECTED RESULTS

SCSI Controller is LSI Parallel
##### ACTUAL RESULTS

SCSI Controller is paravirtual

```

```
