### ISSUE TITLE
blockinfile with delegate_to: localhost results in 1 entry instead of multiple entries

### ISSUE THREAD

**Issue by sbwoodside** [ansible/ansible-modules-extras#3489]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
blockinfile

##### ANSIBLE VERSION
```
ansible 2.1.2.0
  config file = /Users/simon/sandbox/medstack/deployment/ansible/ansible.cfg
  configured module search path = Default w/o overrides
```

##### OS / ENVIRONMENT

OS X El Capitan 10.11.6 (15G1108)

##### SUMMARY
I'm attempting to construct an SSH configuration file on the local machine that will contain `Host` entries for each of the servers in the group. I have 4 remote hosts in this case. I expected that `blockinfile` would add 4 blocks, but instead it's replacing the same block over and over, leaving only one `Host` block for whichever remote host was processed last.

##### STEPS TO REPRODUCE

```
- name: Add current host to SSH config file to give to the client
  blockinfile:
    dest: "{{local_ssh_config_file_path}}"
    backup: yes
    create: yes
    state: present
    marker: "# {mark} MEDSTACK CONFIGURATION"
    block: |
      Host {{'deploy-' + inventory_hostname}}
           User deploy
           IdentityFile ~/.ssh/{{local_ssh_key_file_name}}
           HostName {{inventory_hostname}}
  delegate_to: localhost
  become: no
```

##### EXPECTED RESULTS

Expected to see:

```
# BEGIN MEDSTACK CONFIGURATION
Host host1.example.com
     User deploy
     IdentityFile ~/.ssh/host1.example.com-deploy_ssh_key
     HostName host1.example.com
Host host2.example.com
     User deploy
     IdentityFile ~/.ssh/host2.example.com-deploy_ssh_key
     HostName host2.example.com
Host host3.example.com
     User deploy
     IdentityFile ~/.ssh/host3.example.com-deploy_ssh_key
     HostName host3.example.com
Host host4.example.com
     User deploy
     IdentityFile ~/.ssh/host4.example.com-deploy_ssh_key
     HostName host4.example.com
# END MEDSTACK CONFIGURATION
```
##### ACTUAL RESULTS

```
# BEGIN MEDSTACK CONFIGURATION
Host host4.example.com
     User deploy
     IdentityFile ~/.ssh/host4.example.com-deploy_ssh_key
     HostName host4.example.com
# END MEDSTACK CONFIGURATION
```

**Comment by ansibot** [comment]
@yaegashi ping, this issue is waiting for your response.
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by FelixDefrance** [comment]
Hi, 

Same issue here, so i use with_items, but the issue still there. And if I use "content" instead of "block" we get other strange results..

Step 1: "with_items" and "content" (same issue as initially reported)

```
# cat vars/test_vars
user_present:
  - user1
  - user2
```

```
- name: "Insert/update AllowUsers directive in /etc/ssh/sshd_config"
  become: yes
  tags: ssh-authorized-users
  blockinfile:
    dest: /etc/ssh/sshd_config
    content: |
      {{item}}
    state: present
  with_items:
    - AllowUsers "{{user_present}}"
```
EXPECTED RESULTS
```
# BEGIN ANSIBLE MANAGED BLOCK
AllowUsers user1
AllowUsers user2
# END ANSIBLE MANAGED BLOCK
```

ACTUAL RESULTS
```
# BEGIN ANSIBLE MANAGED BLOCK
AllowUsers user2
# END ANSIBLE MANAGED BLOCK
```

Step 2: "with_items" and "block"

```
- name: "Insert/update AllowUsers directive in /etc/ssh/sshd_config"
  become: yes
  tags: ssh-authorized-users
  blockinfile:
    dest: /etc/ssh/sshd_config
    block: |
      {{item}}
    state: present
  with_items:
    - AllowUsers "{{user_present}}"
```
EXPECTED RESULTS
```
# BEGIN ANSIBLE MANAGED BLOCK
AllowUsers user1
AllowUsers user2
# END ANSIBLE MANAGED BLOCK
```

ACTUAL RESULTS
```
# BEGIN ANSIBLE MANAGED BLOCK
AllowUsers "[u'user1', u'user2']"
# END ANSIBLE MANAGED BLOCK
```
ENVIRONNEMENT 

ansible 2.1.1.0 on Debian Stretch

Thx, 
Félix.
