### ISSUE TITLE
vmware_guest: machine deployment without templates

### ISSUE THREAD

**Issue by karlism** [ansible/ansible-modules-extras#3525]
##### ISSUE TYPE

 - Feature Idea

##### COMPONENT NAME

vmware_guest

##### ANSIBLE VERSION

```
ansible 2.2.0.0
```

##### SUMMARY

Can you please add feature to create VM without any templates specified? We used this scenario with old _vsphere_guest_ module previously, and by default new VMs booted from network and rest of the deployment was automated by kickstart. With vmware_guest module this is no longer possible as it is required to specify template for new VM deployment.

**Comment by ansibot** [comment]
@jctanner ping, this issue is waiting for your response.
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibot** [comment]
This repository has been locked. All new issues and pull requests should be filed in https://github.com/ansible/ansible

Please read through the <a href="http://docs.ansible.com/ansible/dev_guide/repomerge.html#move-issues-and-prs-to-new-repo">repomerge</a> page in the dev guide. The guide contains links to tools which automatically move your issue or pull request to the ansible/ansible repo.

**Comment by afunix** [comment]
Have exactly the same scenario.
I don't need templates as I configure my VMs with vsphere_guest and install OS over PXE.
Would like to migrate from vsphere_guest to vmware_guest, as the first one doesn't work well with some of our hosts.

**Comment by dav1x** [comment]
hey @afunix 

this should be addressed by this PR https://github.com/ansible/ansible/pull/19228

closed via PR# 19228

**Comment by jctanner** [comment]
resolved by https://github.com/ansible/ansible/pull/19228

**Comment by karlism** [comment]
I've finally had the chance to test new changes, but unfortunately _vsphere_guest_ module still fails to deploy VM without a template and displays following error:

> An exception occurred during task execution. To see the full traceback, use -vvv. The error was: KeyError: 'template'
>fatal: [deploytest01]: FAILED! => {"changed": false, "failed": true, "module_stderr": "Traceback (most recent call last):\n  File \"/tmp/ansible_JkSkBu/ansible_module_vmware_guest.py\", line 1349, in <module>\n    main()\n  File \"/tmp/ansible_JkSkBu/ansible_module_vmware_guest.py\", line 1327, in main\n    wait_for_ip=module.params['wait_for_ip_address']\n  File \"/tmp/ansible_JkSkBu/ansible_module_vmware_guest.py\", line 651, in deploy_template\n    template = get_obj(self.content, [vim.VirtualMachine], self.params['template'])\nKeyError: 'template'\n", "module_stdout": "", "msg": "MODULE FAILURE"}

```
- name: "create new ESXi VM"
  connection: local
  vmware_guest:
    hostname: "{{ vcenter_hostname }}"
    username: "{{ vcenter_username }}"
    password: "{{ vcenter_password }}"
    name: "{{ inventory_hostname }}"
    esxi_hostname: "{{ esxi_hostname }}"
    state: poweredoff
    datacenter: "{{ vcenter_datacenter }}"
    annotation: "{{ vm_notes }}"
    wait_for_ip_address: no
    validate_certs: "{{ vcenter_validate_certs }}"
    folder: "{{ vm_folder }}"
    hardware:
      memory_mb: "{{ vm_memory_mb }}"
      num_cpus: "{{ vm_num_cpus }}"
      osid: "{{ vm_osid }}"
      scsi: "{{ vm_scsi_controller }}"
    nic:
      - type: "{{ vm_if_type }}"
        network: "{{ esxi_install_network }}"
        network_type: "{{ vm_network_type }}"
    disk:
      - size_gb: "{{ vm_disk1_size_gb }}"
        type: "{{ vm_disk_type }}"
        datastore: "{{ esxi_datastore }}"
  register: esxi_vm_new
  tags:
    - create
    - esxi_vm
```

If I add "template: False" to the the module options, it starts to clone random live VM (not evan a template) to new VM.
I've tested this with Ansible 2.2.1.0 and this _vmware_guest_ module version:
https://raw.githubusercontent.com/ansible/ansible-modules-extras/devel/cloud/vmware/vmware_guest.py
