### ISSUE TITLE
known_hosts module fails on attempt to remove non-present entry

### ISSUE THREAD

**Issue by mkoshelev** [ansible/ansible-modules-extras#353]
##### Issue Type:

Bug report
##### Ansible Version:

ansible 1.9.0.1
  configured module search path = None
##### Environment:

Fedora 21
##### Summary:

Attempt to remove host entry via known_hosts module fails the task if the host entry in question is not present in .ssh/known_hosts.
##### Steps To Reproduce:

Example playbook:

```
- name: Test known_hosts module
  hosts: localhost

  tasks:
  - name: Try to remove entry from .ssh/known_hosts
    known_hosts: host="no.such.entry" state=absent
```

If for some reason you have 'no.such.entry' in .ssh/known_hosts - just run the playbook twice :)
##### Expected Results:

Task completes successfully. No changes reported.
##### Actual Results:

Task fails:

```
failed: [localhost] => {"cmd": "/usr/bin/ssh-keygen -F no.such.entry -f /home/user/.ssh/known_hosts", "failed": true, "rc": 1}
```
