### ISSUE TITLE
ec2_ami_copy | The parameter Encrypted is not recognized

### ISSUE THREAD

**Issue by jackivanov** [ansible/ansible-modules-extras#3565]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
ec2_ami_copy

##### ANSIBLE VERSION
```
ansible 2.2.0.0
  config file =
  configured module search path = Default w/o overrides
```

##### OS / ENVIRONMENT
MacOS Sierra, Darwin Kernel Version 16.1.0
boto 2.43.0

##### SUMMARY
getting this error when trying to copy an image to an encrypted image

##### STEPS TO REPRODUCE
run the playbook

```
- ec2_ami_copy:
    aws_access_key: "{{ aws_access_key }}"
    aws_secret_key: "{{ aws_secret_key }}"
    description: ENC_IMAGE
    encrypted: yes
    name: newimage
    region: "{{ region }}"
    source_image_id: "{{ source_ami_image }}"
    source_region: "{{ region }}"
```

##### EXPECTED RESULTS
Successful copy an image to an encrypted image

##### ACTUAL RESULTS
```
fatal: [localhost]: FAILED! => {
    "changed": false,
    "failed": true,
    "invocation": {
        "module_args": {
            "aws_access_key": "******",
            "aws_secret_key": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
            "description": "ENC_IMAGE",
            "ec2_url": null,
            "encrypted": yes,
            "kms_key_id": null,
            "name": "newimage",
            "profile": null,
            "region": "eu-central-1",
            "security_token": null,
            "source_image_id": "ami-82cf0aed",
            "source_region": "eu-central-1",
            "tags": null,
            "validate_certs": true,
            "wait": false,
            "wait_timeout": "1200"
        },
        "module_name": "ec2_ami_copy"
    },
    "msg": "UnknownParameter: The parameter Encrypted is not recognized"
}
```
