### ISSUE TITLE
consul_acl keyring and operator ACL types

### ISSUE THREAD

**Issue by williamlord** [ansible/ansible-modules-extras#3592]
##### ISSUE TYPE
 - Feature Idea

##### COMPONENT NAME
consul_acl (http://docs.ansible.com/ansible/consul_acl_module.html)

##### ANSIBLE VERSION
```
ansible 2.2.0.0
```

##### SUMMARY
Add support for the new ACL types keyring and operator which Consul introduced in 0.6.0 and 0.7.0 respectively.
https://github.com/hashicorp/consul/blob/master/acl/policy.go#L23-L24

##### STEPS TO REPRODUCE
Rule types keyring and operator, no expanding required just a policy.

```
- consul_acl:
    rules:
      - keyring: read
      - operator: write
```
