### ISSUE TITLE
can not use variable in responses key of expect module

### ISSUE THREAD

**Issue by hanks** [ansible/ansible-modules-extras#3640]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME
expect

##### ANSIBLE VERSION

```
ansible 2.2.0.0
  config file = 
  configured module search path = Default w/o overrides
```

##### OS / ENVIRONMENT

macOS 10.11.3

##### SUMMARY

can not use variable in responses key of expect module

```
- name: expect test
   expect: 
     command: xxxx
     response:
       "{{ path }}": "yes"
```

##### EXPECTED RESULTS
It should check the prompt with the `path` value, and input `yes`

##### ACTUAL RESULTS

No response for the prompt
