### ISSUE TITLE
openvswitch_bridge ansible 2.3.0

### ISSUE THREAD

**Issue by Mr-Pi** [ansible/ansible-modules-extras#3703]
Failed to add ovs bridge with parent bridge and vlan.

**config:**
```
# Create a bridge named br-int
- openvswitch_bridge:
    bridge: br-int
    state: present

# Create a fake bridge named br-bla within br-int on the VLAN 405
- openvswitch_bridge:
    bridge: br-bla                                                                                                                                                                                                                                                                                                            
    parent: br-int
    vlan: 405 
    state: present
```
output of `ansible-playbook -i ./staging all.yml -l firewalk_new -vvv`
```
TASK [firewall : openvswitch_bridge] *****************************************************************************************************************************************************************************************************************************************************************************************
task path: /home/mrpi/hg/stuvus_config/roles/firewall/tasks/ovs.yml:8
Using module file /usr/lib64/python2.7/site-packages/ansible/modules/network/ovs/openvswitch_bridge.py
<firewalk_new> ESTABLISH SSH CONNECTION FOR USER: None
<firewalk_new> SSH: EXEC ssh -C -o ControlMaster=auto -o ControlPersist=60s -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o ConnectTimeout=10 -o ControlPath=/home/mrpi/.ansible/cp/724597da8b firewalk_new '/bin/sh -c '"'"'echo ~ && sleep 0'"'"''
<firewalk_new> ESTABLISH SSH CONNECTION FOR USER: None
<firewalk_new> SSH: EXEC ssh -C -o ControlMaster=auto -o ControlPersist=60s -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o ConnectTimeout=10 -o ControlPath=/home/mrpi/.ansible/cp/724597da8b firewalk_new '/bin/sh -c '"'"'( umask 77 && mkdir -p "` echo /root/.ansible/tmp/ansible-tmp-1486665710.24-63225261149860 `" && echo ansible-tmp-1486665710.24-63225261149860="` echo /root/.ansible/tmp/ansible-tmp-1486665710.24-63225261149860 `" ) && sleep 0'"'"''
<firewalk_new> PUT /tmp/tmpmvOJZ1 TO /root/.ansible/tmp/ansible-tmp-1486665710.24-63225261149860/openvswitch_bridge.py
<firewalk_new> SSH: EXEC sftp -b - -C -o ControlMaster=auto -o ControlPersist=60s -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o ConnectTimeout=10 -o ControlPath=/home/mrpi/.ansible/cp/724597da8b '[firewalk_new]'
<firewalk_new> ESTABLISH SSH CONNECTION FOR USER: None
<firewalk_new> SSH: EXEC ssh -C -o ControlMaster=auto -o ControlPersist=60s -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o ConnectTimeout=10 -o ControlPath=/home/mrpi/.ansible/cp/724597da8b firewalk_new '/bin/sh -c '"'"'chmod u+x /root/.ansible/tmp/ansible-tmp-1486665710.24-63225261149860/ /root/.ansible/tmp/ansible-tmp-1486665710.24-63225261149860/openvswitch_bridge.py && sleep 0'"'"''
<firewalk_new> ESTABLISH SSH CONNECTION FOR USER: None
<firewalk_new> SSH: EXEC ssh -C -o ControlMaster=auto -o ControlPersist=60s -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o ConnectTimeout=10 -o ControlPath=/home/mrpi/.ansible/cp/724597da8b -tt firewalk_new '/bin/sh -c '"'"'sudo -H -S -n -u root /bin/sh -c '"'"'"'"'"'"'"'"'echo BECOME-SUCCESS-xwayyhuofuxcacbadumfwrfnyhblrbkg; /usr/bin/python /root/.ansible/tmp/ansible-tmp-1486665710.24-63225261149860/openvswitch_bridge.py; rm -rf "/root/.ansible/tmp/ansible-tmp-1486665710.24-63225261149860/" > /dev/null 2>&1'"'"'"'"'"'"'"'"' && sleep 0'"'"''
fatal: [firewalk_new]: FAILED! => {
    "changed": false, 
    "failed": true, 
    "invocation": {
        "module_args": {
            "bridge": "br-bla", 
            "external_ids": null, 
            "fail_mode": null, 
            "parent": "br-int", 
            "set": null, 
            "state": "present", 
            "timeout": 5, 
            "vlan": 405
        }
    }, 
    "msg": "argument of type 'int' is not iterable"
}
```
