### ISSUE TITLE
npm module verbose information omits package name when pinned 

### ISSUE THREAD

**Issue by JeanFred** [ansible/ansible-modules-extras#577]
Issue Type: Bug report
Ansible Version: 1.9.1
Environment: Ubuntu 14.04
Summary: the NPM module does not output the package name when this include pinned version in verbose mode
### Steps To Reproduce

Running the following playbook:

```
- name: Install PhantomJS
  npm:
    name: phantomjs@1.9.17
    state: present
    global: yes
```
### Actual results

```
TASK: [Install PhantomJS] ************************************* 
<hostname> REMOTE_MODULE npm name= state=present
changed: [hostname] => {"changed": true}
```
### Expected results

```
TASK: [Install PhantomJS] ************************************* 
<hostname> REMOTE_MODULE npm name=phantomjs@1.9.17 state=present
changed: [hostname] => {"changed": true}
```

Thanks for looking into this!
