### ISSUE TITLE
Incompatiblity of firewalld module with service module

### ISSUE THREAD

**Issue by cortopy** [ansible/ansible-modules-extras#617]
Firewalld module doesn't seem to be compatible with the reloaded state of the service module.

The following configuration works fine the first time I run my playbook

```
- name: Enable at boot and start firewallD
    service: name=firewalld enabled=yes state=started

- name: Configure firewallD services
    firewalld: service={{item.service}} permanent={{item.permanency}} state={{item.state}}
    with_items:
      - { service: http, permanency: true, state: enabled}
      - { service: https, permanency: true, state: enabled}
    notify:
      - reload firewalld

handlers :
    - name: reload firewalld
      service: name=firewalld state=reloaded
```

However, I've noticed some strange behaviour when the handler is triggered a second time in order to reload firewalld. The result is that firewallD gets stopped altogether 

The report shows that the handler was run OK

```
NOTIFIED: [reload firewalld] ************************************************** 
changed: [host]
```

And yet, firewallD has stopped this second time as checked via ssh with `firewall-cmd --state`

Running the playbook a third time in a way that the handler is triggered restart firewall daemon again.

Some further observations after trying to debug this:
- Results are the same if handler is run as a task to force the reload every time for debugging purposes
- Firewall daemon is definitely running as report always shows that the task "Enable at boot and start firewallD" is OK
