### ISSUE TITLE
npm install is slow

### ISSUE THREAD

**Issue by warrenseine** [ansible/ansible-modules-extras#681]
The `npm` module is really slow (probably because `npm` itself is slow).

For instance, it's much faster to write:

```
- name: check installed global npm modules
  shell: cat /usr/lib/node_modules/{{ item.name }}/package.json | jq -r '.version'
  with_items:
    - { name: forever, version: 0.14.2 }
    - { name: babel, version: 5.6.14 }
  register: result
  failed_when: no
  changed_when: result.stdout != "{{ item.version }}"

- name: install global npm modules
  npm: name={{ item.item.name }} version={{ item.item.version }} global=yes state=present
  with_items: result.results
  when: item.changed
```

Than:

```
- name: install global npm modules
  npm: name={{ item.name }} version={{ item.version }} global=yes state=present
  with_items:
    - { name: forever, version: 0.14.2 }
    - { name: babel, version: 5.6.14 }
```

I'm not sure there's anything to act on, but I'm leaving this here so it can help others.

**Comment by pjdufour** [comment]
The following might be helpful for some static development use cases.  I'm looping over multiple static Jekyll website repos (as a dict of ids and paths).  I want to be able to jump back and forth quickly between sites and rebuild with `gulp`.  Using some Jinja2 filters (http://docs.ansible.com/ansible/playbooks_filters.html), I'm loading the dependencies directly from a folders package.json.  Also just referencing stdout directly in the following task, so don't need to reuse changed/failed fields.

**main.yml**

```
- include: npm_packages.yml
  with_dict: "{{ STATIC_SRC }}"
```

**npm_packages.yml**

```
- set_fact: static_package_dir="{{ item.value }}"

- shell: "cat {{ static_package_dir }}/package.json | jq -r '.devDependencies'"
  register: result

- set_fact: devDependencies="{{ result.stdout | from_json }}"

- name: Check Static Development Environment
  shell: "cat {{ static_package_dir }}/node_modules/{{ item.key }}/package.json | jq -r '.version'"
  with_dict: "{{ devDependencies }}"
  register: version_check
  changed_when: no
  failed_when: no

- name: Install Static Development Libraries to Environment
  npm: name={{ item.item.key }} version={{ item.item.value }} path="{{ static_package_dir }}" state=present
  with_items: version_check.results
  when:
    item.stdout == "" or (item.item.value != "*" and item.stdout != item.item.value)
```

Doesn't handle for the '~' or '^' version prefix in package.json, but should speed up npm package checking none the less ('~' and '^' could probably be supported with some more `when` magic conditional logic).
