### ISSUE TITLE
ufw module does not allow specifying both interface and source IP

### ISSUE THREAD

**Issue by m00dawg** [ansible/ansible-modules-extras#69]
It looks as though the ufw module does not allow specifying both an interface and a from_ip. The following code block was producing what appears to have been a ufw-related error:

```
- name: Allow MySQL/Galera Traffic Over Cluster Network
  ufw: rule=allow proto=tcp
        from_ip="{{ mysql_galera_network }}"
        interface="{{ mysql_galera_interface }}"
        to_port={{ item }}
  with_items:
    - "4567"
    - "3306"
  when: mysql_use_galera == true
```

The resulting error is:

...
failed: [stage-mysqlcluster4.teamsnap.com] => (item=3306) => {"failed": true, "item": "3306"} msg: ERROR: Invalid token 'on'
...

Removing the interface line, however, alleviates the issue. The documentation on the module page (http://docs.ansible.com/ufw_module.html) indicates this should be allowed, although the examples do not necessarily match the options table.

**Comment by sivel** [comment]
IIRC, you need to specify `direction=in` to resolve this problem.

**Comment by m00dawg** [comment]
Aha! Yep adding that in does work. For reference, the full command is now:

```
- name: Allow MySQL/Galera Traffic Over Cluster Network
  ufw: rule=allow proto=tcp
        from_ip="{{ mysql_galera_network }}"
        interface="{{ mysql_galera_interface }}" direction=in
        to_port={{ item }}
  with_items:
    - "4567"
    - "3306"
    - "4444"
  when: mysql_use_galera == true
```

Thanks for the help!
