### ISSUE TITLE
[osx_defaults] cannot specify value = false (without quotes)

### ISSUE THREAD

**Issue by sk-** [ansible/ansible-modules-extras#709]
##### Issue Type:

Bug report
##### Ansible Version:

2.0.0 (installed from sources)
##### Ansible Configuration:

Nothing special
##### Environment:

N/A
##### Summary:

[osx_defaults] cannot specify value = false (without quotes)
##### Steps To Reproduce:

If you have the task

``` yaml
  osx_defaults:
    domain: /Library/Preferences/com.apple.loginwindow
    key: GuestEnabled
    state: present
    value: false
    type: boolean
```

it fails because, yaml first converts 'false' to False and then osx_defaults, lowercases it. See https://github.com/ansible/ansible-modules-extras/blob/9db032aa118425cde4db904b0e8efac5ed07735b/system/osx_defaults.py#L127-130.

It is weird that it lowercases the value and then expects it to be any of [True, 1, ...].

Note that the same happens with value: no.

The workaround is to specify it with quotes: "false" or "no".
##### Expected Results:

To succsfully set the variable to false.
##### Actual Results:

Failure
