### ISSUE TITLE
mysql_replication module:  warning from MySQLdb.Warning result in failed task

### ISSUE THREAD

**Issue by nadley** [ansible/ansible-modules-extras#719]
##### Issue Type:

Bug Report
##### Ansible Version:

ansible --version
ansible 1.9.2
  configured module search path = None
##### Ansible Configuration:

```
[defaults]
# smart - gather by default, but don't regather if already gathered
# implicit - gather by default, turn off with gather_facts: False
# explicit - do not gather by default, must say gather_facts: True
gathering = smart

# if set to a persistant type (not 'memory', for example 'redis') fact values
# from previous runs in Ansible will be stored.  This may be useful when
# wanting to use, for example, IP information from one group of servers
# without having to talk to them in the same playbook run to get their
# current IP information.
# fact_caching = memory

fact_caching = jsonfile
fact_caching_connection = /tmp/ansiblefacts

```
##### Environment:

Running from Debian 8
Managing Debian 8
##### Summary:

When running a playbook to setup MySQL replication with a task doing  mode=changemaster the task failed, after a warning from MySQLdb. The warning complains about "Sending passwords in plain text without SSL/TLS is extremely insecure"
##### Steps To Reproduce:

Create a playbook to setup mysql and replication with a task like this which should be run on slave MySQL to declare the master host : 

```
- name: Change the master in slave to start the replication
  mysql_replication: mode=changemaster master_host={{ mysql_repl_master }} master_log_file={{ repl_stat.File }} master_log_pos={{ repl_stat.Position }} master_user={{ mysql_replication_user }} master_password={{ mysql_replication_user_password }}
```
##### Expected Results:

```
TASK: [mysql | Change the master in slave to start the replication] *** 
changed: [mysql2.preprod]
```
##### Actual Results:

```
failed: [mysql2.preprod] => {"failed": true, "parsed": false}
Traceback (most recent call last):
  File "/root/.ansible/tmp/ansible-tmp-1437058776.53-24949336144903/mysql_replication", line 2001, in <module>
    main()
  File "/root/.ansible/tmp/ansible-tmp-1437058776.53-24949336144903/mysql_replication", line 379, in main
    changemaster(cursor, chm, chm_params)
  File "/root/.ansible/tmp/ansible-tmp-1437058776.53-24949336144903/mysql_replication", line 174, in changemaster
    cursor.execute(query, chm_params)
  File "/usr/lib/python2.7/dist-packages/MySQLdb/cursors.py", line 176, in execute
    if not self._defer_warnings: self._warning_check()
  File "/usr/lib/python2.7/dist-packages/MySQLdb/cursors.py", line 92, in _warning_check
    warn(w[-1], self.Warning, 3)
_mysql_exceptions.Warning: Sending passwords in plain text without SSL/TLS is extremely insecure.

```

**Comment by nadley** [comment]
@jimi-c Here is the new issue ;-)

**Comment by grypyrg** [comment]
This fix was necessary for me as well (@banyek!)

**Comment by Jmainguy** [comment]
Hey, is this still ongoing?

**Comment by banyek** [comment]
No idea.

**Comment by agireud** [comment]
Still seeing this on Ansible 2.0.0.2

**Comment by grypyrg** [comment]
The warnings will remain. we have to have this patch to work with all mysql environments.

**Comment by altmannmarcelo** [comment]
Issue still on Ansible 2.1.0.0

**Comment by dtest** [comment]
For now, my workaround in Ansible 2.1.0.0 is to rewrite `changed_when` and `failed_when` options:

``` yaml
- name: Change the master in slave to start the replication
  mysql_replication:
    mode: changemaster
    master_host: "{{ master_host }}"
    master_log_file: "{{ master_coords['File'] }}"
    master_log_pos: "{{ master_coords['Position'] }}"
    master_user: "{{ mysql_replication['user'] }}"
    master_password: "{{ mysql_replication['password'] }}"
  when: slave|failed and db_role == 'slave'
  register: change_master
  failed_when: change_master|failed and change_master.msg.find('Sending passwords in plain text') == -1
  changed_when: change_master|failed and change_master.msg.find('Sending passwords in plain text') != -1
```

But would like to see proper fix for this module. Looks like some recent activity with #2594 going in the right direction. Thanks @srvg
