### ISSUE TITLE
gluster_volume: unsupported parameter for module: bricks

### ISSUE THREAD

**Issue by BrianHicks** [ansible/ansible-modules-extras#721]
**Issue Type:** Bug Report
**Ansible Version:**

```
ansible 1.9.2
  configured module search path = None
```

**Environment**: OSX 10.10.4 connecting to Centos 7.1
**Summary:** The `gluster_volume` module isn't recognizing the "bricks" parameter.
**Steps to Reproduce**:
Enter this into your playbook:

```
- name: create glusterfs volumes
  run_once: true
  sudo: yes
  gluster_volume:
    bricks: "{{ glusterfs_server_data_location }}/{{ item }}"
    force: true # TODO: separate partitions so we don't have to do this
    name: "{{ item }}"
    rebalance: yes
    replicas: "{{ glusterfs_replication }}"
    state: present
  with_items: glusterfs_volumes
```

(also tried by mimicking the bricks syntax from the `gluster` CLI tool. EG `host1:/brickpath,host2:/brickpath`

**Expected Results:**

Playbook runs without error, volume is created. I am able to create the volume by running the analagous `gluster` command(s).

**Actual Results:**

Playbook halts Ansible with this result:

```
TASK: [glusterfs | create glusterfs volumes] **********************************
failed: [batman-control-02] => (item=docker) => {"failed": true, "item": "docker"}
msg: unsupported parameter for module: bricks

FATAL: all hosts have already failed -- aborting
```
