### ISSUE TITLE
locale_gen is_present check fails with some locales

### ISSUE THREAD

**Issue by madddi** [ansible/ansible-modules-extras#741]
##### Issue Type:

Bug Report
##### Ansible Version:

```
ansible 1.9.2
  configured module search path = None
```
##### Ansible Configuration:

No custom config
##### Environment:

Managing OS: OS X 10.10.4
Target OS: Debian Jessie
##### Summary:

`locale_gen` uses the ouput of `locale -a` to test if a given locale is already enabled ([See here](https://github.com/ansible/ansible-modules-extras/blob/devel/system/locale_gen.py#L67)). If the name of the locale differs from the name in `/etc/locale.gen` the test will fail and the locale will be enabled every time. Example:

```
# egrep -i '^en_us.iso.+15$' /etc/locale.gen
en_US.ISO-8859-15 ISO-8859-15
# locale -a | egrep -i '^en_us.iso.+15$'
en_US.iso885915
```
##### Steps To Reproduce:

Run the following playbook multiple times:

```

---
- hosts: all
  vars:
    locales:
      - "en_US"
      - "en_US.ISO-8859-15"
  tasks:
  - locale_gen: name="{{ item }}" state=present
    with_items: "{{ locales }}"
```
##### Expected Results:

Both tasks should report "changed" only after the first run, if at all. The following run should report "changed=0" because both locales are already enabled.
##### Actual Results:

While "en_US" only gets enabled once, "en_US.ISO-8859-15" will be enabled every time.
