### ISSUE TITLE
Using win_iis_webbinding fails with "missing required argument"

### ISSUE THREAD

**Issue by stu-smith** [ansible/ansible-modules-extras#744]
It seems that any use of win_iis_webbinding fails with the message "missing required argument":

```
# ansible -m win_iis_webbinding -a "name='Default Web Site'" name.of.instance
name.of.instance | FAILED! => {
    "changed": false,
    "failed": true,
    "msg": "missing required argument: name"
}
```

(Other "older" Windows modules work just fine eg win_feature).

I have tried this both as an ad-hoc module command, and from a playbook:

```

---

- name: 'Remove default website'
  hosts: all
  gather_facts: false
  tasks:
    - name: 'Remove default website'
      win_iis_webbinding:
        name: 'Default Web Site'
        state: absent
```

I'm working from Ansible grabbed from source. I notice v2.0.0 is still in development - are these new Windows modules complete, or still in development?

Cheers!
