### ISSUE TITLE
opkg module does not support the --force group of options

### ISSUE THREAD

**Issue by isotopp** [ansible/ansible-modules-extras#881]
opkg command has a number of --force options, which are requires for example to install procps-top replacing the busybox top.

**Comment by isotopp** [comment]
Example:

```
- name: install full top command
  hosts: access-points
  tasks:
    - name: force install full top
      opkg: name=procps-top force=overwrite
```
