### ISSUE TITLE
Bower needs an executable option.

### ISSUE THREAD

**Issue by kitsunde** [ansible/ansible-modules-extras#888]
I use [nvm](https://github.com/creationix/nvm) and so my bower isn't available on a system level:

``` shell
$ which bower
/home/vagrant/.nvm/v0.12.7/bin/bower
```

This of course means ansible can't find bower. Can we have an executable arg like on the [pip](https://docs.ansible.com/ansible/pip_module.html) and [npm](https://docs.ansible.com/ansible/npm_module.html) modules please?

**Comment by kitsunde** [comment]
Regarding using nvm. I'm setting the path manually instead.

``` yml
- bower:
    path=foo
  environment:
    PATH: {{nvm_path}}:{{ ansible_env.PATH }}
```

This is a better solution for my use case. I still think it's inconsistent with regards to other modules not to have the executable option though.
