### ISSUE TITLE
Error in slack module if used as the example says

### ISSUE THREAD

**Issue by varnav** [ansible/ansible-modules-extras#960]
##### Issue Type:
- Bug Report
##### Ansible Version:

1.9.2
##### Environment:

CentOS 7
##### Steps To Reproduce:

Use example from docs in your playbook:

```
- name: Send notification message via Slack
  local_action:
    module: slack
    token: tokeninthenewformat
    msg: "{{ inventory_hostname }} completed"
```
##### Expected Results:

Message is sent to slack
##### Actual Results:

ERROR: msg is not a legal parameter in an Ansible task or handler
